/*******************************************************************************
 * Copyright (c) 2024, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.endpoint;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import static org.mockito.ArgumentMatchers.*;
import java.util.*;
import java.util.stream.*;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.configuration.ComponentConfiguration;
import org.eclipse.kura.configuration.metatype.OCD;
import org.eclipse.kura.core.identity.IdentityServiceImpl;
import org.eclipse.kura.core.testutil.requesthandler.TransportType;
import org.eclipse.kura.core.testutil.requesthandler.Transport.MethodSpec;
import org.eclipse.kura.identity.*;
import org.eclipse.kura.identity.configuration.extension.IdentityConfigurationExtension;
import org.eclipse.kura.internal.rest.identity.provider.IdentityRestServiceV2;
import org.eclipse.kura.internal.rest.identity.provider.util.IdentityDTOUtils;
import org.eclipse.kura.internal.rest.identity.provider.v2.dto.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;
import com.google.gson.Gson;

class IdentityV2EndpointsIT extends EndpointTestBase {
    private static final String MQTT_APP_ID = "IDN-V2";
    private static final String REST_APP_ID = "identity/v2";
    private static final String METHOD_SPEC_GET = "GET";
    private static final String METHOD_SPEC_POST = "POST";
    private static final String METHOD_SPEC_DELETE = "DELETE";
    private static final String MQTT_METHOD_SPEC_DEL = "DEL";
    private static final String METHOD_SPEC_PUT = "PUT";
    private static final int HTTP_STATUS_CONFLICT = 409;
    private final Gson gson = new Gson();
    private final String testUsername = "test.identity";
    private final String testPermissionName = "test.permission";
    private IdentityServiceImpl identityService;
    private IdentityRestServiceV2 endpoint;
    private IdentityDTO identity;
    private IdentityConfigurationRequestDTO identityConfigurationRequestDTO;
    private IdentityConfigurationDTO identityConfiguration;
    private PasswordConfigurationDTO passwordConfiguration;
    private AdditionalConfigurationsDTO additionalConfigurations;
    private PermissionConfigurationDTO permissionConfiguration;
    private final Map<String, MockExtensionHolder> extensions = new HashMap<>();

    @BeforeEach
    void registerEndpoint() {
        this.identity = null;
        this.identityConfigurationRequestDTO = null;
        this.identityConfiguration = null;
        this.passwordConfiguration = null;
        this.additionalConfigurations = null;
        this.permissionConfiguration = null;
        this.extensions.clear();
        this.identityService = this.http.identityFixture().service;
        this.endpoint = new IdentityRestServiceV2();
        this.endpoint.bindIdentityService(this.identityService);
        this.endpoint.bindPasswordStrengthVerificationService(this.http.identityFixture().passwordStrength);
        this.endpoint.bindRequestHandlerRegistry(this.cloud);
        this.http.resource(this.endpoint);
    }
    @AfterEach
    void unregisterEndpoint() {
        if (this.endpoint != null) { this.endpoint.unbindRequestHandlerRegistry(this.cloud); }
        this.extensions.forEach((pid, holder) -> this.identityService.unsetIdentityConfigurationExtension(
                holder.extension, Map.of("kura.service.pid", pid)));
        this.extensions.clear();
    }
    @ParameterizedTest
    @EnumSource(TransportType.class)
    void shouldInvokeCreateIdentitySuccessfully(TransportType type) throws Exception {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);
        givenNewIdentity(new IdentityDTO(this.testUsername));

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_POST), "/identities", gson.toJson(this.identity));

        thenRequestSucceeds();
        thenResponseBodyIsEmpty();
        assertTrue(this.identityService.getIdentityConfiguration(this.testUsername, Set.of()).isPresent());
    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    void shouldReturnErrorIfIdentityAlreadyExists(TransportType type) throws Exception {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);
        givenExistingIdentity(new IdentityDTO(this.testUsername));

        givenNewIdentity(new IdentityDTO(this.testUsername));

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_POST), "/identities", gson.toJson(this.identity));

        thenResponseCodeIs(HTTP_STATUS_CONFLICT);
        thenResponseBodyIsNotEmpty();
    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    void shouldUpdateIdentityWithConfiguration(TransportType type) throws Exception {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);
        givenExistingIdentity(new IdentityDTO(this.testUsername));
        givenExistingPermission(new PermissionDTO(this.testPermissionName));
        givenMockIdentityConfigurationExtension("test.extension");
        givenMockIdentityConfigurationExtension("test2.extension");

        givenPermissionConfiguration(this.testPermissionName);
        givenPasswordConfiguration("Abcdef1234567@", true, false);
        givenAdditionalConfigurations(TestComponentConfiguration.forPid("test.extension"),
                TestComponentConfiguration.forPid("test2.extension"));

        givenIdentityConfigurationFor(new IdentityDTO(this.testUsername));

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_PUT), "/identities", gson.toJson(this.identityConfiguration));

        thenRequestSucceeds();
        thenResponseBodyIsEmpty();
        this.identityService.checkPassword(this.testUsername, "Abcdef1234567@".toCharArray());
        for (var extension : this.extensions.values()) {
            assertEquals(Map.of("foo", "bar"), extension.configurations.get(this.testUsername).getConfigurationProperties());
        }
    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    void shouldGetIdentityByName(TransportType type) throws Exception {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);
        givenExistingIdentity(new IdentityDTO(this.testUsername));
        givenExistingPermission(new PermissionDTO(this.testPermissionName));
        givenAssignedPermissionToIdentity();

        givenIdentityConfigurationRequestDTO();

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_POST), "/identities/byName",
                gson.toJson(this.identityConfigurationRequestDTO));

        thenRequestSucceeds();
        thenResponseBodyEqualsJson("{\"identity\":{\"name\":\"" + this.testUsername
                + "\"},\"permissionConfiguration\":{\"permissions\":[{\"name\":\"" + this.testPermissionName
                + "\"}]},\"passwordConfiguration\":{\"passwordChangeNeeded\":false,\"passwordAuthEnabled\":false},\"additionalConfigurations\":{\"configurations\":[]}}");
    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    void shouldGetIdentityDefaultByName(TransportType type) throws Exception {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);
        givenExistingIdentity(new IdentityDTO(this.testUsername));
        givenExistingPermission(new PermissionDTO(this.testPermissionName));
        givenIdentityConfigurationRequestDTO();

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_POST), "/identities/default/byName",
                gson.toJson(this.identityConfigurationRequestDTO));

        thenRequestSucceeds();
        thenResponseBodyEqualsJson("{\"identity\":{\"name\":\"" + this.testUsername
                + "\"},\"permissionConfiguration\":{\"permissions\":[]},\"passwordConfiguration\":{\"passwordChangeNeeded\":false,\"passwordAuthEnabled\":false},\"additionalConfigurations\":{\"configurations\":[]}}");
    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    void shouldDeleteExistingIdentity(TransportType type) throws Exception {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);
        givenExistingIdentity(new IdentityDTO(this.testUsername));

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_DELETE, MQTT_METHOD_SPEC_DEL), "/identities",
                gson.toJson(new IdentityDTO(this.testUsername)));

        thenRequestSucceeds();
        thenResponseBodyIsEmpty();

        assertFalse(this.identityService.getIdentityConfiguration(this.testUsername, Set.of()).isPresent());
    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    void shouldReturnErrorDeletingNonExistingIdentity(TransportType type) throws Exception {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_DELETE, MQTT_METHOD_SPEC_DEL), "/identities",
                gson.toJson(new IdentityDTO(this.testUsername)));

        thenResponseCodeIs(404);
        thenResponseBodyEqualsJson("{\"message\":\"Identity not found\"}");

    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    void shouldReturnErrorDeletingWithMalformedIdentityRequest(TransportType type) throws Exception {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_DELETE, MQTT_METHOD_SPEC_DEL), "/identities",
                "{\"nm\":\"identity\"}");

        thenResponseCodeIs(400);
        thenResponseBodyEqualsJson("{\"message\":\"Missing 'name' property\"}");

    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    void shouldGetDefinedPermissions(TransportType type) throws Exception {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);
        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_GET), "/definedPermissions");

        thenRequestSucceeds();
        thenResponseBodyIsNotEmpty();

    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    void shouldGetIdentities(TransportType type) throws Exception {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);
        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_GET), "/identities");

        thenRequestSucceeds();
        thenResponseBodyIsNotEmpty();

    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    void shouldGetPasswordStrenghtRequirements(TransportType type) throws Exception {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);

        givenPasswordStrenghtServiceMockConfiguration(8, false, false, false);

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_GET), "/passwordStrenghtRequirements");

        thenRequestSucceeds();
        thenResponseBodyIsNotEmpty();

    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    void shouldCreatePermission(TransportType type) throws Exception {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);
        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_POST), "/permissions",
                gson.toJson(new PermissionDTO(testPermissionName)));

        thenRequestSucceeds();
        thenResponseBodyIsEmpty();

        assertTrue(this.identityService.getPermissions().contains(new Permission(this.testPermissionName)));
    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    void shouldDeleteExistingPermission(TransportType type) throws Exception {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);
        givenExistingPermission(new PermissionDTO(this.testPermissionName));

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_DELETE, MQTT_METHOD_SPEC_DEL), "/permissions",
                gson.toJson(new PermissionDTO(this.testPermissionName)));

        thenRequestSucceeds();
        thenResponseBodyIsEmpty();

        assertFalse(this.identityService.getPermissions().contains(new Permission(this.testPermissionName)));
    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    void shouldReturnErrorDeletingNonExistingPermission(TransportType type) throws Exception {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_DELETE, MQTT_METHOD_SPEC_DEL), "/permissions",
                gson.toJson(new PermissionDTO(this.testPermissionName)));

        thenResponseCodeIs(404);
        thenResponseBodyEqualsJson("{\"message\":\"Permission not found\"}");

    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    void shouldReturnErrorDeletingWithMalformedPermissionRequest(TransportType type) throws Exception {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_DELETE, MQTT_METHOD_SPEC_DEL), "/permissions",
                "{\"nm\":\"permission\"}");

        thenResponseCodeIs(400);
        thenResponseBodyEqualsJson("{\"message\":\"Missing 'name' property\"}");

    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    void shouldValidateIdentityConfiguration(TransportType type) throws Exception {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);
        givenExistingIdentity(new IdentityDTO(this.testUsername));

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_POST), "/identities/validate",
                gson.toJson(new IdentityConfigurationDTO(new IdentityDTO(this.testUsername))));

        thenRequestSucceeds();
    }

    private void givenAdditionalConfigurations(ComponentConfiguration... componentConfigurations) {

        this.additionalConfigurations = new AdditionalConfigurationsDTO();
        this.additionalConfigurations.setConfigurations(Stream.of(componentConfigurations)
                .map(IdentityDTOUtils::fromComponentConfiguration).collect(Collectors.toSet()));

    }

    private void givenPermissionConfiguration(String... permissionNames) {
        this.permissionConfiguration = new PermissionConfigurationDTO();
        this.permissionConfiguration.setPermissions(new HashSet<PermissionDTO>(
                Stream.of(permissionNames).map(PermissionDTO::new).collect(Collectors.toList())));

    }

    private void givenExistingPermission(PermissionDTO permissionDTO) {
        try {
            identityService.createPermission(IdentityDTOUtils.toPermission(permissionDTO));
        } catch (KuraException e) {
            e.printStackTrace();
            fail("unable to create the permission");
        }
    }

    private void givenPasswordConfiguration(String password, boolean passwordAuthEnabled,
            boolean passwordChangeEnabled) {
        this.passwordConfiguration = new PasswordConfigurationDTO();

        this.passwordConfiguration.setPassword(password);
        this.passwordConfiguration.setPasswordAuthEnabled(passwordAuthEnabled);
        this.passwordConfiguration.setPasswordChangeNeeded(passwordChangeEnabled);
    }

    private void givenIdentityConfigurationFor(IdentityDTO identityDTO) {
        this.identityConfiguration = new IdentityConfigurationDTO(identityDTO);

        this.identityConfiguration.setAdditionalConfigurations(this.additionalConfigurations);
        this.identityConfiguration.setPasswordConfiguration(this.passwordConfiguration);
        this.identityConfiguration.setPermissionConfiguration(this.permissionConfiguration);
    }

    private void givenNewIdentity(IdentityDTO identity) {
        this.identity = identity;
    }

    private void givenExistingIdentity(IdentityDTO identity) {
        try {
            identityService.createIdentity(identity.getName());
        } catch (KuraException e) {
            e.printStackTrace();
            fail("unable to create the identity");
        }
    }

    private void givenMockIdentityConfigurationExtension(final String pid) {
        this.extensions.put(pid, new MockExtensionHolder(pid));
    }

    private void givenIdentityConfigurationRequestDTO() {
        this.identityConfigurationRequestDTO = new IdentityConfigurationRequestDTO();
        this.identityConfigurationRequestDTO.setIdentity(new IdentityDTO(testUsername));
        this.identityConfigurationRequestDTO.setConfigurationComponents(new HashSet<String>(
                Arrays.asList("AdditionalConfigurations", "AssignedPermissions", "PasswordConfiguration")));
    }

    private void givenPasswordStrenghtServiceMockConfiguration(int minimum, boolean digits, boolean special, boolean both) {
        this.http.identityFixture().passwordStrength.updated(Map.of("new.password.min.length", minimum,
                "new.password.require.digits", digits, "new.password.require.special.characters", special,
                "new.password.require.both.cases", both));
    }

    private void givenAssignedPermissionToIdentity() {
        try {
            Set<Permission> permissions = new HashSet<>(Arrays.asList(new Permission(this.testPermissionName)));
            identityService.updateIdentityConfiguration(
                    new IdentityConfiguration(this.testUsername, Arrays.asList(new AssignedPermissions(permissions))));
        } catch (Exception ex) {
            ex.printStackTrace();
            fail("Unable to configure identity permissions");
        }
    }

    private class MockExtensionHolder {
        private final IdentityConfigurationExtension extension = mock(IdentityConfigurationExtension.class);
        private final Map<String, ComponentConfiguration> configurations = new HashMap<>();
        MockExtensionHolder(String pid) {
            try {
                when(this.extension.getConfiguration(anyString())).thenAnswer(call -> Optional.ofNullable(this.configurations.get(call.getArgument(0))));
                when(this.extension.getDefaultConfiguration(anyString())).thenReturn(Optional.empty());
                doAnswer(call -> { this.configurations.put(call.getArgument(0), call.getArgument(1)); return null; })
                        .when(this.extension).updateConfiguration(anyString(), any());
            } catch (KuraException e) { throw new IllegalStateException(e); }
            identityService.setIdentityConfigurationExtension(this.extension, Map.of("kura.service.pid", pid));
        }
    }

    private static class TestComponentConfiguration implements ComponentConfiguration {

        private final String pid;
        private final OCD ocd;
        private final Map<String, Object> properties;

        public TestComponentConfiguration(String pid, OCD ocd, Map<String, Object> properties) {
            this.pid = pid;
            this.ocd = ocd;
            this.properties = properties;
        }

        @Override
        public String getPid() {
            return this.pid;
        }

        @Override
        public OCD getDefinition() {
            return this.ocd;
        }

        @Override
        public OCD getLocalizedDefinition(String locale) { return this.ocd; }

        @Override
        public Map<String, Object> getConfigurationProperties() {
            return this.properties;
        }

        @Override
        public int hashCode() {
            return Objects.hash(this.ocd, this.pid, this.properties);
        }

        static TestComponentConfiguration forPid(final String pid) {
            return new TestComponentConfiguration(pid, null, Collections.singletonMap("foo", "bar"));
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) {
                return true;
            }
            if (obj == null || getClass() != obj.getClass()) {
                return false;
            }
            TestComponentConfiguration other = (TestComponentConfiguration) obj;
            return Objects.equals(this.ocd, other.ocd) && Objects.equals(this.pid, other.pid)
                    && Objects.equals(this.properties, other.properties);
        }

        @Override
        public String toString() {
            return "TestComponentConfiguration [pid=" + this.pid + ", ocd=" + this.ocd + ", properties="
                    + this.properties + "]";
        }

    }

}
