/*******************************************************************************
 * Copyright (c) 2024, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 * Content with portions generated by generative AI platform
 *******************************************************************************/
package org.eclipse.kura.endpoint;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import java.io.IOException;
import java.util.*;
import jakarta.ws.rs.core.Response.Status;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.core.testutil.requesthandler.TransportType;
import org.eclipse.kura.core.testutil.requesthandler.Transport.MethodSpec;
import org.eclipse.kura.internal.rest.security.provider.SecurityRestServiceV2;
import org.eclipse.kura.security.SecurityService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;

class SecurityEndpointsV2IT extends EndpointTestBase {
    private static final String MQTT_APP_ID = "SEC-V2";
    private static final String REST_APP_ID = "security/v2";
    private static final String METHOD_SPEC_GET = "GET";
    private static final String METHOD_SPEC_POST = "POST";
    private static final String ADMIN_ADMIN = "endpoint.admin:Endpoint-Admin-1!";
    private static final String DEBUG_ENABLED = "/debug-enabled";
    private static final String EXPECTED_DEBUG_ENABLE_TRUE_RESPONSE = "{\"enabled\":true}";
    private static final String SECURITY_POLICY_APPLY_DEFAULT_PRODUCTION = "/security-policy/apply-default-production";
    private static final String SECURITY_POLICY_APPLY = "/security-policy/apply";
    private SecurityService securityServiceMock;
    private SecurityRestServiceV2 endpoint;
    private boolean debugEnabled;
    private String securityPolicy;

    @BeforeEach
    void registerEndpoint() {
        this.debugEnabled = false;
        this.securityPolicy = null;
        this.securityServiceMock = mock(SecurityService.class);
        this.endpoint = new SecurityRestServiceV2();
        this.endpoint.bindSecurityService(this.securityServiceMock);
        this.endpoint.bindRequestHandlerRegistry(this.cloud);
        this.http.resource(this.endpoint);
    }

    @AfterEach
    void unregisterEndpoint() {
        if (this.endpoint != null) { this.endpoint.unbindRequestHandlerRegistry(this.cloud); }
    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    public void shouldCopyDefaultSecurityPolicy(TransportType type) throws KuraException {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);
        givenSecurityService();
        givenRestBasicCredentials(ADMIN_ADMIN);

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_POST), SECURITY_POLICY_APPLY_DEFAULT_PRODUCTION);

        thenRequestSucceeds();
        thenResponseBodyIsEmpty();
        thenApplyDefaultProductionSecurityPolicyIsCalled();
    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    public void shouldReloadFingerprintsWhenDefaultSecurityPolicyIsApplied(TransportType type) throws IOException, KuraException {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);
        givenSecurityService();
        givenRestBasicCredentials(ADMIN_ADMIN);

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_POST), SECURITY_POLICY_APPLY_DEFAULT_PRODUCTION);

        thenRequestSucceeds();
        thenResponseBodyIsEmpty();
        thenFingerprintsAreReloaded();
    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    public void shouldRethrowWebApplicationExceptionOnApplyDefaultProductionSecurityPolicy(TransportType type) throws KuraException {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);
        givenFailingSecurityService();
        givenRestBasicCredentials(ADMIN_ADMIN);

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_POST), SECURITY_POLICY_APPLY_DEFAULT_PRODUCTION);

        thenResponseCodeIs(Status.INTERNAL_SERVER_ERROR.getStatusCode());
    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    public void shouldRethrowWebApplicationExceptionOnApplyNullSecurityPolicy(TransportType type) throws KuraException {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);
        givenSecurityService();
        givenRestBasicCredentials(ADMIN_ADMIN);

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_POST), SECURITY_POLICY_APPLY, null);

        thenResponseCodeIs(Status.BAD_REQUEST.getStatusCode());
        thenResponseBodyEqualsJson("{\"message\":\"Security Policy cannot be null or empty\"}");
        verifyNoInteractions(this.securityServiceMock);
    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    public void shouldRethrowWebApplicationExceptionOnApplyEmptySecurityPolicy(TransportType type) throws KuraException {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);
        givenSecurityService();
        givenRestBasicCredentials(ADMIN_ADMIN);

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_POST), SECURITY_POLICY_APPLY, "");

        thenResponseCodeIs(Status.BAD_REQUEST.getStatusCode());
        thenResponseBodyEqualsJson("{\"message\":\"Security Policy cannot be null or empty\"}");
        verifyNoInteractions(this.securityServiceMock);
    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    public void shouldRethrowWebApplicationExceptionOnApplyTooBigSecurityPolicy(TransportType type) throws KuraException {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);
        // the server rejects the request before reading the whole body; on Windows the client socket
        // gets aborted instead of receiving the 400 response
        Assumptions.assumeFalse(System.getProperty("os.name").toLowerCase().startsWith("windows"));
        givenSecurityService();
        givenRestBasicCredentials(ADMIN_ADMIN);
        givenTooLargeSecurityPolicy();

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_POST), SECURITY_POLICY_APPLY, securityPolicy);

        thenResponseCodeIs(Status.BAD_REQUEST.getStatusCode());
        thenResponseBodyEqualsJson("{\"message\":\"Security policy too large\"}");
        verifyNoInteractions(this.securityServiceMock);
    }

    @ParameterizedTest
    @EnumSource(TransportType.class)
    public void shouldApplySecurityPolicy(TransportType type) throws KuraException {
        useTransport(type, MQTT_APP_ID, REST_APP_ID);
        givenSecurityService();
        givenRestBasicCredentials(ADMIN_ADMIN);

        whenRequestIsPerformed(new MethodSpec(METHOD_SPEC_POST), SECURITY_POLICY_APPLY,
                "This is a very cool security policy!");

        thenRequestSucceeds();
        thenResponseBodyIsEmpty();
        thenApplySecurityPolicyIsCalled("This is a very cool security policy!");
    }

    private void givenSecurityService() {
        reset(securityServiceMock);
    }

    private void givenFailingSecurityService() throws KuraException {
        reset(securityServiceMock);

        doThrow(RuntimeException.class).when(securityServiceMock).applyDefaultProductionSecurityPolicy();
        doThrow(RuntimeException.class).when(securityServiceMock).reloadCommandLineFingerprint();
        doThrow(RuntimeException.class).when(securityServiceMock).reloadSecurityPolicyFingerprint();
    }

    private void givenRestBasicCredentials(String value) { givenBasicCredentials(Optional.of(value)); }
    private void givenNoRestBasicCredentials() { givenBasicCredentials(Optional.empty()); }

    private void givenIdentity(String username, Optional<String> password, List<String> roles, boolean changeRequired) {
        assertDoesNotThrow(() -> {
            this.http.identityFixture().create(username, password.orElseThrow(), roles);
            if (changeRequired) { this.http.identityFixture().requirePasswordChange(username); }
        });
    }

    @Override
    protected void configureBrokerProperties(Properties properties) {
        // Original upstream request is 3.6 MB before JSON/base64 encoding; endpoint limit remains 1 MiB.
        properties.setProperty("netty.mqtt.message_size", Integer.toString(8 * 1024 * 1024));
    }

    private void givenTooLargeSecurityPolicy() {
        this.securityPolicy = "This is a very large security policy!".repeat(100000);
    }

    private void thenApplyDefaultProductionSecurityPolicyIsCalled() throws KuraException {
        verify(this.securityServiceMock).applyDefaultProductionSecurityPolicy();
    }

    private void thenFingerprintsAreReloaded() throws KuraException {
        verify(this.securityServiceMock).reloadSecurityPolicyFingerprint();
        verify(this.securityServiceMock).reloadCommandLineFingerprint();
    }

    private void thenApplySecurityPolicyIsCalled(String policy) throws KuraException {
        verify(this.securityServiceMock).applySecurityPolicy(policy);
        thenFingerprintsAreReloaded();
    }
}
