/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.common;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.atLeastOnce;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;

import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

import org.eclipse.kura.KuraAuthenticationFailedException;
import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.issuer.JwtIssuingService;
import org.eclipse.kura.core.token.jwt.verifier.JwtVerificationService;
import org.eclipse.kura.security.keystore.KeystoreService;
import org.eclipse.kura.security.token.TokenIssueRequest;
import org.eclipse.kura.security.token.TokenVerifyRequest;
import org.eclipse.kura.security.token.VerificationProof;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;

public abstract class AbstractJwtScenario {

    protected static final String TEST_IDENTITY = "test.user";
    protected static final String SIGNING_ALIAS = "jwt-signing-key";
    protected static final String DEFAULT_ISSUER = "kura";

    private KeystoreFixture keystore = new KeystoreFixture();

    private final JwtIssuingService issuingService = new JwtIssuingService();
    private final JwtVerificationService verificationService = new JwtVerificationService();

    private String issuedToken;
    private TokenInspector issuedTokenInspector;
    private Instant issuedNoEarlierThan;
    private Instant issuedNoLaterThan;
    private Exception issuingFailure;

    private VerificationProof proof;
    private Exception verificationFailure;

    protected KeystoreFixture keystore() {
        return this.keystore;
    }

    protected String issuedToken() {
        return this.issuedToken;
    }

    protected TokenInspector issuedTokenInspector() {
        return this.issuedTokenInspector;
    }

    protected Exception issuingFailure() {
        return this.issuingFailure;
    }

    protected VerificationProof proof() {
        return this.proof;
    }

    protected void givenKeystorePrivateKeyEntry(final String alias, final int keyIndex) throws TestCAException {
        this.keystore.withPrivateKeyEntry(alias, TestKeys.rsa(keyIndex));
    }

    protected void givenKeystorePrivateKeyEntryWithNonRsaKey(final String alias) throws TestCAException {
        this.keystore.withNonRsaPrivateKeyEntry(alias);
    }

    protected void givenKeystoreTrustedCertificate(final String alias, final int keyIndex) throws TestCAException {
        this.keystore.withTrustedCertificate(alias, TestKeys.rsa(keyIndex));
    }

    protected void givenKeystoreTrustedCertificate(final String alias, final int keyIndex, final Instant validFrom,
            final Instant validTo) throws TestCAException {

        this.keystore.withTrustedCertificate(alias, TestKeys.rsa(keyIndex), validFrom, validTo);
    }

    protected void givenKeystoreTrustedCertificateForNonRsaKey(final String alias) throws TestCAException {
        this.keystore.withTrustedCertificate(alias, TestKeys.certificate(alias, TestKeys.ecdsa()));
    }

    protected void givenKeystoreSecretKeyEntry(final String alias) {
        this.keystore.withSecretKeyEntry(alias);
    }

    protected void givenKeystoreWithoutEntry(final String alias) {
        this.keystore.withoutEntry(alias);
    }

    protected void givenAKeystoreThatAlwaysFails() {
        this.keystore = KeystoreFixture.alwaysFailing();
    }

    protected void givenTheIssuerIsBoundToTheKeystore() {
        this.issuingService.setKeystoreService(this.keystore.service(), this.keystore.serviceProperties());
    }

    protected void givenTheVerifierIsBoundToTheKeystore() {
        this.verificationService.setKeystoreService(this.keystore.service(), this.keystore.serviceProperties());
    }

    protected void givenTheIssuerIsActivatedWith(final IssuingConfig config) {
        this.issuingService.activate(org.mockito.Mockito.mock(org.osgi.service.component.ComponentContext.class), config.toProperties());
    }

    protected void givenTheVerifierIsActivatedWith(final VerificationConfig config) {
        this.verificationService.activate(org.mockito.Mockito.mock(org.osgi.service.component.ComponentContext.class), config.toProperties());
    }

    protected void givenTheServicesWereDeactivated() {
        whenTheServicesAreDeactivated();
    }

    protected void givenTheIssuerReportsMaximumLifetime(final Duration expected) {
        thenTheIssuerReportsMaximumLifetime(expected);
    }

    protected void givenIssuingIsNotAvailableYet() {
        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenNoTokenIsIssued();
        thenIssuingFailedWith(KuraErrorCode.CONFIGURATION_ERROR);

        resetIssuingOutcome();
    }

    protected void givenVerificationIsNotAvailableYetFor(final String token) {
        whenATokenIsVerified(token);

        thenNoVerificationProofIsProduced();
        thenVerificationFailedWith(KuraErrorCode.CONFIGURATION_ERROR);

        resetVerificationOutcome();
    }

    protected void givenTheBoundKeystoreAnnouncedAChange() {
        whenTheBoundKeystoreAnnouncesAChange();
    }

    protected void givenAForeignKeystoreAnnouncedAChange() {
        whenAForeignKeystoreAnnouncesAChange();
    }

    protected void givenTheBoundKeystoreWasUnbound() {
        whenTheBoundKeystoreIsUnbound();
    }

    protected void givenADifferentKeystoreInstanceWasUnbound() {
        whenADifferentKeystoreInstanceIsUnbound();
    }

    protected void givenTheIssuerWasReconfiguredWith(final IssuingConfig config) {
        whenTheIssuerIsReconfiguredWith(config);
    }

    protected void givenTheVerifierWasReconfiguredWith(final VerificationConfig config) {
        whenTheVerifierIsReconfiguredWith(config);
    }

    protected void whenATokenIsIssuedFor(final String identityName) {
        whenATokenIsIssued(TokenIssueRequest.builder(identityName).build());
    }

    protected void whenATokenIsIssued(final TokenIssueRequest request) {
        resetIssuingOutcome();

        this.issuedNoEarlierThan = Instant.now();

        try {
            this.issuedToken = this.issuingService.issue(request);
            this.issuedTokenInspector = TokenInspector.of(this.issuedToken);
        } catch (final Exception e) {
            this.issuingFailure = e;
        }

        this.issuedNoLaterThan = Instant.now();
    }

    protected void whenATokenIsVerified(final String token) {
        whenTheRequestIsVerified(TokenVerifyRequest.builder(token).build());
    }

    protected void whenATokenIsVerifiedFor(final String token, final String intendedConsumer) {
        whenTheRequestIsVerified(TokenVerifyRequest.builder(token).intendedConsumer(intendedConsumer).build());
    }

    protected void whenTheIssuedTokenIsVerified() {
        assertNotNull(this.issuedToken, "no token has been issued, nothing to verify");

        whenATokenIsVerified(this.issuedToken);
    }

    protected void whenTheIssuerIsReconfiguredWith(final IssuingConfig config) {
        this.issuingService.updated(config.toProperties());
    }

    protected void whenTheVerifierIsReconfiguredWith(final VerificationConfig config) {
        this.verificationService.updated(config.toProperties());
    }

    protected void whenTheBoundKeystoreAnnouncesAChange() {
        this.keystore.forgetRecordedInteractions();

        this.issuingService.handleEvent(this.keystore.changedEvent());
        this.verificationService.handleEvent(this.keystore.changedEvent());
    }

    protected void whenAForeignKeystoreAnnouncesAChange() {
        this.keystore.forgetRecordedInteractions();

        this.issuingService.handleEvent(KeystoreFixture.changedEventFrom(KeystoreFixture.FOREIGN_PID));
        this.verificationService.handleEvent(KeystoreFixture.changedEventFrom(KeystoreFixture.FOREIGN_PID));
    }

    protected void whenAKeystoreChangeWithoutSenderPidIsDelivered() {
        this.keystore.forgetRecordedInteractions();

        this.issuingService.handleEvent(KeystoreFixture.changedEventWithoutSenderPid());
        this.verificationService.handleEvent(KeystoreFixture.changedEventWithoutSenderPid());
    }

    protected void whenAnUnrelatedEventOnTheKeystoreTopicIsDelivered() {
        this.keystore.forgetRecordedInteractions();

        this.issuingService.handleEvent(KeystoreFixture.unrelatedEventOnTheKeystoreTopic());
        this.verificationService.handleEvent(KeystoreFixture.unrelatedEventOnTheKeystoreTopic());
    }

    protected void whenTheServicesAreDeactivated() {
        this.keystore.forgetRecordedInteractions();

        this.issuingService.deactivate();
        this.verificationService.deactivate();
    }

    protected void whenTheKeystoreIsBoundAgain() {
        this.keystore.forgetRecordedInteractions();

        givenTheIssuerIsBoundToTheKeystore();
        givenTheVerifierIsBoundToTheKeystore();
    }

    protected void whenTheBoundKeystoreIsUnbound() {
        this.issuingService.unsetKeystoreService(this.keystore.service());
        this.verificationService.unsetKeystoreService(this.keystore.service());
    }

    protected void whenADifferentKeystoreInstanceIsUnbound() {
        final KeystoreService anotherKeystore = new KeystoreFixture(KeystoreFixture.FOREIGN_PID).service();

        this.issuingService.unsetKeystoreService(anotherKeystore);
        this.verificationService.unsetKeystoreService(anotherKeystore);
    }

    protected void thenATokenIsIssued() {
        assertNull(this.issuingFailure, "issuing failed unexpectedly");
        assertNotNull(this.issuedToken, "expected a token to be issued");
    }

    protected void thenNoTokenIsIssued() {
        assertNull(this.issuedToken, "expected no token to be issued");
    }

    protected void thenIssuingFailedWith(final KuraErrorCode expectedErrorCode) {
        assertNotNull(this.issuingFailure, "expected issuing to fail");
        assertTrue(this.issuingFailure instanceof KuraException, "expected a KuraException but got " + this.issuingFailure.getClass().getName());
        assertEquals(expectedErrorCode, ((KuraException) this.issuingFailure).getCode());
    }

    protected void thenIssuingFailedWithBadRequestMentioning(final String expectedFragment) {
        thenIssuingFailedWith(KuraErrorCode.BAD_REQUEST);
        assertTrue(this.issuingFailure.getMessage().contains(expectedFragment), "failure message '" + this.issuingFailure.getMessage() + "' does not mention " + expectedFragment);
    }

    protected void thenIssuedTokenHeaderHas(final String name, final String expectedValue) {
        final JsonElement entry = requireHeaderEntry(name);

        assertEquals(expectedValue, entry.getAsString());
    }

    protected void thenIssuedTokenHasNoClaim(final String name) {
        thenATokenIsIssued();
        assertFalse(this.issuedTokenInspector.claim(name).isPresent(), "claim '" + name + "' should not be present in " + this.issuedTokenInspector.payload());
    }

    protected void thenIssuedTokenHasStringClaim(final String name, final String expectedValue) {
        final JsonElement claim = requireClaim(name);

        assertTrue(isPrimitiveString(claim), "claim '" + name + "' is not a JSON string but " + claim);
        assertEquals(expectedValue, claim.getAsString());
    }

    protected void thenIssuedTokenHasBooleanClaim(final String name, final boolean expectedValue) {
        final JsonElement claim = requireClaim(name);

        assertTrue(claim.isJsonPrimitive() && claim.getAsJsonPrimitive().isBoolean(), "claim '" + name + "' is not a JSON boolean but " + claim);
        assertEquals(expectedValue, claim.getAsBoolean());
    }

    protected void thenIssuedTokenHasIntegralClaim(final String name, final long expectedValue) {
        final JsonElement claim = requireClaim(name);

        assertTrue(isPrimitiveNumber(claim), "claim '" + name + "' is not a JSON number but " + claim);
        assertEquals(expectedValue, claim.getAsLong());
    }

    protected void thenIssuedTokenHasDecimalClaim(final String name, final double expectedValue, final double delta) {
        final JsonElement claim = requireClaim(name);

        assertTrue(isPrimitiveNumber(claim), "claim '" + name + "' is not a JSON number but " + claim);
        assertEquals(expectedValue, claim.getAsDouble(), delta);
    }

    protected void thenIssuedTokenHasNullClaim(final String name) {
        final JsonElement claim = requireClaim(name);

        assertTrue(claim.isJsonNull(), "claim '" + name + "' is not a JSON null but " + claim);
    }

    protected void thenIssuedTokenHasStringArrayClaim(final String name, final List<String> expectedValues) {
        final JsonElement claim = requireClaim(name);

        assertTrue(claim.isJsonArray(), "claim '" + name + "' is not a JSON array but " + claim);

        final List<String> actualValues = new ArrayList<>();
        claim.getAsJsonArray().forEach(element -> actualValues.add(element.getAsString()));

        assertEquals(expectedValues, actualValues);
    }

    protected void thenIssuedTokenHasObjectClaimWithEntry(final String name, final String key,
            final String expectedValue) {

        final JsonElement claim = requireClaim(name);

        assertTrue(claim.isJsonObject(), "claim '" + name + "' is not a JSON object but " + claim);

        final JsonObject object = claim.getAsJsonObject();

        assertTrue(object.has(key), "claim '" + name + "' has no entry '" + key + "' in " + object);
        assertEquals(expectedValue, object.get(key).getAsString());
    }

    protected void thenIssuedTokenClaimIsAUniversallyUniqueIdentifier(final String name) {
        final JsonElement claim = requireClaim(name);

        assertTrue(isPrimitiveString(claim), "claim '" + name + "' is not a JSON string but " + claim);
        assertEquals(claim.getAsString(), UUID.fromString(claim.getAsString()).toString());
    }

    protected void thenIssuedTokenExpiresAt(final Instant expectedExpiration) {
        final JsonElement claim = requireClaim("exp");

        assertEquals(expectedExpiration.getEpochSecond(), claim.getAsLong());
    }

    protected void thenIssuedTokenExpiresAtIssueTimePlus(final Duration expectedLifetime) {
        final JsonElement claim = requireClaim("exp");

        final long earliest = this.issuedNoEarlierThan.plus(expectedLifetime).getEpochSecond();
        final long latest = this.issuedNoLaterThan.plus(expectedLifetime).getEpochSecond();
        final long actual = claim.getAsLong();

        assertTrue(actual >= earliest && actual <= latest, "exp is " + actual + " but was expected between " + earliest + " and " + latest);
    }

    protected void thenIssuedTokenIsNotBeforeAt(final Instant expectedNotBefore) {
        final JsonElement claim = requireClaim("nbf");

        assertEquals(expectedNotBefore.getEpochSecond(), claim.getAsLong());
    }

    protected void thenTheTokenIsVerifiedFor(final String expectedIdentityName) {
        assertNull(this.verificationFailure, "verification failed unexpectedly");
        assertNotNull(this.proof, "expected a verification proof");
        assertEquals(expectedIdentityName, this.proof.getIdentityName());
    }

    protected void thenNoVerificationProofIsProduced() {
        assertNull(this.proof, "expected no verification proof");
    }

    protected void thenVerificationFailedAsAuthenticationFailure() {
        assertNotNull(this.verificationFailure, "expected verification to fail");
        assertTrue(this.verificationFailure instanceof KuraAuthenticationFailedException, "expected a KuraAuthenticationFailedException but got "
                + this.verificationFailure.getClass().getName());
    }

    protected void thenVerificationFailedBecauseOf(final Class<? extends Throwable> expectedCauseClass) {
        thenVerificationFailedAsAuthenticationFailure();

        final Throwable cause = this.verificationFailure.getCause();

        assertNotNull(cause, "expected the failure to carry a cause");
        assertTrue(expectedCauseClass.isInstance(cause), "expected a cause of type " + expectedCauseClass.getName() + " but got " + cause.getClass().getName());
    }

    protected void thenVerificationFailedWithoutAnUnderlyingCause() {
        thenVerificationFailedAsAuthenticationFailure();

        assertNull(this.verificationFailure.getCause(), "expected the failure to carry no cause");
    }

    protected void thenVerificationFailedWith(final KuraErrorCode expectedErrorCode) {
        assertNotNull(this.verificationFailure, "expected verification to fail");
        assertTrue(this.verificationFailure instanceof KuraException, "expected a KuraException but got " + this.verificationFailure.getClass().getName());
        assertEquals(expectedErrorCode, ((KuraException) this.verificationFailure).getCode());
    }

    protected void thenTheProofHasStringClaim(final String name, final String expectedValue) {
        assertNotNull(this.proof, "expected a verification proof");
        assertTrue(this.proof.getClaims().containsKey(name), "proof has no claim '" + name + "' in " + this.proof.getClaims());
        assertEquals(expectedValue, this.proof.getClaims().get(name));
    }

    protected void thenTheProofHasNullClaim(final String name) {
        assertNotNull(this.proof, "expected a verification proof");
        assertTrue(this.proof.getClaims().containsKey(name), "proof has no claim '" + name + "' in " + this.proof.getClaims());
        assertNull(this.proof.getClaims().get(name), "claim '" + name + "' should be null");
    }

    protected void thenTheProofClaimsCannotBeModified() {
        assertNotNull(this.proof, "expected a verification proof");

        final Map<String, Object> claims = this.proof.getClaims();

        assertThrows(UnsupportedOperationException.class, () -> claims.put("injected", "value"));
    }

    protected void thenTheProofRecordsAVerificationTime() {
        assertNotNull(this.proof, "expected a verification proof");
        assertNotNull(this.proof.getVerifiedAt(), "expected the proof to record when verification happened");
    }

    protected void thenTheProofExposesExpiresAt(final Instant expected) {
        assertNotNull(this.proof, "expected a verification proof");
        assertTrue(this.proof.getExpiresAt().isPresent(), "expected the proof to expose exp");
        assertEquals(expected.getEpochSecond(), this.proof.getExpiresAt().get().getEpochSecond());
    }

    protected void thenTheProofExposesNoExpiresAt() {
        assertNotNull(this.proof, "expected a verification proof");
        assertFalse(this.proof.getExpiresAt().isPresent(), "expected the proof to expose no exp");
    }

    protected void thenTheProofExposesNotBefore(final Instant expected) {
        assertNotNull(this.proof, "expected a verification proof");
        assertTrue(this.proof.getNotBefore().isPresent(), "expected the proof to expose nbf");
        assertEquals(expected.getEpochSecond(), this.proof.getNotBefore().get().getEpochSecond());
    }

    protected void thenTheProofExposesNoNotBefore() {
        assertNotNull(this.proof, "expected a verification proof");
        assertFalse(this.proof.getNotBefore().isPresent(), "expected the proof to expose no nbf");
    }

    protected void thenTheProofExposesIssuedAt(final Instant expected) {
        assertNotNull(this.proof, "expected a verification proof");
        assertTrue(this.proof.getIssuedAt().isPresent(), "expected the proof to expose iat");
        assertEquals(expected.getEpochSecond(), this.proof.getIssuedAt().get().getEpochSecond());
    }

    protected void thenTheProofExposesNoIssuedAt() {
        assertNotNull(this.proof, "expected a verification proof");
        assertFalse(this.proof.getIssuedAt().isPresent(), "expected the proof to expose no iat");
    }

    protected void thenTheProofExposesTokenId(final String expected) {
        assertNotNull(this.proof, "expected a verification proof");
        assertTrue(this.proof.getTokenID().isPresent(), "expected the proof to expose jti");
        assertEquals(expected, this.proof.getTokenID().get());
    }

    protected void thenTheProofExposesNoTokenId() {
        assertNotNull(this.proof, "expected a verification proof");
        assertFalse(this.proof.getTokenID().isPresent(), "expected the proof to expose no jti");
    }

    protected void thenTheIssuerReportsMaximumLifetime(final Duration expected) {
        final Optional<Duration> actual = this.issuingService.getMaximumLifetime();

        assertTrue(actual.isPresent(), "expected the issuer to report a maximum lifetime");
        assertEquals(expected, actual.get());
    }

    protected void thenTheIssuerReportsNoMaximumLifetime() {
        final Optional<Duration> actual = this.issuingService.getMaximumLifetime();

        assertFalse(actual.isPresent(), "expected the issuer to report no maximum lifetime but got " + actual);
    }

    protected void thenTheKeystoreWasConsultedAgain() throws KuraException {
        verify(this.keystore.service(), atLeastOnce()).getEntry(anyString());
        verify(this.keystore.service(), atLeastOnce()).getEntries();
    }

    protected void thenTheKeystoreWasNotConsultedAgain() throws KuraException {
        verify(this.keystore.service(), never()).getEntries();
        verify(this.keystore.service(), never()).getEntry(anyString());
    }

    private void whenTheRequestIsVerified(final TokenVerifyRequest request) {
        resetVerificationOutcome();

        try {
            this.proof = this.verificationService.verify(request);
        } catch (final Exception e) {
            this.verificationFailure = e;
        }
    }

    private void resetIssuingOutcome() {
        this.issuedToken = null;
        this.issuedTokenInspector = null;
        this.issuingFailure = null;
    }

    private void resetVerificationOutcome() {
        this.proof = null;
        this.verificationFailure = null;
    }

    private JsonElement requireClaim(final String name) {
        thenATokenIsIssued();

        return this.issuedTokenInspector.claim(name)
                .orElseThrow(() -> new AssertionError("claim '" + name + "' not found in "
                        + this.issuedTokenInspector.payload()));
    }

    private JsonElement requireHeaderEntry(final String name) {
        thenATokenIsIssued();

        return this.issuedTokenInspector.headerEntry(name)
                .orElseThrow(() -> new AssertionError("header entry '" + name + "' not found in "
                        + this.issuedTokenInspector.header()));
    }

    private static boolean isPrimitiveString(final JsonElement element) {
        return element.isJsonPrimitive() && element.getAsJsonPrimitive().isString();
    }

    private static boolean isPrimitiveNumber(final JsonElement element) {
        return element.isJsonPrimitive() && element.getAsJsonPrimitive().isNumber();
    }

}
