/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.common;

import java.util.LinkedHashMap;
import java.util.Map;


public final class IssuingConfig {

    private String keystoreTargetFilter = "(kura.service.pid=changeme)";
    private String signingKeyAlias = "jwt-signing-key";
    private String issuer = "kura";
    private int maximumLifetimeSeconds = 3600;

    private IssuingConfig() {
    }

    public static IssuingConfig defaults() {
        return new IssuingConfig();
    }

    public IssuingConfig withKeystoreTargetFilter(final String keystoreTargetFilter) {
        this.keystoreTargetFilter = keystoreTargetFilter;
        return this;
    }

    public IssuingConfig withSigningKeyAlias(final String signingKeyAlias) {
        this.signingKeyAlias = signingKeyAlias;
        return this;
    }

    public IssuingConfig withIssuer(final String issuer) {
        this.issuer = issuer;
        return this;
    }

    public IssuingConfig withMaximumLifetimeSeconds(final int maximumLifetimeSeconds) {
        this.maximumLifetimeSeconds = maximumLifetimeSeconds;
        return this;
    }

    /** Matches the hand-written metatype property IDs used by this fork. */
    public Map<String, Object> toProperties() {
        final Map<String, Object> properties = new LinkedHashMap<>();
        properties.put("KeystoreService_target", this.keystoreTargetFilter);
        properties.put("signing.key.alias", this.signingKeyAlias);
        properties.put("issuer", this.issuer);
        properties.put("maximum.lifetime.seconds", this.maximumLifetimeSeconds);
        return properties;
    }

}
