/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.common;

import java.util.LinkedHashMap;
import java.util.Map;


public final class VerificationConfig {

    private String keystoreTargetFilter = "(kura.service.pid=changeme)";
    private String trustedIssuers = "";
    private String verificationKeyAliases = "";
    private int clockSkewSeconds = 30;
    private boolean requireValidCertificate = true;

    private VerificationConfig() {
    }

    public static VerificationConfig defaults() {
        return new VerificationConfig();
    }

    public VerificationConfig withKeystoreTargetFilter(final String keystoreTargetFilter) {
        this.keystoreTargetFilter = keystoreTargetFilter;
        return this;
    }

    public VerificationConfig withTrustedIssuers(final String trustedIssuers) {
        this.trustedIssuers = trustedIssuers;
        return this;
    }

    public VerificationConfig withVerificationKeyAliases(final String verificationKeyAliases) {
        this.verificationKeyAliases = verificationKeyAliases;
        return this;
    }

    public VerificationConfig withClockSkewSeconds(final int clockSkewSeconds) {
        this.clockSkewSeconds = clockSkewSeconds;
        return this;
    }

    public VerificationConfig withRequireValidCertificate(final boolean requireValidCertificate) {
        this.requireValidCertificate = requireValidCertificate;
        return this;
    }

    /** Matches the hand-written metatype property IDs used by this fork. */
    public Map<String, Object> toProperties() {
        final Map<String, Object> properties = new LinkedHashMap<>();
        properties.put("KeystoreService_target", this.keystoreTargetFilter);
        properties.put("trusted.issuers", this.trustedIssuers);
        properties.put("verification.key.aliases", this.verificationKeyAliases);
        properties.put("clock.skew.seconds", this.clockSkewSeconds);
        properties.put("require.valid.certificate", this.requireValidCertificate);
        return properties;
    }

}
