/*******************************************************************************
 * Copyright (c) 2024, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.core.identity.test;

import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.HashMap;
import java.util.HexFormat;
import java.util.Map;

import org.apache.felix.useradmin.RoleFactory;
import org.apache.felix.useradmin.RoleRepositoryStore;
import org.apache.felix.useradmin.impl.EventDispatcher;
import org.apache.felix.useradmin.impl.RoleRepository;
import org.apache.felix.useradmin.impl.UserAdminImpl;
import org.eclipse.kura.core.identity.IdentityServiceImpl;
import org.eclipse.kura.core.identity.PasswordStrengthVerificationServiceImpl;
import org.eclipse.kura.crypto.CryptoService;
import org.osgi.framework.Bundle;
import org.osgi.framework.Filter;
import org.osgi.framework.FrameworkUtil;
import org.osgi.framework.ServiceReference;
import org.osgi.framework.ServiceRegistration;
import org.osgi.service.useradmin.Role;
import org.osgi.service.useradmin.UserAdmin;

abstract class IdentityServiceTestBase {
    protected final UserAdmin userAdmin;
    protected final CryptoService cryptoService = mock(CryptoService.class);
    protected final IdentityServiceImpl identityService = new IdentityServiceImpl();
    private final PasswordStrengthVerificationServiceImpl passwordStrength = new PasswordStrengthVerificationServiceImpl();

    @SuppressWarnings({ "rawtypes", "unchecked" })
    IdentityServiceTestBase() {
        UserAdminImpl actualUserAdmin = new UserAdminImpl(new RoleRepository(new MemoryRoles()),
                mock(EventDispatcher.class));
        ServiceRegistration registration = mock(ServiceRegistration.class);
        when(registration.getReference()).thenReturn(mock(ServiceReference.class));
        actualUserAdmin.getService(mock(Bundle.class), registration);
        this.userAdmin = actualUserAdmin;
        try {
            when(this.cryptoService.sha256Hash(anyString())).thenAnswer(invocation -> HexFormat.of().formatHex(
                    MessageDigest.getInstance("SHA-256").digest(invocation.<String>getArgument(0)
                            .getBytes(StandardCharsets.UTF_8))));
        } catch (Exception e) {
            throw new IllegalStateException(e);
        }
        this.passwordStrength.activate(Map.of("new.password.min.length", 8));
        this.identityService.setCryptoService(this.cryptoService);
        this.identityService.setUserAdmin(this.userAdmin);
        this.identityService.setPasswordStrengthVerificationService(this.passwordStrength);
        this.identityService.activate();
    }

    protected void givenPasswordStrengthVerificationOptions(Object... values) {
        Map<String, Object> options = new HashMap<>();
        for (int i = 0; i < values.length; i += 2) {
            options.put((String) values[i], values[i + 1]);
        }
        this.passwordStrength.updated(options);
    }

    // Only persistence is replaced; Felix roles, groups, membership and UserAdmin run normally.
    private static class MemoryRoles implements RoleRepositoryStore {
        private final Map<String, Role> roles = new HashMap<>();

        @Override
        public Role addRole(String name, int type) {
            if (this.roles.containsKey(name)) { return null; }
            Role role = RoleFactory.createRole(type, name);
            this.roles.put(name, role);
            return role;
        }

        @Override
        public Role getRoleByName(String name) { return this.roles.get(name); }

        @Override
        public Role removeRole(String name) { return this.roles.remove(name); }

        @Override
        public Role[] getRoles(String expression) throws Exception {
            Filter filter = expression == null ? null : FrameworkUtil.createFilter(expression);
            return this.roles.values().stream().filter(role -> filter == null || filter.match(role.getProperties()))
                    .toArray(Role[]::new);
        }
    }
}
