<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.eclipse.kura</groupId>
  <artifactId>kura-workspace</artifactId>
  <version>6.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>Kura development workspace</name>
  <modules>
    <module>build-support</module>
    <module>kura</module>
  </modules>
  <profiles>
    <profile>
      <id>dev-runtime</id>
      <modules>
        <module>kura-dev-runtime</module>
      </modules>
    </profile>
    <profile>
      <id>osgi-it</id>
      <modules>
        <module>kura-osgi-tests</module>
      </modules>
    </profile>
  </profiles>
</project>
