/*******************************************************************************
 * Copyright (c) 2017, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.clock;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicReference;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.junit.jupiter.api.Test;

class JavaNtpClockSyncProviderTest {

    private final AtomicReference<Runnable> tick = new AtomicReference<>();
    private final ScheduledExecutorService scheduler = mock(ScheduledExecutorService.class);
    private final ScheduledFuture<?> future = mock(ScheduledFuture.class);

    private void start(JavaNtpClockSyncProvider provider) throws KuraException {
        Map<String, Object> properties = new HashMap<>();
        properties.put("enabled", true);
        properties.put("clock.provider", "java-ntp");
        properties.put("clock.ntp.host", "localhost");
        properties.put("clock.ntp.port", 123);
        properties.put("clock.ntp.timeout", 100);
        properties.put("clock.ntp.retry.interval", 1);
        properties.put("clock.ntp.refresh-interval", 1);
        properties.put("clock.ntp.max-retry", 1);
        doAnswer(invocation -> {
            this.tick.set(invocation.getArgument(0));
            return this.future;
        }).when(this.scheduler).scheduleAtFixedRate(any(Runnable.class), eq(0L), eq(1L), eq(TimeUnit.SECONDS));
        provider.init(new ClockServiceConfig(properties), this.scheduler, null);
        provider.start();
        assertNotNull(this.tick.get());
    }

    @Test
    void testStartFail() throws KuraException {
        JavaNtpClockSyncProvider provider = new JavaNtpClockSyncProvider() {
            @Override protected boolean syncClock() { return false; }
        };
        start(provider);
        this.tick.get().run();
        assertTrue(provider.isSynced, "Exhausted retry attempts pause syncing until the refresh period");
        assertEquals(1, provider.numRetry);
        this.tick.get().run();
        assertEquals(1, provider.syncCount);
        assertEquals(0, provider.numRetry);
        assertFalse(provider.isSynced);
        provider.stop();
        verify(this.future).cancel(true);
    }

    @Test
    void testStart() throws KuraException {
        JavaNtpClockSyncProvider provider = new JavaNtpClockSyncProvider() {
            @Override protected boolean syncClock() { return true; }
        };
        start(provider);
        this.tick.get().run();
        assertTrue(provider.isSynced);
        assertEquals(0, provider.syncCount);
        assertEquals(0, provider.numRetry);
        provider.stop();
        verify(this.future).cancel(true);
    }

    @Test
    void testStartSynchException() throws KuraException {
        JavaNtpClockSyncProvider provider = new JavaNtpClockSyncProvider() {
            @Override protected boolean syncClock() throws KuraException {
                throw new KuraException(KuraErrorCode.CONFIGURATION_ERROR, "test");
            }
        };
        start(provider);
        this.tick.get().run();
        assertEquals(0, provider.syncCount);
        assertEquals(1, provider.numRetry);
        assertTrue(provider.isSynced);
        provider.stop();
        verify(this.future).cancel(true);
    }
}
