<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (c) 2025, 2026 Eurotech and contributors.
     SPDX-License-Identifier: EPL-2.0 -->
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>${groupId}</groupId><artifactId>${artifactId}</artifactId>
    <version>${version}</version><relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>${artifactId}.parent</artifactId><packaging>pom</packaging>
  <properties>
    <skip.artifact.signing>true</skip.artifact.signing><keystore.type>JKS</keystore.type>
  </properties>
  <build><pluginManagement><plugins><plugin>
    <groupId>org.apache.maven.plugins</groupId><artifactId>maven-jarsigner-plugin</artifactId><version>1.4</version>
    <executions><execution><id>sign</id><goals><goal>sign</goal></goals></execution></executions>
    <configuration>
      <skip>${skip.artifact.signing}</skip><storetype>${keystore.type}</storetype>
      <keystore>${addon.keystore.path}</keystore><alias>${addon.key.alias}</alias>
      <storepass>${addon.keystore.password}</storepass><keypass>${addon.key.password}</keypass>
      <arguments><argument>-tsa</argument><argument>http://timestamp.digicert.com</argument></arguments>
      <archiverConfig><compress>false</compress></archiverConfig>
    </configuration>
  </plugin></plugins></pluginManagement></build>
  <profiles><profile><id>sign-artifacts</id><properties>
    <skip.artifact.signing>false</skip.artifact.signing>
  </properties></profile></profiles>
  <modules><module>${artifactId}.bundle</module></modules>
</project>
