source.. = src/main/java/
output.. = target/classes/
bin.includes = META-INF/,\
               OSGI-INF/,\
               .,\
               about.html,\
               .gitkeep,\
               bcpkix-jdk18on.jar,\
               bcprov-jdk18on.jar,\
               bcutil-jdk18on.jar,\
               collections.jar,\
               groovy-jsr223.jar,\
               icu4j.jar,\
               jline.jar,\
               js-language.jar,\
               js-scriptengine.jar,\
               json.jar,\
               launcher-common.jar,\
               llvm-api.jar,\
               nativeimage.jar,\
               polyglot.jar,\
               profiler-tool.jar,\
               python-language.jar,\
               python-resources.jar,\
               regex.jar,\
               truffle-api.jar,\
               truffle-compiler.jar,\
               truffle-enterprise.jar,\
               truffle-nfi-libffi.jar,\
               truffle-nfi.jar,\
               truffle-runtime.jar,\
               wasm-language.jar,\
               word.jar,\
               xz.jar,\
js-language.jar,\
js-scriptengine.jar,\
truffle-runtime.jar,\
truffle-compiler.jar,\
truffle-enterprise.jar,\
polyglot.jar,\
launcher-common.jar,\
jline.jar,\
collections.jar,\
nativeimage.jar,\
word.jar,\
truffle-api.jar,\
icu4j.jar,\
groovy-jsr223.jar,\
regex.jar,\
python-language.jar,\
profiler-tool.jar,\
json.jar,\
truffle-nfi.jar,\
truffle-nfi-libffi.jar,\
llvm-api.jar,\
xz.jar,\
bcprov-jdk18on.jar,\
bcpkix-jdk18on.jar,\
bcutil-jdk18on.jar,\
python-resources.jar,\
wasm-language.jar
