bin.includes = META-INF/,\
               about.html,\
               lib/js-language.jar,\
               lib/truffle-runtime.jar,\
               lib/truffle-enterprise.jar,\
               lib/polyglot.jar,\
               lib/launcher-common.jar,\
               lib/jline.jar,\
               lib/collections.jar,\
               lib/nativeimage.jar,\
               lib/word.jar,\
               lib/truffle-api.jar,\
               lib/icu4j.jar,\
               lib/groovy-jsr223.jar,\
               lib/regex.jar,\
               lib/python-language.jar,\
               lib/profiler-tool.jar,\
               lib/json.jar,\
               lib/truffle-nfi.jar,\
               lib/truffle-nfi-libffi.jar,\
               lib/llvm-api.jar,\
               lib/xz.jar,\
               lib/bcprov-jdk18on.jar,\
               lib/bcpkix-jdk18on.jar,\
               lib/bcutil-jdk18on.jar,\
               lib/python-resources.jar,\
               lib/wasm-language.jar
