<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.eclipse.kura</groupId>
        <artifactId>kura</artifactId>
        <version>6.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>org.eclipse.kura.script.provider</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>eclipse-plugin</packaging>

    <properties>
        <graalvm.version>24.2.1</graalvm.version>
        <org.apache.groovy.version>5.0.5</org.apache.groovy.version>
        <kura.basedir>${project.basedir}/..</kura.basedir>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <configuration>
                            <outputDirectory>${project.basedir}/lib</outputDirectory>
                            <stripVersion>true</stripVersion>
                            <artifactItems>
                                <!-- GraalVM JS engine -->
                                <artifactItem>
                                    <groupId>org.graalvm.js</groupId>
                                    <artifactId>js-language</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.graalvm.truffle</groupId>
                                    <artifactId>truffle-runtime</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.graalvm.truffle</groupId>
                                    <artifactId>truffle-enterprise</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.graalvm.polyglot</groupId>
                                    <artifactId>polyglot</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.graalvm.sdk</groupId>
                                    <artifactId>launcher-common</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.graalvm.shadowed</groupId>
                                    <artifactId>jline</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.graalvm.sdk</groupId>
                                    <artifactId>collections</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.graalvm.sdk</groupId>
                                    <artifactId>nativeimage</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.graalvm.sdk</groupId>
                                    <artifactId>word</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.graalvm.truffle</groupId>
                                    <artifactId>truffle-api</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.graalvm.shadowed</groupId>
                                    <artifactId>icu4j</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.graalvm.regex</groupId>
                                    <artifactId>regex</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <!-- GraalVM Python engine -->
                                <artifactItem>
                                    <groupId>org.graalvm.python</groupId>
                                    <artifactId>python-language</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.graalvm.tools</groupId>
                                    <artifactId>profiler-tool</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.graalvm.shadowed</groupId>
                                    <artifactId>json</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.graalvm.truffle</groupId>
                                    <artifactId>truffle-nfi</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.graalvm.truffle</groupId>
                                    <artifactId>truffle-nfi-libffi</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.graalvm.llvm</groupId>
                                    <artifactId>llvm-api</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.graalvm.shadowed</groupId>
                                    <artifactId>xz</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.bouncycastle</groupId>
                                    <artifactId>bcprov-jdk18on</artifactId>
                                    <version>1.78.1</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.bouncycastle</groupId>
                                    <artifactId>bcpkix-jdk18on</artifactId>
                                    <version>1.78.1</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.bouncycastle</groupId>
                                    <artifactId>bcutil-jdk18on</artifactId>
                                    <version>1.78.1</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.graalvm.python</groupId>
                                    <artifactId>python-resources</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <!-- GraalVM Wasm engine -->
                                <artifactItem>
                                    <groupId>org.graalvm.wasm</groupId>
                                    <artifactId>wasm-language</artifactId>
                                    <version>${graalvm.version}</version>
                                </artifactItem>
                                <!-- Groovy JSR-223 -->
                                <artifactItem>
                                    <groupId>org.apache.groovy</groupId>
                                    <artifactId>groovy-jsr223</artifactId>
                                    <version>${org.apache.groovy.version}</version>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
