<?xml version="1.0" encoding="UTF-8"?>
<!-- GraalVM JS engine -->
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.kura</groupId>
    <artifactId>kura-build-parent</artifactId>
    <version>6.0.0-SNAPSHOT</version>
    <relativePath>../../build-support/kura-build-parent/pom.xml</relativePath>
  </parent>
  <artifactId>org.eclipse.kura.script.provider</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>bundle</packaging>
  <dependencies>
    <dependency>
      <groupId>org.apache.groovy</groupId>
      <artifactId>groovy-jsr223</artifactId>
      <version>5.0.5</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.apache.groovy</groupId>
      <artifactId>groovy</artifactId>
      <version>5.0.5</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcpkix-jdk18on</artifactId>
      <version>1.78.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcprov-jdk18on</artifactId>
      <version>1.78.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcutil-jdk18on</artifactId>
      <version>1.78.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.eclipse.kura</groupId>
      <artifactId>org.eclipse.kura.api</artifactId>
      <version>3.0.0-SNAPSHOT</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.js</groupId>
      <artifactId>js-language</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.js</groupId>
      <artifactId>js-scriptengine</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.llvm</groupId>
      <artifactId>llvm-api</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.polyglot</groupId>
      <artifactId>polyglot</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.python</groupId>
      <artifactId>python-language</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.python</groupId>
      <artifactId>python-resources</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.regex</groupId>
      <artifactId>regex</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.sdk</groupId>
      <artifactId>collections</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.sdk</groupId>
      <artifactId>launcher-common</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.sdk</groupId>
      <artifactId>nativeimage</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.sdk</groupId>
      <artifactId>word</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.shadowed</groupId>
      <artifactId>icu4j</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.shadowed</groupId>
      <artifactId>jline</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.shadowed</groupId>
      <artifactId>json</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.shadowed</groupId>
      <artifactId>xz</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.tools</groupId>
      <artifactId>profiler-tool</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.truffle</groupId>
      <artifactId>truffle-api</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.truffle</groupId>
      <artifactId>truffle-compiler</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.truffle</groupId>
      <artifactId>truffle-enterprise</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.truffle</groupId>
      <artifactId>truffle-nfi-libffi</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.truffle</groupId>
      <artifactId>truffle-nfi</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.truffle</groupId>
      <artifactId>truffle-runtime</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.graalvm.wasm</groupId>
      <artifactId>wasm-language</artifactId>
      <version>24.2.1</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>2.0.18</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
  </dependencies>
  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
      </resource>
      <resource>
        <directory>src/main/java</directory>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${project.basedir}</directory>
        <includes>
          <include>META-INF/**</include>
          <include>OSGI-INF/**</include>
          <include>about.html</include>
          <include>.gitkeep</include>
        </includes>
        <excludes>
          <exclude>META-INF/MANIFEST.MF</exclude>
        </excludes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-private-embedded-jars</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>copy</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>org.graalvm.js</groupId>
                  <artifactId>js-language</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>js-language.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.js</groupId>
                  <artifactId>js-scriptengine</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>js-scriptengine.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.truffle</groupId>
                  <artifactId>truffle-runtime</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>truffle-runtime.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.truffle</groupId>
                  <artifactId>truffle-compiler</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>truffle-compiler.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.truffle</groupId>
                  <artifactId>truffle-enterprise</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>truffle-enterprise.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.polyglot</groupId>
                  <artifactId>polyglot</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>polyglot.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.sdk</groupId>
                  <artifactId>launcher-common</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>launcher-common.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.shadowed</groupId>
                  <artifactId>jline</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>jline.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.sdk</groupId>
                  <artifactId>collections</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>collections.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.sdk</groupId>
                  <artifactId>nativeimage</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>nativeimage.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.sdk</groupId>
                  <artifactId>word</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>word.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.truffle</groupId>
                  <artifactId>truffle-api</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>truffle-api.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.shadowed</groupId>
                  <artifactId>icu4j</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>icu4j.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.apache.groovy</groupId>
                  <artifactId>groovy-jsr223</artifactId>
                  <version>5.0.5</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>groovy-jsr223.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.regex</groupId>
                  <artifactId>regex</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>regex.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.python</groupId>
                  <artifactId>python-language</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>python-language.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.tools</groupId>
                  <artifactId>profiler-tool</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>profiler-tool.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.shadowed</groupId>
                  <artifactId>json</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>json.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.truffle</groupId>
                  <artifactId>truffle-nfi</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>truffle-nfi.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.truffle</groupId>
                  <artifactId>truffle-nfi-libffi</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>truffle-nfi-libffi.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.llvm</groupId>
                  <artifactId>llvm-api</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>llvm-api.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.shadowed</groupId>
                  <artifactId>xz</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>xz.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.bouncycastle</groupId>
                  <artifactId>bcprov-jdk18on</artifactId>
                  <version>1.78.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>bcprov-jdk18on.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.bouncycastle</groupId>
                  <artifactId>bcpkix-jdk18on</artifactId>
                  <version>1.78.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>bcpkix-jdk18on.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.bouncycastle</groupId>
                  <artifactId>bcutil-jdk18on</artifactId>
                  <version>1.78.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>bcutil-jdk18on.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.python</groupId>
                  <artifactId>python-resources</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>python-resources.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.graalvm.wasm</groupId>
                  <artifactId>wasm-language</artifactId>
                  <version>24.2.1</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>wasm-language.jar</destFileName>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <instructions>
            <_include>${project.build.directory}/osgi/MANIFEST.MF</_include>
            <_nodefaultversion>true</_nodefaultversion>
            <_removeheaders>Include-Resource,Private-Package</_removeheaders>
            <Private-Package>!*</Private-Package>
            <Include-Resource>${project.build.outputDirectory}</Include-Resource>
          </instructions>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
