/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.rest.provider.test.util;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

import java.net.URI;
import java.net.http.*;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.*;

import com.eclipsesource.json.Json;
import com.eclipsesource.json.JsonObject;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;
import org.eclipse.jetty.ee10.servlet.ServletContextHandler;
import org.eclipse.jetty.ee10.servlet.ServletHolder;
import org.eclipse.jetty.util.thread.QueuedThreadPool;
import org.eclipse.kura.internal.rest.provider.RestService;
import org.eclipse.kura.core.identity.LoginBannerServiceImpl;
import org.glassfish.jersey.server.ResourceConfig;
import org.glassfish.jersey.servlet.ServletContainer;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Timeout;
import org.mockito.MockedStatic;
import org.osgi.framework.*;
import org.osgi.service.cm.Configuration;
import org.osgi.service.cm.ConfigurationAdmin;

@Timeout(30)
public abstract class AbstractJwtRestScenario {
    public enum IdentityChange {
        DELETED,
        REQUIRED_TO_CHANGE_PASSWORD
    }

    protected static final String IDENTITY = "jwt.alice";
    protected static final String ASSETS_PERMISSION = "rest.assets";
    protected static final int MAX_REFRESH_TOKEN_BYTES = 8 * 1024;

    protected static final String JWT_ENABLED = "auth.jwt.enabled";
    protected static final String ACCESS_TOKEN_DURATION = "auth.jwt.access.token.duration";
    protected static final String REFRESH_TOKEN_DURATION = "auth.jwt.refresh.token.duration";
    protected static final String USED_REFRESH_TOKEN_RETENTION = "auth.jwt.used.refresh.token.retention";
    protected static final String ISSUING_SERVICE_TARGET = "TokenIssuingService.target";
    protected static final String VERIFICATION_SERVICE_TARGET = "TokenVerificationService.target";
    protected static final String DEFAULT_VERIFICATION_SERVICE_TARGET = //
            "(objectClass=org.eclipse.kura.security.token.TokenVerificationService)";
    protected static final String UNMATCHED_TARGET = "(kura.service.pid=does.not.exist)";

    protected static final String SIGNING_KEY_ALIAS = TokenServicesFixture.SIGNING_KEY_ALIAS;
    protected static final String MISSING_KEY_ALIAS = TokenServicesFixture.MISSING_KEY_ALIAS;
    protected static final Duration MAXIMUM_TOKEN_LIFETIME = TokenServicesFixture.MAXIMUM_TOKEN_LIFETIME;

    protected static final Optional<String> NO_AUTHORIZATION = Optional.empty();

    private static final String PASSWORD = "Jwt-Password-1!";
    private static final Map<String, Object> DEFAULT_JWT_CONFIGURATION = Map.of( //
            JWT_ENABLED, false, //
            ACCESS_TOKEN_DURATION, 60, //
            REFRESH_TOKEN_DURATION, 900, //
            USED_REFRESH_TOKEN_RETENTION, 300, //
            ISSUING_SERVICE_TARGET, "(objectClass=org.eclipse.kura.security.token.TokenIssuingService)", //
            VERIFICATION_SERVICE_TARGET, DEFAULT_VERIFICATION_SERVICE_TARGET);

    private JsonObject tokenPair;
    private String accessToken;
    private String refreshToken;
    private final List<String> exchangedRefreshTokens = new ArrayList<>();


    private final IdentityFixture identities = new IdentityFixture();
    protected final RestService rest = new RestService();
    protected final LoginBannerServiceImpl banner = new LoginBannerServiceImpl();
    private final List<ServiceRegistration<?>> registrations = new ArrayList<>();
    private TokenServicesFixture tokenServices;
    protected Server server;
    protected HttpClient client;
    protected String baseUrl;
    private HttpResponse<String> response;
    private boolean activated;
    protected final java.net.CookieManager cookies = new java.net.CookieManager(null, java.net.CookiePolicy.ACCEPT_ALL);
    private final Set<Object> components = new LinkedHashSet<>();
    private ServletContainer container;

    protected void addResource(Object resource) {
        this.components.add(resource);
        this.container.reload(new ResourceConfig().property("jersey.config.server.wadl.disableWadl", true)
                .registerInstances(this.components));
    }


    @BeforeEach
    @SuppressWarnings({ "unchecked", "rawtypes" })
    void setUpHttp() throws Exception {
        this.tokenServices = new TokenServicesFixture();
        this.rest.setUserAdmin(this.identities.userAdmin);
        this.rest.setIdentityService(this.identities.service);
        this.rest.setCryptoService(this.identities.crypto);
        this.rest.setPasswordStrengthVerificationService(this.identities.passwordStrength);
        this.banner.activate(Map.of());
        this.rest.setLoginBannerService(this.banner);
        ConfigurationAdmin configuration = mock(ConfigurationAdmin.class);
        when(configuration.listConfigurations(anyString())).thenReturn(new Configuration[0]);
        this.rest.setConfigurationAdmin(configuration);
        this.rest.bindTokenIssuingService(this.tokenServices.issuer);
        this.rest.bindTokenVerificationService(this.tokenServices.verifier);
        Bundle bundle = mock(Bundle.class);
        BundleContext context = mock(BundleContext.class);
        when(bundle.getBundleContext()).thenReturn(context);
        org.mockito.stubbing.Answer<Object> register = invocation -> {
            components.add(invocation.getArgument(1));
            ServiceRegistration<?> registration = mock(ServiceRegistration.class);
            this.registrations.add(registration);
            return registration;
        };
        doAnswer(register).when(context).registerService(any(Class.class), any(Object.class), any());
        doAnswer(register).when(context).registerService(any(String[].class), any(), any());
        Map<String, Object> options = new HashMap<>(DEFAULT_JWT_CONFIGURATION);
        options.put(JWT_ENABLED, true);
        try (MockedStatic<FrameworkUtil> framework = mockStatic(FrameworkUtil.class, CALLS_REAL_METHODS)) {
            framework.when(() -> FrameworkUtil.getBundle(RestService.class)).thenReturn(bundle);
            this.rest.activate(options);
            this.activated = true;
        }
        components.add(new ProtectedResource());
        ResourceConfig resources = new ResourceConfig().property("jersey.config.server.wadl.disableWadl", true).registerInstances(components);
        QueuedThreadPool threads = new QueuedThreadPool(16, 2);
        threads.setName("kura-jwt-rest-test");
        this.server = new Server(threads);
        this.server.setStopTimeout(5000);
        ServerConnector connector = new ServerConnector(this.server, 1, 1);
        connector.setHost("127.0.0.1");
        connector.setPort(0);
        this.server.addConnector(connector);
        ServletContextHandler servlet = new ServletContextHandler(ServletContextHandler.SESSIONS);
        servlet.setContextPath("/services");
        this.container = new ServletContainer(resources);
        servlet.addServlet(new ServletHolder(this.container), "/*");
        this.server.setHandler(servlet);
        this.server.start();
        this.baseUrl = "http://127.0.0.1:" + connector.getLocalPort() + "/services/";
        this.client = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(5))
                .cookieHandler(this.cookies).build();
        assertEquals(200, request("GET", ProtectedResource.PATH + ProtectedResource.PING_PATH,
                NO_AUTHORIZATION, null).statusCode());
    }

    @AfterEach
    void tearDownHttp() throws Exception {
        try {
            if (this.client != null) { this.client.close(); }
        } finally {
            try {
                if (this.server != null) {
                    this.server.stop();
                    assertTrue(this.server.isStopped());
                    assertTrue(((QueuedThreadPool) this.server.getThreadPool()).isStopped());
                    this.server.destroy();
                }
            } finally {
                try {
                    if (this.activated) {
                        this.rest.deactivate();
                        this.registrations.forEach(registration -> verify(registration).unregister());
                    }
                } finally {
                    if (this.tokenServices != null) { this.tokenServices.close(); }
                }
            }
        }
    }

    protected void givenTheRestServiceProperties(Map<String, Object> properties) {
        Map<String, Object> options = new HashMap<>(DEFAULT_JWT_CONFIGURATION);
        options.put(JWT_ENABLED, true);
        options.putAll(properties);
        // Emulate DS reference arrival/removal; actual SCR target matching is a separate acceptance check.
        if (UNMATCHED_TARGET.equals(options.get(ISSUING_SERVICE_TARGET))) {
            this.rest.unbindTokenIssuingService(this.tokenServices.issuer);
        } else { this.rest.bindTokenIssuingService(this.tokenServices.issuer); }
        if (UNMATCHED_TARGET.equals(options.get(VERIFICATION_SERVICE_TARGET))) {
            this.rest.unbindTokenVerificationService(this.tokenServices.verifier);
        } else { this.rest.bindTokenVerificationService(this.tokenServices.verifier); }
        this.rest.update(options);
    }

    protected void givenTheIssuerSigningKeyAlias(final String alias) throws Exception {
        this.tokenServices.useIssuerSigningKeyAlias(alias);
    }

    protected void givenAnIdentityWithPermissions(final String... permissions) throws Exception {
        this.identities.create(IDENTITY, PASSWORD, List.of(permissions));
    }

    protected void givenTheIdentityIs(final IdentityChange change) throws Exception {
        switch (change) {
        case DELETED -> this.identities.delete(IDENTITY);
        case REQUIRED_TO_CHANGE_PASSWORD -> this.identities.requirePasswordChange(IDENTITY);
        }
    }

    protected void givenATokenPairIssuedToTheIdentity() {
        whenATokenPairIsRequestedWith(basic(IDENTITY));

        thenATokenPairIsReturned();
    }

    protected void givenTheRefreshTokenWasExchangedWithStatus(final int status) {
        whenTheRefreshEndpointReceives(theRefreshToken());

        thenResponseCodeIs(status);

        if (status == 200) {
            thenATokenPairIsReturned();
        }
    }

    protected void givenTimePasses(final Duration duration) throws InterruptedException {
        Thread.sleep(duration.toMillis());
    }


    protected void whenATokenPairIsRequestedWith(Optional<String> authorization) {
        this.response = request("POST", "token/jwt/v1/issue", authorization, null);
    }

    protected void whenTheProtectedResourceIsAccessedWith(Optional<String> authorization) {
        this.response = request("GET", ProtectedResource.PATH + ProtectedResource.ASSETS_PATH, authorization, null);
    }

    protected void whenTheRefreshEndpointReceives(String body) {
        this.response = request("POST", "token/jwt/v1/refresh", NO_AUTHORIZATION, body);
        if (this.response.statusCode() == 200) { this.exchangedRefreshTokens.add(body.trim()); }
    }

    protected IdentityFixture identities() { return this.identities; }

    private HttpResponse<String> request(String method, String path, Optional<String> authorization, String body) {
        Map<String, String> headers = new HashMap<>();
        authorization.ifPresent(value -> headers.put("Authorization", value));
        if (body != null) { headers.put("Content-Type", "text/plain"); }
        return sendRequest(method, path, headers, body);
    }

    protected HttpResponse<String> sendRequest(String method, String path, Map<String, String> headers, String body) {
        HttpRequest.Builder request = HttpRequest.newBuilder(URI.create(this.baseUrl + path))
                .timeout(Duration.ofSeconds(5));
        headers.forEach(request::header);
        request.method(method, body == null ? HttpRequest.BodyPublishers.noBody() : HttpRequest.BodyPublishers.ofString(body));
        try {
            return this.client.send(request.build(), HttpResponse.BodyHandlers.ofString());
        } catch (Exception e) {
            throw new AssertionError("HTTP request failed", e);
        }
    }

    protected void thenResponseCodeIs(int status) {
        assertEquals(status, this.response.statusCode(), () -> this.response.body());
    }

    private JsonObject expectJsonResponse() { return Json.parse(this.response.body()).asObject(); }

    protected void thenATokenPairIsReturned() {
        thenResponseCodeIs(200);

        final JsonObject tokenPair = expectJsonResponse();
        assertEquals(Set.of("tokenType", "accessToken", "accessTokenExpiresInSeconds", "refreshToken",
                "refreshTokenExpiresInSeconds"), new HashSet<>(tokenPair.names()));
        assertEquals("Bearer", tokenPair.get("tokenType").asString());

        this.tokenPair = tokenPair;
        this.accessToken = tokenPair.get("accessToken").asString();
        this.refreshToken = tokenPair.get("refreshToken").asString();
        assertFalse(this.accessToken.isEmpty());
        assertFalse(this.refreshToken.isEmpty());
    }

    // checks both the lifetime reported to the client and the one of the issued tokens
    protected void thenTheTokensLast(final Duration accessTokenDuration, final Duration refreshTokenDuration) {
        assertEquals(accessTokenDuration.toSeconds(), this.tokenPair.get("accessTokenExpiresInSeconds").asLong());
        assertEquals(refreshTokenDuration.toSeconds(), this.tokenPair.get("refreshTokenExpiresInSeconds").asLong());
        assertEquals(accessTokenDuration, lifetime(this.accessToken));
        assertEquals(refreshTokenDuration, lifetime(this.refreshToken));
    }

    protected void thenResponseContainsHeader(final String headerName, final String expectedHeaderValue) {
        assertEquals(List.of(expectedHeaderValue), this.response.headers().allValues(headerName));
    }

    protected void thenTheFirstRefreshTokenIsExpiredButStillVerifiable() throws Exception {
        String token = theFirstExchangedRefreshToken();
        assertTrue(Jwt.claims(token).get("exp").asLong() <= java.time.Instant.now().getEpochSecond());
        org.eclipse.kura.security.token.VerificationProof proof = this.tokenServices.verifier.verify(
                org.eclipse.kura.security.token.TokenVerifyRequest.builder(token)
                        .intendedConsumer(org.eclipse.kura.internal.rest.auth.jwt.JwtRestServiceConstants.INTENDED_REFRESH_CONSUMER)
                        .build());
        assertEquals(IDENTITY, proof.getIdentityName());
    }

    protected void thenTheReturnedRefreshTokenDiffersFromTheExchangedOne() {
        assertNotEquals(this.exchangedRefreshTokens.get(this.exchangedRefreshTokens.size() - 1), this.refreshToken);
    }

    protected void thenTheReturnedAccessTokenGrantsAccessToTheProtectedResource() {
        whenTheProtectedResourceIsAccessedWith(bearer(theAccessToken()));

        thenResponseCodeIs(200);
    }

    /*
     * Step arguments
     */

    protected String theAccessToken() {
        return this.accessToken;
    }

    protected String theRefreshToken() {
        return this.refreshToken;
    }

    protected String theFirstExchangedRefreshToken() {
        return this.exchangedRefreshTokens.get(0);
    }

    protected String theAccessTokenForgedFor(final String identityName) {
        final String forgedToken = Jwt.withSubject(this.accessToken, identityName);
        assertNotEquals(this.accessToken, forgedToken, "the token was not altered");
        return forgedToken;
    }

    protected static Optional<String> basic(final String identityName) {
        final String credentials = identityName + ":" + PASSWORD;
        return header("Basic " + Base64.getEncoder().encodeToString(credentials.getBytes(StandardCharsets.UTF_8)));
    }

    protected static Optional<String> bearer(final String token) {
        return header("Bearer " + token);
    }

    protected static Optional<String> header(final String authorization) {
        return Optional.of(authorization);
    }


    private static Duration lifetime(String token) {
        JsonObject claims = Jwt.claims(token);
        return Duration.ofSeconds(claims.get("exp").asLong() - claims.get("nbf").asLong());
    }
}
