/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.rest.provider.test.util;

import static org.mockito.Mockito.*;
import java.util.*;
import org.apache.felix.useradmin.*;
import org.apache.felix.useradmin.impl.*;
import org.eclipse.kura.core.crypto.CryptoServiceImpl;
import org.eclipse.kura.core.identity.IdentityServiceImpl;
import org.eclipse.kura.core.identity.PasswordStrengthVerificationServiceImpl;
import org.eclipse.kura.identity.*;
import org.osgi.framework.*;
import org.osgi.service.useradmin.*;

public class IdentityFixture {
    public final CryptoServiceImpl crypto = new CryptoServiceImpl();
    public final IdentityServiceImpl service = new IdentityServiceImpl();
    public final PasswordStrengthVerificationServiceImpl passwordStrength = new PasswordStrengthVerificationServiceImpl();
    public final UserAdminImpl userAdmin;

    @SuppressWarnings({ "rawtypes", "unchecked" })
    public IdentityFixture() {
        this.userAdmin = new UserAdminImpl(new RoleRepository(new MemoryRoles()), mock(EventDispatcher.class));
        ServiceRegistration registration = mock(ServiceRegistration.class);
        when(registration.getReference()).thenReturn(mock(ServiceReference.class));
        this.userAdmin.getService(mock(Bundle.class), registration);
        this.passwordStrength.activate(Map.of("new.password.min.length", 8));
        this.service.setCryptoService(this.crypto);
        this.service.setUserAdmin(this.userAdmin);
        this.service.setPasswordStrengthVerificationService(this.passwordStrength);
        this.service.activate();
    }

    public void create(String name, String password, List<String> permissions) throws Exception {
        this.service.createIdentity(name);
        Set<Permission> assigned = new HashSet<>();
        for (String permission : permissions) {
            Permission value = new Permission(permission);
            this.service.createPermission(value);
            assigned.add(value);
        }
        this.service.updateIdentityConfiguration(new IdentityConfiguration(name, List.of(
                new AssignedPermissions(assigned),
                new PasswordConfiguration(false, true, Optional.of(password.toCharArray()), Optional.empty()))));
    }

    public void requirePasswordChange(String name) throws Exception {
        this.service.updateIdentityConfiguration(new IdentityConfiguration(name, List.of(
                new PasswordConfiguration(true, true, Optional.empty(), Optional.empty()))));
    }

    public void delete(String name) throws Exception { this.service.deleteIdentity(name); }

    private static class MemoryRoles implements RoleRepositoryStore {
        private final Map<String, Role> roles = new HashMap<>();

        @Override
        public Role addRole(String name, int type) {
            if (this.roles.containsKey(name)) { return null; }
            Role role = RoleFactory.createRole(type, name);
            this.roles.put(name, role);
            return role;
        }

        @Override
        public Role getRoleByName(String name) { return this.roles.get(name); }

        @Override
        public Role removeRole(String name) { return this.roles.remove(name); }

        @Override
        public Role[] getRoles(String expression) throws Exception {
            Filter filter = expression == null ? null : FrameworkUtil.createFilter(expression);
            return this.roles.values().stream().filter(role -> filter == null || filter.match(role.getProperties()))
                    .toArray(Role[]::new);
        }
    }
}
