/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.rest.provider.test.util;

import java.security.KeyPair;
import java.security.KeyStore;
import java.security.SecureRandom;
import java.security.cert.Certificate;
import java.util.HashMap;
import java.util.Map;
import javax.net.ssl.KeyManagerFactory;
import javax.net.ssl.SSLContext;
import javax.net.ssl.TrustManagerFactory;
import org.bouncycastle.asn1.x500.X500Name;
import org.eclipse.jetty.server.*;
import org.eclipse.jetty.util.ssl.SslContextFactory;
import org.eclipse.kura.core.testutil.pki.TestCA;
import org.eclipse.kura.core.testutil.pki.TestCA.CertificateCreationOptions;

/** Real ephemeral key stores and mutual TLS; no trust-all manager or hostname bypass. */
public class RestTlsFixture {
    private static final String PASSWORD = "test-only-key-password";
    private final Map<String, TestCA> authorities = new HashMap<>();
    private final Map<String, KeyStore> stores = new HashMap<>();

    public void createCA(String name) throws Exception {
        this.authorities.put(name, new TestCA(CertificateCreationOptions.builder(new X500Name("CN=" + name)).build()));
    }

    public void createKeyStore(String name) throws Exception {
        KeyStore store = KeyStore.getInstance("PKCS12");
        store.load(null, PASSWORD.toCharArray());
        this.stores.put(name, store);
    }

    public void trust(String store, String ca) throws Exception {
        this.stores.get(store).setCertificateEntry(ca, this.authorities.get(ca).getCertificate());
    }

    public void createKey(String store, String ca, String cn) throws Exception {
        TestCA authority = this.authorities.get(ca);
        KeyPair key = TestCA.generateKeyPair();
        // The old serverCert CN depended on a permissive client; validate localhost here.
        String subject = "serverCert".equals(cn) ? "localhost" : cn;
        var cert = authority.createAndSignCertificate(
                CertificateCreationOptions.builder(new X500Name("CN=" + subject)).build(), key);
        this.stores.get(store).setKeyEntry(cn, key.getPrivate(), PASSWORD.toCharArray(),
                new Certificate[] { cert, authority.getCertificate() });
    }

    public String addMutualTlsConnector(Server server, String store) throws Exception {
        SslContextFactory.Server ssl = new SslContextFactory.Server();
        ssl.setKeyStore(this.stores.get(store));
        ssl.setKeyStorePassword(PASSWORD);
        ssl.setTrustStore(this.stores.get(store));
        ssl.setNeedClientAuth(true);
        HttpConfiguration http = new HttpConfiguration();
        http.addCustomizer(new SecureRequestCustomizer());
        ServerConnector connector = new ServerConnector(server, 1, 1,
                new SslConnectionFactory(ssl, "http/1.1"), new HttpConnectionFactory(http));
        connector.setHost("127.0.0.1");
        connector.setPort(0);
        server.addConnector(connector);
        connector.start();
        return "https://localhost:" + connector.getLocalPort() + "/services/";
    }

    public SSLContext clientContext(String store) throws Exception {
        KeyManagerFactory keys = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
        keys.init(this.stores.get(store), PASSWORD.toCharArray());
        TrustManagerFactory trust = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
        trust.init(this.stores.get(store));
        SSLContext context = SSLContext.getInstance("TLS");
        context.init(keys.getKeyManagers(), trust.getTrustManagers(), new SecureRandom());
        return context;
    }
}
