/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.rest.provider.test.util;

import static org.mockito.Mockito.*;
import java.security.KeyPair;
import java.security.KeyStore.PrivateKeyEntry;
import java.security.cert.Certificate;
import java.time.Duration;
import java.util.Map;
import org.bouncycastle.asn1.x500.X500Name;
import org.eclipse.kura.core.testutil.pki.TestCA;
import org.eclipse.kura.core.testutil.pki.TestCA.CertificateCreationOptions;
import org.eclipse.kura.core.token.jwt.issuer.JwtIssuingService;
import org.eclipse.kura.core.token.jwt.verifier.JwtVerificationService;
import org.eclipse.kura.security.keystore.KeystoreService;
import org.eclipse.kura.security.token.TokenIssueRequest;
import org.eclipse.kura.security.token.TokenVerifyRequest;
import org.osgi.service.component.ComponentContext;

public class TokenServicesFixture implements AutoCloseable {
    public static final String SIGNING_KEY_ALIAS = "jwt-signing-key";
    public static final String MISSING_KEY_ALIAS = "missing-key";
    public static final Duration MAXIMUM_TOKEN_LIFETIME = Duration.ofHours(1);
    public final JwtIssuingService issuer = new JwtIssuingService();
    public final JwtVerificationService verifier = new JwtVerificationService();

    public TokenServicesFixture() throws Exception {
        TestCA ca = new TestCA(CertificateCreationOptions.builder(new X500Name("cn=jwt-rest-test-ca")).build());
        KeyPair key = TestCA.generateKeyPair();
        Certificate certificate = ca.createAndSignCertificate(
                CertificateCreationOptions.builder(new X500Name("cn=jwt-rest-signer")).build(), key);
        PrivateKeyEntry entry = new PrivateKeyEntry(key.getPrivate(), new Certificate[] { certificate, ca.getCertificate() });
        KeystoreService keystore = mock(KeystoreService.class);
        when(keystore.getEntry(SIGNING_KEY_ALIAS)).thenReturn(entry);
        when(keystore.getEntries()).thenReturn(Map.of(SIGNING_KEY_ALIAS, entry));
        Map<String, Object> serviceProperties = Map.of("kura.service.pid", "jwt-rest-test-keystore");
        this.issuer.setKeystoreService(keystore, serviceProperties);
        this.verifier.setKeystoreService(keystore, serviceProperties);
        this.verifier.activate(mock(ComponentContext.class), Map.of());
        useIssuerSigningKeyAlias(SIGNING_KEY_ALIAS);
        String probe = this.issuer.issue(TokenIssueRequest.builder("probe").intendedConsumer("probe").build());
        this.verifier.verify(TokenVerifyRequest.builder(probe).intendedConsumer("probe").build());
    }

    public void useIssuerSigningKeyAlias(String alias) {
        this.issuer.updated(Map.of("signing.key.alias", alias, "maximum.lifetime.seconds",
                (int) MAXIMUM_TOKEN_LIFETIME.toSeconds()));
    }

    @Override
    public void close() {
        this.issuer.deactivate();
        this.verifier.deactivate();
    }
}
