/*******************************************************************************
 * Copyright (c) 2021, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 * Content with portions generated by generative AI platform
 *******************************************************************************/
package org.eclipse.kura.https.server.manager.test;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.ServerSocket;
import java.net.URI;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.KeyPair;
import java.security.KeyStore;
import java.security.cert.Certificate;
import java.security.cert.X509Certificate;
import java.util.ArrayList;
import java.util.EventListener;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Future;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CountDownLatch;
import org.eclipse.jetty.io.ssl.SslHandshakeListener;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.TimeUnit;
import java.util.function.BooleanSupplier;

import javax.net.ssl.HttpsURLConnection;
import javax.net.ssl.KeyManagerFactory;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLException;
import javax.net.ssl.TrustManagerFactory;

import org.bouncycastle.asn1.x500.X500Name;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;
import org.eclipse.kura.core.keystore.FilesystemKeystoreServiceImpl;
import org.eclipse.kura.core.testutil.TestUtil;
import org.eclipse.kura.core.testutil.http.TestServer;
import org.eclipse.kura.core.testutil.pki.TestCA;
import org.eclipse.kura.core.testutil.pki.TestCA.CertificateCreationOptions;
import org.eclipse.kura.core.testutil.pki.TestCA.CRLCreationOptions;
import org.eclipse.kura.crypto.CryptoService;
import org.eclipse.kura.security.keystore.KeystoreChangedEvent;
import org.eclipse.kura.security.keystore.KeystoreService;
import org.eclipse.osgi.launch.EquinoxFactory;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.io.TempDir;
import org.osgi.framework.Bundle;
import org.osgi.framework.BundleReference;
import org.osgi.framework.Constants;
import org.osgi.framework.FrameworkEvent;
import org.osgi.framework.launch.Framework;
import org.osgi.service.component.ComponentContext;
import org.osgi.service.event.Event;
import org.osgi.service.event.EventAdmin;

import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSessionListener;

/** Actual manager, Jetty, filesystem keystore and TLS; explicit lifecycle replaces global SCR. */
@Timeout(90)
class HttpServiceTest {
    @TempDir Path directory;
    private Framework framework;
    private ManagerLoader loader;
    private Object manager;
    private FilesystemKeystoreServiceImpl keystore;
    private TestServer crlServer;
    private TestCA serverCA;
    private TestCA clientCA;
    private X509Certificate clientCertificate;
    private KeyStore clientKeys;
    private volatile boolean active;
    private final BlockingQueue<Event> events = new LinkedBlockingQueue<>();

    @BeforeEach
    void prepare() throws Exception {
        this.framework = new EquinoxFactory().newFramework(Map.of(Constants.FRAMEWORK_STORAGE,
                this.directory.resolve("osgi").toString()));
        this.framework.start();
        Bundle bundle = this.framework.getBundleContext().getBundle();
        Files.createDirectories(bundle.getBundleContext().getDataFile("").toPath());
        URL classes = org.eclipse.kura.http.server.manager.HttpService.class.getProtectionDomain()
                .getCodeSource().getLocation();
        this.loader = new ManagerLoader(classes, bundle);
        this.manager = this.loader.loadClass("org.eclipse.kura.http.server.manager.HttpService")
                .getConstructor().newInstance();
        invoke("setDispatcherServlet", HttpServlet.class, new HttpServlet() {
            @Override protected void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
                response.sendError(404);
            }
        });
        invoke("setEventListener", EventListener.class, new HttpSessionListener() {});
    }

    @Test
    void shouldNotOpenAnyPortWithDefaultConfig() throws Exception {
        createKeystore(false);
        configure(Map.of());
        assertEquals(0, server().getConnectors().length);
    }

    @Test
    void shouldOpenHttpPorts() throws Exception {
        createKeystore(false);
        configure(Map.of("http.ports", new Integer[] { 0 }));
        assertEquals(1, server().getConnectors().length);
        assertEquals(404, request(connector(0), false, false));
    }

    @Test
    void repeatedKeystoreInjectionDuringStartupDoesNotOpenAnotherServer() throws Exception {
        int port;
        try (ServerSocket socket = new ServerSocket(0)) {
            port = socket.getLocalPort();
        }
        ExecutorService executor = (ExecutorService) TestUtil.getFieldValue(this.manager, "executorService");
        CountDownLatch releaseStartup = new CountDownLatch(1);
        Future<?> blocked = executor.submit(() -> {
            releaseStartup.await();
            return null;
        });
        try {
            invoke("activate", Map.class, Map.of("http.ports", new Integer[] { port }));
            createKeystore(false);
            this.manager.getClass().getMethod("setKeystoreService", KeystoreService.class, Map.class)
                    .invoke(this.manager, this.keystore, Map.of("kura.service.pid", "test-keystore"));
        } finally {
            releaseStartup.countDown();
        }
        blocked.get(5, TimeUnit.SECONDS);
        drainManager();
        assertEquals(port, connector(0).getLocalPort());
        assertEquals(404, request(connector(0), false, false));
    }

    @Test
    void shouldOpenMultipleHttpPorts() throws Exception {
        createKeystore(false);
        final Integer[] ports;
        try (ServerSocket one = new ServerSocket(0); ServerSocket two = new ServerSocket(0);
                ServerSocket three = new ServerSocket(0)) {
            ports = new Integer[] { one.getLocalPort(), two.getLocalPort(), three.getLocalPort() };
        }
        configure(Map.of("http.ports", ports));
        assertEquals(3, server().getConnectors().length);
        for (int i = 0; i < 3; i++) { assertEquals(404, request(connector(i), false, false)); }
    }

    @Test
    void shouldNotSupportHttpsWithoutKeystore() throws Exception {
        // Retain the fork's real, bounded keystore monitor before the HTTP-only fallback.
        configure(Map.of("https.ports", new Integer[] { 0 }, "https.client.auth.ports", new Integer[] { 0 }));
        assertEquals(0, server().getConnectors().length);
    }

    @Test
    void shouldSupportHttps() throws Exception {
        createKeystore(false);
        configure(Map.of("https.ports", new Integer[] { 0 }));
        assertEquals(1, server().getConnectors().length);
        assertEquals(404, request(connector(0), true, false));
    }

    @Test
    void shouldSupportHttpsClientAuth() throws Exception {
        createKeystore(false);
        configure(Map.of("https.client.auth.ports", new Integer[] { 0 }));
        assertEquals(1, server().getConnectors().length);
        assertEquals(404, request(connector(0), true, true));
    }

    @Test
    void shouldSupportRevocationCheckWithNoSources() throws Exception {
        createKeystore(false);
        configure(Map.of("https.client.auth.ports", new Integer[] { 0 }, "https.revocation.check.enabled", true));
        assertEquals(1, server().getConnectors().length);
        assertTlsHandshakeRejected(connector(0), true);
    }

    @Test
    void shouldSupportRevocation() throws Exception {
        createKeystore(true);
        await(() -> {
            try { return !this.keystore.getCRLs().isEmpty(); }
            catch (Exception e) { throw new AssertionError(e); }
        }, 35);
        configure(Map.of("https.client.auth.ports", new Integer[] { 0 }, "https.revocation.check.enabled", true));
        assertEquals(404, request(connector(0), true, true));
        this.events.clear();
        this.clientCA.revokeCertificate(this.clientCertificate);
        publishCRL();
        Event changed = this.events.poll(35, TimeUnit.SECONDS);
        assertInstanceOf(KeystoreChangedEvent.class, changed, "CRL change must be published");
        ((Future<?>) TestUtil.getFieldValue(this.manager, "restartTask")).get(20, TimeUnit.SECONDS);
        drainManager();
        assertTlsHandshakeRejected(connector(0), true);
    }

    @Test
    void shouldRejectClientConnectionWithNoCert() throws Exception {
        createKeystore(false);
        configure(Map.of("https.client.auth.ports", new Integer[] { 0 }));
        assertTlsHandshakeRejected(connector(0), false);
    }

    @Test
    void shouldSupportAllAuthMethods() throws Exception {
        createKeystore(false);
        configure(Map.of("http.ports", new Integer[] { 0 }, "https.ports", new Integer[] { 0 },
                "https.client.auth.ports", new Integer[] { 0 }));
        assertEquals(3, server().getConnectors().length);
        assertEquals(404, request(connector(0), false, false));
        assertEquals(404, request(connector(1), true, false));
        assertEquals(404, request(connector(2), true, true));
    }

    private void configure(Map<String, Object> properties) throws Exception {
        this.active = true;
        invoke("activate", Map.class, properties);
        await(() -> {
            try { drainManager(); return TestUtil.getFieldValue(this.manager, "jettyServerHolder") != null; }
            catch (Exception e) { throw new AssertionError(e); }
        }, 18);
        assertTrue(server().isStarted(), "Manager must actually start Jetty");
    }

    private void createKeystore(boolean crls) throws Exception {
        this.serverCA = new TestCA(CertificateCreationOptions.builder(new X500Name("cn=Server CA, dc=test")).build());
        this.clientCA = new TestCA(CertificateCreationOptions.builder(new X500Name("cn=Client CA, dc=test")).build());
        KeyPair serverKey = TestCA.generateKeyPair();
        X509Certificate serverCertificate = this.serverCA.createAndSignCertificate(
                CertificateCreationOptions.builder(new X500Name("cn=localhost, dc=test")).build(), serverKey);
        KeyPair clientKey = TestCA.generateKeyPair();
        this.clientCertificate = this.clientCA.createAndSignCertificate(
                CertificateCreationOptions.builder(new X500Name("cn=admin, dc=test")).build(), clientKey);
        this.clientKeys = KeyStore.getInstance("PKCS12");
        this.clientKeys.load(null, null);
        this.clientKeys.setKeyEntry("client", clientKey.getPrivate(), "test-password".toCharArray(),
                new Certificate[] { this.clientCertificate, this.clientCA.getCertificate() });
        KeyStore serverKeys = KeyStore.getInstance("PKCS12");
        serverKeys.load(null, null);
        serverKeys.setKeyEntry("server", serverKey.getPrivate(), "test-password".toCharArray(),
                new Certificate[] { serverCertificate, this.serverCA.getCertificate() });
        serverKeys.setCertificateEntry("client-ca", this.clientCA.getCertificate());
        Path file = this.directory.resolve("server.p12");
        try (var out = Files.newOutputStream(file)) { serverKeys.store(out, "test-password".toCharArray()); }
        CryptoService crypto = mock(CryptoService.class);
        when(crypto.decryptAes(any(char[].class))).thenAnswer(call -> call.getArgument(0));
        when(crypto.encryptAes(any(char[].class))).thenAnswer(call -> call.getArgument(0));
        EventAdmin eventAdmin = mock(EventAdmin.class);
        doAnswer(call -> {
            Event event = call.getArgument(0);
            if (this.active) {
                invoke("handleEvent", Event.class, event);
                this.events.offer(event);
            }
            return null;
        }).when(eventAdmin).postEvent(any());
        ComponentContext context = mock(ComponentContext.class);
        when(context.getBundleContext()).thenReturn(this.framework.getBundleContext());
        this.keystore = new FilesystemKeystoreServiceImpl();
        this.keystore.setCryptoService(crypto);
        this.keystore.setEventAdmin(eventAdmin);
        Map<String, Object> options = new HashMap<>(Map.of("kura.service.pid", "test-keystore", "keystore.path",
                file.toString(), "keystore.password", "test-password", "randomize.password", false,
                "crl.management.enabled", crls));
        if (crls) {
            this.crlServer = new TestServer(0, Optional.empty());
            publishCRL();
            options.put("crl.urls", new String[] { "http://127.0.0.1:" + this.crlServer.getPort() + "/crl.pem" });
            options.put("crl.check.interval", 1L);
            options.put("crl.check.interval.time.unit", TimeUnit.SECONDS.name());
            options.put("crl.update.interval", 1L);
            options.put("crl.update.interval.time.unit", TimeUnit.SECONDS.name());
        }
        this.keystore.activate(context, options);
        this.manager.getClass().getMethod("setKeystoreService", KeystoreService.class, Map.class)
                .invoke(this.manager, this.keystore, Map.of("kura.service.pid", "test-keystore"));
    }

    private void publishCRL() throws Exception {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            TestCA.encodeToPEM(this.clientCA.generateCRL(CRLCreationOptions.builder().build()), out);
            this.crlServer.setResource("/crl.pem", out.toByteArray());
        }
    }

    private SSLContext clientContext(boolean clientAuth) throws Exception {
        KeyStore trust = KeyStore.getInstance("PKCS12");
        trust.load(null, null);
        trust.setCertificateEntry("server-ca", this.serverCA.getCertificate());
        TrustManagerFactory tmf = TrustManagerFactory.getInstance("PKIX");
        tmf.init(trust);
        KeyManagerFactory kmf = KeyManagerFactory.getInstance("SunX509");
        kmf.init(this.clientKeys, "test-password".toCharArray());
        SSLContext ssl = SSLContext.getInstance("TLS");
        ssl.init(clientAuth ? kmf.getKeyManagers() : null, tmf.getTrustManagers(), null);
        return ssl;
    }

    private void assertTlsHandshakeRejected(ServerConnector connector, boolean clientAuth) throws Exception {
        assertTrue(server().isStarted());
        assertTrue(connector.isOpen(), "A closed listener must not look like certificate rejection");
        CompletableFuture<Throwable> serverFailure = new CompletableFuture<>();
        SslHandshakeListener listener = new SslHandshakeListener() {
            @Override public void handshakeFailed(SslHandshakeListener.Event event, Throwable failure) {
                serverFailure.complete(failure);
            }
        };
        connector.addBean(listener);
        try {
            // Depending on TLS alert delivery, the client sees an SSLException or a connection reset.
            assertThrows(IOException.class, () -> request(connector, true, clientAuth));
            assertInstanceOf(SSLException.class, serverFailure.get(3, TimeUnit.SECONDS),
                    "The running server must report an actual TLS handshake failure");
        } finally { connector.removeBean(listener); }
    }

    private int request(ServerConnector connector, boolean tls, boolean clientAuth) throws Exception {
        URL url = URI.create((tls ? "https" : "http") + "://127.0.0.1:" + connector.getLocalPort() + "/").toURL();
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        connection.setConnectTimeout(3000);
        connection.setReadTimeout(3000);
        connection.setInstanceFollowRedirects(false);
        connection.setRequestProperty("Connection", "close");
        try {
            if (tls) {
                SSLContext ssl = clientContext(clientAuth);
                HttpsURLConnection https = (HttpsURLConnection) connection;
                https.setSSLSocketFactory(ssl.getSocketFactory());
                https.setHostnameVerifier((host, session) -> true);
            }
            int status = connection.getResponseCode();
            if (connection.getErrorStream() != null) { connection.getErrorStream().close(); }
            return status;
        } finally { connection.disconnect(); }
    }

    private void invoke(String method, Class<?> type, Object value) throws Exception {
        this.manager.getClass().getMethod(method, type).invoke(this.manager, value);
    }

    private void drainManager() throws Exception {
        ((ExecutorService) TestUtil.getFieldValue(this.manager, "executorService")).submit(() -> {}).get(5, TimeUnit.SECONDS);
    }

    private Server server() throws Exception {
        Object holder = TestUtil.getFieldValue(this.manager, "jettyServerHolder");
        return (Server) TestUtil.getFieldValue(holder, "server");
    }

    private ServerConnector connector(int index) throws Exception { return (ServerConnector) server().getConnectors()[index]; }

    private static void await(BooleanSupplier condition, int seconds) throws InterruptedException {
        long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(seconds);
        while (!condition.getAsBoolean()) {
            assertTrue(System.nanoTime() < deadline, "Timed out waiting for component state");
            Thread.sleep(25);
        }
    }

    @AfterEach
    void close() throws Exception {
        this.active = false;
        try {
            if (this.manager != null) {
                Object holder = TestUtil.getFieldValue(this.manager, "jettyServerHolder");
                Server running = holder == null ? null : (Server) TestUtil.getFieldValue(holder, "server");
                this.manager.getClass().getMethod("deactivate").invoke(this.manager);
                if (running != null) {
                    assertTrue(running.isStopped(), "Jetty must stop before temporary storage is removed");
                    for (var connector : running.getConnectors()) {
                        assertFalse(((ServerConnector) connector).isOpen(), "Listener must be closed");
                    }
                }
                assertTrue(((ExecutorService) TestUtil.getFieldValue(this.manager, "executorService")).isTerminated());
            }
        } finally {
            try {
                if (this.keystore != null) {
                    List<ExecutorService> executors = new ArrayList<>();
                    executors.add((ExecutorService) TestUtil.getFieldValue(this.keystore, "selfUpdaterExecutor"));
                    Optional<?> crl = (Optional<?>) TestUtil.getFieldValue(this.keystore, "crlManager");
                    if (crl.isPresent()) {
                        executors.add((ExecutorService) TestUtil.getFieldValue(crl.get(), "updateExecutor"));
                        executors.add((ExecutorService) TestUtil.getFieldValue(crl.get(), "downloadExecutor"));
                    }
                    this.keystore.deactivate();
                    for (ExecutorService executor : executors) { assertTrue(executor.awaitTermination(5, TimeUnit.SECONDS)); }
                }
            } finally {
                if (this.crlServer != null) { this.crlServer.close(); }
                if (this.loader != null) { this.loader.close(); }
                if (this.framework != null) {
                    this.framework.stop();
                    assertEquals(FrameworkEvent.STOPPED, this.framework.waitForStop(5000).getType());
                }
            }
        }
    }

    /** Only manager classes are isolated; FrameworkUtil resolves their actual private Equinox bundle context. */
    private static final class ManagerLoader extends URLClassLoader implements BundleReference {
        private final Bundle bundle;
        ManagerLoader(URL classes, Bundle bundle) {
            super(new URL[] { classes }, HttpServiceTest.class.getClassLoader());
            this.bundle = bundle;
        }
        @Override public Bundle getBundle() { return this.bundle; }
        @Override protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
            synchronized (getClassLoadingLock(name)) {
                Class<?> loaded = findLoadedClass(name);
                if (loaded == null) {
                    loaded = name.startsWith("org.eclipse.kura.http.server.manager.") ? findClass(name) : super.loadClass(name, false);
                }
                if (resolve) { resolveClass(loaded); }
                return loaded;
            }
        }
    }
}
