<?xml version="1.0"?>
<!--
    Copyright (c) 2011, 2025 Eurotech and/or its affiliates and others
  
    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/
 
    SPDX-License-Identifier: EPL-2.0
 
    Contributors:
     Eurotech
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.eclipse.kura</groupId>
        <artifactId>target-platform</artifactId>
        <version>6.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>p2-repo-common</artifactId>
    <packaging>pom</packaging>
    <build>
        <plugins> 
            <plugin>
				<groupId>org.reficio</groupId>
				<artifactId>p2-maven-plugin</artifactId>
				<version>${p2-maven-plugin.version}</version>
				<executions>
					<execution>
						<id>generate-p2-site</id>
						<phase>initialize</phase>
						<goals>
							<goal>site</goal>
						</goals>
						<configuration>
							<artifacts>
							<!-- vertx  -->
								<artifact>
									<id>io.vertx:vertx-core:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.vertx:vertx-core-logging:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.vertx:vertx-web-common:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.vertx:vertx-web:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.vertx:vertx-http-proxy:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.vertx:vertx-bridge-common:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.vertx:vertx-web-client:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.vertx:vertx-uri-template:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.vertx:vertx-tcp-eventbus-bridge:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.vertx:vertx-mqtt:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.vertx:vertx-auth-common:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>com.digitalpetri.fsm:strict-machine:jar:${strict-machine.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>com.digitalpetri.netty:netty-channel-fsm:jar:${netty-channel-fsm.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>tel.schich:javacan-core:jar:${javacan.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>com.alibaba.fastjson2:fastjson2:jar:${fastjson2.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.apache.qpid:qpid-jms-client:${apache-qpid-jms-client.version}</id>
									<source>true</source>
									<transitive>false</transitive>
									<override>true</override>
									<instructions>
										<Import-Package>io.opentracing;resolution:=optional,io.opentracing.propa
													 gation;resolution:=optional,io.opentracing.tag;resolution:=optional,io.
													 opentracing.util;resolution:=optional,io.netty.channel.epoll;resolution
													 :=optional;version="[4.1.0,5.0.0)",io.netty.channel.kqueue;resolution:=
													 optional;version="[4.1.0,5.0.0)",io.netty.handler.proxy;resolution:=opt
													 ional;version="[4.1.0,5.0.0)",io.netty.bootstrap;version="[4.1.0,5.0.0)
													 ",io.netty.buffer;version="[4.1.0,5.0.0)",io.netty.channel;version="[4.
													 1.0,5.0.0)",io.netty.channel.nio;version="[4.1.0,5.0.0)",io.netty.chann
													 el.socket.nio;version="[4.1.0,5.0.0)",io.netty.handler.codec.http;versi
													 on="[4.1.0,5.0.0)",io.netty.handler.codec.http.websocketx;version="[4.1
													 .0,5.0.0)",io.netty.handler.logging;version="[4.1.0,5.0.0)",io.netty.ha
													 ndler.ssl;version="[4.1.0,5.0.0)",io.netty.handler.ssl.util;version="[4
													 .1.0,5.0.0)",io.netty.resolver;version="[4.1.0,5.0.0)",io.netty.util;ve
													 rsion="[4.1.0,5.0.0)",io.netty.util.concurrent;version="[4.1.0,5.0.0)",
													 org.apache.qpid.proton.amqp;version="[0.33.2,0.40.0)",org.apache.qpid.p
													 roton.amqp.messaging;version="[0.33.2,0.40.0)",org.apache.qpid.proton.a
													 mqp.security;version="[0.33.2,0.40.0)",org.apache.qpid.proton.amqp.tran
													 saction;version="[0.33.2,0.40.0)",org.apache.qpid.proton.amqp.transport
													 ;version="[0.33.2,0.40.0)",org.apache.qpid.proton.codec;version="[0.33.
													 2,0.40.0)",org.apache.qpid.proton.engine;version="[0.33.2,0.40.0)",org.
													 apache.qpid.proton.engine.impl;version="[0.33.2,0.40.0)",org.apache.qpi
													 d.proton.framing;version="[0.33.2,0.40.0)",org.apache.qpid.proton.messa
													 ge;version="[0.33.2,0.40.0)",jakarta.jms;version="[3.1,4)",java.beans,j
													 ava.io,java.lang,java.lang.invoke,java.lang.reflect,java.math,java.net,
													 java.nio,java.nio.charset,java.security,java.security.cert,java.text,ja
													 va.util,java.util.concurrent,java.util.concurrent.atomic,java.util.conc
													 urrent.locks,java.util.function,java.util.regex,javax.crypto,javax.cryp
													 to.spec,javax.naming,javax.naming.spi,javax.net.ssl,javax.security.auth
													 ,javax.security.auth.callback,javax.security.auth.login,javax.security.
													 sasl,org.apache.qpid.jms,org.apache.qpid.jms.exceptions,org.apache.qpid
													 .jms.jndi,org.apache.qpid.jms.message,org.apache.qpid.jms.message.facad
													 e,org.apache.qpid.jms.meta,org.apache.qpid.jms.policy,org.apache.qpid.j
													 ms.provider,org.apache.qpid.jms.provider.amqp,org.apache.qpid.jms.provi
													 der.amqp.builders,org.apache.qpid.jms.provider.amqp.filters,org.apache.
													 qpid.jms.provider.amqp.message,org.apache.qpid.jms.provider.exceptions,
													 org.apache.qpid.jms.sasl,org.apache.qpid.jms.selector,org.apache.qpid.j
													 ms.selector.filter,org.apache.qpid.jms.selector.parser,org.apache.qpid.
													 jms.tracing,org.apache.qpid.jms.transports,org.apache.qpid.jms.util,org
													 .slf4j;version="[2.0,3)"
										 </Import-Package>
										<Export-Package>org.apache.qpid.jms;uses:="jakarta.jms,javax.net.ssl,org
													 .apache.qpid.jms.jndi,org.apache.qpid.jms.message,org.apache.qpid.jms.m
													 eta,org.apache.qpid.jms.policy,org.apache.qpid.jms.provider,org.apache.
													 qpid.jms.tracing,org.apache.qpid.jms.util,org.slf4j";version="2.7.0",or
													 g.apache.qpid.jms.exceptions;uses:="jakarta.jms";version="2.7.0",org.ap
													 ache.qpid.jms.jndi;uses:="jakarta.jms,javax.naming,javax.naming.spi,org
													 .apache.qpid.jms";version="2.7.0",org.apache.qpid.jms.message;uses:="ja
													 karta.jms,org.apache.qpid.jms,org.apache.qpid.jms.message.facade,org.ap
													 ache.qpid.jms.meta,org.apache.qpid.jms.provider";version="2.7.0",org.ap
													 ache.qpid.jms.message.facade;uses:="jakarta.jms,org.apache.qpid.jms,org
													 .apache.qpid.jms.tracing";version="2.7.0",org.apache.qpid.jms.meta;uses
													 :="jakarta.jms,org.apache.qpid.jms,org.apache.qpid.jms.message,org.apac
													 he.qpid.jms.policy,org.apache.qpid.jms.tracing";version="2.7.0",org.apa
													 che.qpid.jms.policy;uses:="org.apache.qpid.jms,org.apache.qpid.jms.mess
													 age";version="2.7.0",org.apache.qpid.jms.provider;uses:="jakarta.jms,or
													 g.apache.qpid.jms.message,org.apache.qpid.jms.meta";version="2.7.0",org
													 .apache.qpid.jms.provider.amqp;uses:="io.netty.buffer,org.apache.qpid.j
													 ms,org.apache.qpid.jms.message,org.apache.qpid.jms.meta,org.apache.qpid
													 .jms.provider,org.apache.qpid.jms.provider.amqp.message,org.apache.qpid
													 .jms.provider.exceptions,org.apache.qpid.jms.sasl,org.apache.qpid.jms.t
													 ransports,org.apache.qpid.proton.amqp,org.apache.qpid.proton.amqp.messa
													 ging,org.apache.qpid.proton.amqp.security,org.apache.qpid.proton.amqp.t
													 ransaction,org.apache.qpid.proton.amqp.transport,org.apache.qpid.proton
													 .engine,org.apache.qpid.proton.engine.impl,org.apache.qpid.proton.frami
													 ng,org.slf4j";version="2.7.0",org.apache.qpid.jms.provider.amqp.builder
													 s;uses:="org.apache.qpid.jms,org.apache.qpid.jms.meta,org.apache.qpid.j
													 ms.provider,org.apache.qpid.jms.provider.amqp,org.apache.qpid.proton.en
													 gine";version="2.7.0",org.apache.qpid.jms.provider.amqp.filters;uses:="
													 org.apache.qpid.proton.amqp";version="2.7.0",org.apache.qpid.jms.provid
													 er.amqp.message;uses:="io.netty.buffer,jakarta.jms,org.apache.qpid.jms,
													 org.apache.qpid.jms.exceptions,org.apache.qpid.jms.message,org.apache.q
													 pid.jms.message.facade,org.apache.qpid.jms.policy,org.apache.qpid.jms.p
													 rovider.amqp,org.apache.qpid.jms.util,org.apache.qpid.proton.amqp,org.a
													 pache.qpid.proton.amqp.messaging,org.apache.qpid.proton.codec,org.apach
													 e.qpid.proton.message";version="2.7.0",org.apache.qpid.jms.provider.exc
													 eptions;uses:="jakarta.jms,org.apache.qpid.jms,org.apache.qpid.jms.exce
													 ptions,org.apache.qpid.jms.message,org.apache.qpid.jms.provider,org.apa
													 che.qpid.proton.amqp.messaging";version="2.7.0",org.apache.qpid.jms.pro
													 vider.failover;uses:="org.apache.qpid.jms.message,org.apache.qpid.jms.m
													 eta,org.apache.qpid.jms.provider";version="2.7.0",org.apache.qpid.jms.s
													 asl;uses:="javax.security.sasl";version="2.7.0",org.apache.qpid.jms.sel
													 ector;uses:="org.apache.qpid.jms.selector.filter";version="2.7.0",org.a
													 pache.qpid.jms.selector.filter;version="2.7.0",org.apache.qpid.jms.sele
													 ctor.parser;uses:="org.apache.qpid.jms.selector.filter";version="2.7.0"
													 ,org.apache.qpid.jms.tracing;version="2.7.0",org.apache.qpid.jms.tracin
													 g.opentracing;uses:="io.opentracing,org.apache.qpid.jms.tracing";versio
													 n="2.7.0",org.apache.qpid.jms.transports;uses:="io.netty.buffer,io.nett
													 y.handler.ssl,javax.net.ssl";version="2.7.0",org.apache.qpid.jms.transp
													 orts.netty;uses:="io.netty.bootstrap,io.netty.buffer,io.netty.channel,j
													 avax.net.ssl,org.apache.qpid.jms.transports";version="2.7.0",org.apache
													 .qpid.jms.util;uses:="org.apache.qpid.jms.message";version="2.7.0"
										</Export-Package>
									</instructions>
								</artifact>
								<artifact>
									<id>org.eclipse.paho:org.eclipse.paho.mqttv5.client:${org.eclipse.paho.client.mqttv3.version}</id>
									<source>true</source>
									<transitive>false</transitive>
									<override>true</override>
									<instructions>
										<Import-Package>*;resolution:=optional</Import-Package>
										<Export-Package>org.eclipse.paho.mqttv5.client;version="1.2.5",
														org.eclipse.paho.mqttv5.client.persist;version="1.2.5",
														org.eclipse.paho.mqttv5.common;version="1.2.5",
														org.eclipse.paho.mqttv5.common.packet;version="1.2.5"
										</Export-Package>
									</instructions>
								</artifact>
								
								<artifact>
									<id>junit:junit:${org.junit.version}</id>
									<source>true</source>
									<transitive>false</transitive>
									<override>true</override>
									<instructions>
										<Export-Package>junit.extensions;version="4.13.2",junit.framework;vers
					                         ion="4.13.2",junit.runner;version="4.13.2",junit.textui;version="4.13
					                         .2",org.junit;version="4.13.2",org.junit.experimental;version="4.13.2
					                         ",org.junit.experimental.categories;version="4.13.2",org.junit.experi
					                         mental.max;version="4.13.2",org.junit.experimental.results;version="4
					                         .13.2",org.junit.experimental.runners;version="4.13.2",org.junit.expe
					                         rimental.theories;version="4.13.2",org.junit.experimental.theories.in
					                         ternal;version="4.13.2";x-internal:=true,org.junit.experimental.theor
					                         ies.suppliers;version="4.13.2",org.junit.internal;version="4.13.2";x-
					                         internal:=true,org.junit.internal.builders;version="4.13.2";x-interna
					                         l:=true,org.junit.internal.matchers;version="4.13.2";x-internal:=true
					                         ,org.junit.internal.requests;version="4.13.2";x-internal:=true,org.ju
					                         nit.internal.runners;version="4.13.2";x-internal:=true,org.junit.inte
					                         rnal.runners.model;version="4.13.2";x-internal:=true,org.junit.intern
					                         al.runners.rules;version="4.13.2";x-internal:=true,org.junit.internal
					                         .runners.statements;version="4.13.2";x-internal:=true,org.junit.match
					                         ers;version="4.13.2",org.junit.rules;version="4.13.2",org.junit.runne
					                         r;version="4.13.2",org.junit.runner.manipulation;version="4.13.2",org
					                         .junit.runner.notification;version="4.13.2",org.junit.runners;version
					                         ="4.13.2",org.junit.runners.model;version="4.13.2",org.junit.runners.
					                         parameterized;version="4.13.2",org.junit.validator;version="4.13.2"
				                        </Export-Package>
										<Bundle-SymbolicName>org.junit</Bundle-SymbolicName>
									</instructions>
								</artifact>
								<artifactItem>
									<id>io.moquette:moquette-broker:${moquette-broker.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifactItem>
                                
                            </artifacts>
						</configuration>
					</execution>
				</executions>
			</plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <id>install-p2-bundles-to-local-m2</id>
                        <phase>install</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <exec executable="${project.basedir}/../install-to-m2.sh"
                                      dir="${project.basedir}"
                                      failonerror="true">
                                    <arg value="${project.build.directory}/repository/plugins" />
                                    <arg value="p2.osgi.bundle" />
                                </exec>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>