<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (c) 2025, 2026 Eurotech and contributors.
     SPDX-License-Identifier: EPL-2.0 -->
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.kura</groupId><artifactId>kura-build-parent</artifactId>
    <version>${kuraVersion}</version><relativePath/>
  </parent>
  <groupId>${groupId}</groupId><artifactId>${artifactId}</artifactId>
  <version>${version}</version><packaging>pom</packaging>
  <properties>
    <kura.api.version>3.0.0-SNAPSHOT</kura.api.version>
    <kura.configuration.version>3.0.0-SNAPSHOT</kura.configuration.version>
  </properties>
  <build><plugins><plugin>
    <groupId>org.apache.maven.plugins</groupId><artifactId>maven-deploy-plugin</artifactId>
    <configuration><skip>true</skip></configuration>
  </plugin></plugins></build>
  <modules><module>bundles</module><module>tests</module><module>distrib</module></modules>
</project>
