/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.issuer;

import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.IssuingConfig;
import org.eclipse.kura.core.token.jwt.common.TokenInspector;
import org.eclipse.kura.security.token.TokenIssueRequest;
import org.junit.jupiter.api.Test;

public class TokenIdentifierTest extends AbstractJwtScenario {

    private String firstTokenId;
    private String secondTokenId;

    @Test
    public void everyIssuedTokenCarriesATokenIdentifier() throws TestCAException {
        givenAnIssuerWithASigningKey();

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenIssuedTokenClaimIsAUniversallyUniqueIdentifier("jti");
    }

    @Test
    public void twoTokensIssuedFromTheSameRequestCarryDifferentTokenIdentifiers() throws TestCAException {
        givenAnIssuerWithASigningKey();

        whenTheSameRequestIsIssuedTwice();

        thenBothTokensCarryATokenIdentifier();
        thenTheTwoTokenIdentifiersDiffer();
    }

    private void givenAnIssuerWithASigningKey() throws TestCAException {
        givenKeystorePrivateKeyEntry(SIGNING_ALIAS, 0);
        givenTheIssuerIsBoundToTheKeystore();
        givenTheIssuerIsActivatedWith(IssuingConfig.defaults().withSigningKeyAlias(SIGNING_ALIAS));
    }

    private void whenTheSameRequestIsIssuedTwice() {
        final TokenIssueRequest request = TokenIssueRequest.builder(TEST_IDENTITY).build();

        whenATokenIsIssued(request);
        this.firstTokenId = tokenIdOfIssuedToken();

        whenATokenIsIssued(request);
        this.secondTokenId = tokenIdOfIssuedToken();
    }

    private void thenBothTokensCarryATokenIdentifier() {
        assertNotNull(this.firstTokenId, "the first token carries no jti claim");
        assertNotNull(this.secondTokenId, "the second token carries no jti claim");
    }

    private void thenTheTwoTokenIdentifiersDiffer() {
        assertNotEquals(this.firstTokenId, this.secondTokenId, "two issued tokens share the same jti claim");
    }

    private String tokenIdOfIssuedToken() {
        thenATokenIsIssued();

        return TokenInspector.of(issuedToken()).claim("jti").map(claim -> claim.getAsString()).orElse(null);
    }

}
