/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.rest.provider.test;

import static org.junit.jupiter.api.Assertions.*;
import java.net.http.HttpResponse;
import java.util.List;
import java.util.Map;
import com.eclipsesource.json.Json;
import com.eclipsesource.json.JsonObject;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.rest.provider.test.util.AbstractJwtRestScenario;
import org.junit.jupiter.api.Test;

class PasswordChangeSessionTest extends AbstractJwtRestScenario {
    @Test
    void shouldAllowResourceAccessAfterPasswordChangeWithoutRelogin() throws Exception {
        changePasswordAndCheckSession("baz");
    }

    @Test
    void passwordMatchingAnotherIdentityMustNotChangeSessionIdentity() throws Exception {
        identities().create("other.admin", "different-password", List.of("kura.admin"));
        changePasswordAndCheckSession("other.admin");
    }

    private void changePasswordAndCheckSession(String newPassword) throws Exception {
        identities().passwordStrength.updated(Map.of("new.password.min.length", 1));
        identities().create("foo", "bar", List.of("rest.assets"));
        identities().requirePasswordChange("foo");
        HttpResponse<String> login = sendRequest("POST", "session/v1/login/password",
                Map.of("Content-Type", "application/json"), "{\"username\":\"foo\",\"password\":\"bar\"}");
        assertEquals(200, login.statusCode(), login.body());
        assertTrue(Json.parse(login.body()).asObject().get("passwordChangeNeeded").asBoolean());
        String xsrf = xsrfToken();
        assertEquals(401, sendRequest("GET", "jwttest/assets", Map.of("X-XSRF-Token", xsrf), null).statusCode());

        HttpResponse<String> changed = sendRequest("POST", "session/v1/changePassword",
                Map.of("Content-Type", "application/json", "X-XSRF-Token", xsrf),
                new JsonObject().add("currentPassword", "bar").add("newPassword", newPassword).toString());
        assertEquals(204, changed.statusCode(), changed.body());
        identities().service.checkPassword("foo", newPassword.toCharArray());
        assertThrows(KuraException.class, () -> identities().service.checkPassword("foo", "bar".toCharArray()));

        String refreshedXsrf = xsrfToken();
        HttpResponse<String> identity = sendRequest("GET", "session/v1/currentIdentity",
                Map.of("X-XSRF-Token", refreshedXsrf), null);
        assertEquals(200, identity.statusCode(), identity.body());
        JsonObject current = Json.parse(identity.body()).asObject();
        assertEquals("foo", current.get("name").asString());
        assertFalse(current.get("passwordChangeNeeded").asBoolean());
        assertEquals(List.of("rest.assets"), current.get("permissions").asArray().values().stream()
                .map(value -> value.asString()).toList());
        HttpResponse<String> resource = sendRequest("GET", "jwttest/assets",
                Map.of("X-XSRF-Token", refreshedXsrf), null);
        assertEquals(200, resource.statusCode(), resource.body());
        assertEquals("ok", resource.body());
    }

    private String xsrfToken() {
        HttpResponse<String> response = sendRequest("GET", "session/v1/xsrfToken", Map.of(), null);
        assertEquals(200, response.statusCode(), response.body());
        return Json.parse(response.body()).asObject().get("xsrfToken").asString();
    }
}
