/*******************************************************************************
 * Copyright (c) 2022, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.rest.provider.test;

import static org.junit.jupiter.api.Assertions.*;
import java.net.*;
import java.net.http.*;
import java.nio.charset.StandardCharsets;
import java.security.Principal;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;
import org.eclipse.kura.audit.AuditContext;
import org.eclipse.kura.identity.IdentityConfiguration;
import org.eclipse.kura.identity.PasswordConfiguration;
import org.eclipse.kura.rest.auth.AuthenticationProvider;
import org.eclipse.kura.rest.provider.test.util.AbstractJwtRestScenario;
import org.eclipse.kura.rest.provider.test.util.RestTlsFixture;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import com.eclipsesource.json.Json;
import com.eclipsesource.json.JsonObject;
import com.google.gson.JsonParser;
import jakarta.annotation.Priority;
import jakarta.annotation.security.RolesAllowed;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.container.ContainerRequestContext;
import jakarta.ws.rs.core.Context;

public class RestServiceTest extends AbstractJwtRestScenario {
    private static final String LOGIN_BANNER_SERVICE_PID = "org.eclipse.kura.identity.LoginBannerService";
    private static final String PASSWORD_STRENGTH_VERIFICATION_SERVICE_PID = "org.eclipse.kura.identity.PasswordStrengthVerificationService";
    @Test
    public void shouldReturnNotFoundIfNoServiceIsRegistered() throws Exception {

        whenRequestIsPerformed(new MethodSpec("GET"), "/foo");

        thenResponseCodeIs(404);
    }

    @Test
    public void shouldNotRequireAuth() throws Exception {
        givenService(new NoAuth());
        givenNoBasicCredentials();

        whenRequestIsPerformed(new MethodSpec("GET"), "/noAuth");

        thenResponseCodeIs(200);
    }

    @Test
    public void shouldRerturn403IfUserIsNotInRole() throws Exception {
        givenService(new RequiresAssetsRole());
        givenIdentity("fooo", Optional.of("barr"), Collections.emptyList());
        givenBasicCredentials(Optional.of("fooo:barr"));

        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");

        thenResponseCodeIs(403);
    }

    @Test
    public void shouldRerturn401IfPasswordIsWrong() throws Exception {
        givenService(new RequiresAssetsRole());
        givenIdentity("foo", Optional.of("bar"), Collections.emptyList());
        givenBasicCredentials(Optional.of("foo:baz"));

        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");

        thenResponseCodeIs(401);
    }

    @Test
    public void shouldAllowAccessIfUserIsInRole() throws Exception {
        givenService(new RequiresAssetsRole());
        givenIdentity("foo1", Optional.of("bar1"), Collections.singletonList("rest.assets"));
        givenBasicCredentials(Optional.of("foo1:bar1"));

        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");

        thenResponseCodeIs(200);
    }

    @Test
    public void shouldRerturn401IfNoCredentialsAreProvided() throws Exception {
        givenService(new RequiresAssetsRole());
        givenIdentity("foo", Optional.of("bar"), Collections.emptyList());
        givenNoBasicCredentials();

        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");

        thenResponseCodeIs(401);
    }

    @Test
    public void shouldEnableAuthenticationProvider() throws Exception {

        whenAuthenticationProviderIsRegistered(new DummyAuthenticationProvider("foo", "bar", "admin"));

        thenProviderIsEnabled();
    }

    @Test
    public void shouldDisableAuthenticationProvider() throws Exception {

        givenAuthenticationProvider(new DummyAuthenticationProvider("foo", "bar", "admin"));

        whenLastRegisteredServiceIsUnregistered();

        thenProviderIsDisabled();
    }

    @Test
    public void shouldSupportCustomAuthenticationProvider() throws Exception {
        givenService(new RequiresAssetsRole());
        givenAuthenticationProvider(new DummyAuthenticationProvider("bar", "baz", "admin"));
        givenBasicCredentials(Optional.of("bar:baz"));

        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");

        thenProviderAuthenticatedRequest();
        thenResponseCodeIs(200);
    }

    @Test
    public void shouldSupportLowPriorityAuthenticationHandler() throws Exception {
        givenService(new RequiresAssetsRole());
        givenAuthenticationProvider(new LowPriorityAuthenticationProvider("foo", "bar", "admin"));
        givenBasicCredentials(Optional.of("foo:bar"));
        givenIdentity("foo", Optional.of("bar"), Collections.singletonList("rest.assets"));

        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");

        thenProviderDidNotAuthenticateRequest();
        thenResponseCodeIs(200);
    }

    @Test
    public void shouldSupportHighPriorityAuthenticationHandler() throws Exception {
        givenService(new RequiresAssetsRole());
        givenAuthenticationProvider(new HighPriorityAuthenticationProvider("foo", "bar", "admin"));
        givenBasicCredentials(Optional.of("foo:bar"));
        givenIdentity("foo", Optional.of("bar"), Collections.singletonList("rest.assets"));

        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");

        thenProviderAuthenticatedRequest();
        thenResponseCodeIs(200);
    }

    @Test
    public void shouldSupportDisablingBuiltInPasswordAuthentication() throws Exception {
        givenRestServiceConfiguration(Collections.singletonMap("auth.password.enabled", false));
        givenService(new RequiresAssetsRole());
        givenIdentity("foo1", Optional.of("bar1"), Collections.singletonList("rest.assets"));
        givenBasicCredentials(Optional.of("foo1:bar1"));

        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");

        thenResponseCodeIs(401);
    }

    @Test
    public void shouldSupportCertificateAuthenticationOnResourcePath() throws Exception {
        givenRestServiceConfiguration(Collections.singletonMap("allowed.ports", new Integer[] { 8080, 9999 }));
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.empty(), Arrays.asList("rest.assets"));
        givenService(new RequiresAssetsRole());
        givenCA("clientCA");
        givenCA("serverCA");
        givenKeystoreService("clientKeystore");
        givenCACertificateInKeystore("clientKeystore", "serverCA");
        givenKeystoreService("serverKeystore");
        givenCACertificateInKeystore("serverKeystore", "clientCA");
        givenKeyPairInKeystore("clientKeystore", "clientCA", "foo");
        givenKeyPairInKeystore("serverKeystore", "serverCA", "serverCert");
        givenHttpServiceClientCertAuthEnabled("serverKeystore", 9999);
        givenClientKeystore("clientKeystore");

        whenRequestIsPerformed("https", 9999, new MethodSpec("GET"), "/testservice/requireAssets", null);

        thenResponseCodeIs(200);
    }

    @Test
    public void shouldRejectRequestIfCertCommonNameDoesNotMatchIdentity() throws Exception {
        givenRestServiceConfiguration(Collections.singletonMap("allowed.ports", new Integer[] { 8080, 9999 }));
        givenNoBasicCredentials();
        givenService(new RequiresAssetsRole());
        givenCA("clientCA");
        givenCA("serverCA");
        givenKeystoreService("clientKeystore");
        givenCACertificateInKeystore("clientKeystore", "serverCA");
        givenKeystoreService("serverKeystore");
        givenCACertificateInKeystore("serverKeystore", "clientCA");
        givenKeyPairInKeystore("clientKeystore", "clientCA", "doesNotExist");
        givenKeyPairInKeystore("serverKeystore", "serverCA", "serverCert");
        givenHttpServiceClientCertAuthEnabled("serverKeystore", 9999);
        givenClientKeystore("clientKeystore");

        whenRequestIsPerformed("https", 9999, new MethodSpec("GET"), "/testservice/requireAssets", null);

        thenResponseCodeIs(401);
    }

    @Test
    public void shouldCreateSessionWithUsernameAndPassword() throws Exception {
        givenConfiguration(LOGIN_BANNER_SERVICE_PID, //
                "pre.login.banner.enabled", false, //
                "post.login.banner.enabled", false);
        givenService(new RequiresAssetsRole());
        givenIdentity("foo", Optional.of("bar"), Collections.emptyList());
        givenNoBasicCredentials();

        whenRequestIsPerformed("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");

        thenResponseCodeIs(200);
        thenResponseBodyEqualsJson("{\"passwordChangeNeeded\":false}");
        thenResponseHasCookie("JSESSIONID");
    }

    @Test
    public void shouldNotCreateSessionWithWrongPassword() throws Exception {
        givenService(new RequiresAssetsRole());
        givenIdentity("foo", Optional.of("bar"), Collections.emptyList());
        givenNoBasicCredentials();

        whenRequestIsPerformed("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"baz\"}");

        thenResponseCodeIs(401);
        thenResponseDoesNotHaveCookie("JSESSIONID");
    }

    @Test
    public void shouldNotCreateSessionWithWrongUsername() throws Exception {
        givenService(new RequiresAssetsRole());
        givenIdentity("foo", Optional.of("bar"), Collections.emptyList());
        givenNoBasicCredentials();

        whenRequestIsPerformed("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"bar\",\"password\":\"bar\"}");

        thenResponseCodeIs(401);
        thenResponseDoesNotHaveCookie("JSESSIONID");
    }

    @Test
    public void shouldCreateSessionWithCertificate() throws Exception {
        givenRestServiceConfiguration(Collections.singletonMap("allowed.ports", new Integer[] { 8080, 9999 }));
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.empty(), Arrays.asList("rest.assets"));
        givenService(new RequiresAssetsRole());
        givenCA("clientCA");
        givenCA("serverCA");
        givenKeystoreService("clientKeystore");
        givenCACertificateInKeystore("clientKeystore", "serverCA");
        givenKeystoreService("serverKeystore");
        givenCACertificateInKeystore("serverKeystore", "clientCA");
        givenKeyPairInKeystore("clientKeystore", "clientCA", "foo");
        givenKeyPairInKeystore("serverKeystore", "serverCA", "serverCert");
        givenHttpServiceClientCertAuthEnabled("serverKeystore", 9999);
        givenClientKeystore("clientKeystore");

        whenRequestIsPerformed("https", 9999, new MethodSpec("POST"), "/session/v1/login/certificate", null);

        thenRequestSucceeds();
        thenResponseHasCookie("JSESSIONID");
    }

    @Test
    public void shouldCreateSessionWithCertificateAndReturnPostLoginMessage() throws Exception {
        givenRestServiceConfiguration(Collections.singletonMap("allowed.ports", new Integer[] { 8080, 9999 }));
        givenConfiguration(LOGIN_BANNER_SERVICE_PID, //
                "post.login.banner.enabled", true, //
                "post.login.banner.content", "foo");
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.empty(), Arrays.asList("rest.assets"));
        givenService(new RequiresAssetsRole());
        givenCA("clientCA");
        givenCA("serverCA");
        givenKeystoreService("clientKeystore");
        givenCACertificateInKeystore("clientKeystore", "serverCA");
        givenKeystoreService("serverKeystore");
        givenCACertificateInKeystore("serverKeystore", "clientCA");
        givenKeyPairInKeystore("clientKeystore", "clientCA", "foo");
        givenKeyPairInKeystore("serverKeystore", "serverCA", "serverCert");
        givenHttpServiceClientCertAuthEnabled("serverKeystore", 9999);
        givenClientKeystore("clientKeystore");

        whenRequestIsPerformed("https", 9999, new MethodSpec("POST"), "/session/v1/login/certificate", null);

        thenRequestSucceeds();
        thenResponseHasCookie("JSESSIONID");
        thenResponseBodyEqualsJson("{\"passwordChangeNeeded\":false,\"message\":\"foo\"}");
    }

    @Test
    public void shouldNotCreateSessionWithCertificateIfCNDoesNotMatchIdentity() throws Exception {
        givenRestServiceConfiguration(Collections.singletonMap("allowed.ports", new Integer[] { 8080, 9999 }));
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.empty(), Arrays.asList("rest.assets"));
        givenService(new RequiresAssetsRole());
        givenCA("clientCA");
        givenCA("serverCA");
        givenKeystoreService("clientKeystore");
        givenCACertificateInKeystore("clientKeystore", "serverCA");
        givenKeystoreService("serverKeystore");
        givenCACertificateInKeystore("serverKeystore", "clientCA");
        givenKeyPairInKeystore("clientKeystore", "clientCA", "bar");
        givenKeyPairInKeystore("serverKeystore", "serverCA", "serverCert");
        givenHttpServiceClientCertAuthEnabled("serverKeystore", 9999);
        givenClientKeystore("clientKeystore");

        whenRequestIsPerformed("https", 9999, new MethodSpec("POST"), "/session/v1/login/certificate", null);

        thenResponseCodeIs(401);
        thenResponseDoesNotHaveCookie("JSESSIONID");
    }

    @Test
    public void shouldReturnXSRFTokenIfSessionIsOpen() throws Exception {
        givenIdentity("foo", Optional.of("bar"), Collections.emptyList());
        givenNoBasicCredentials();

        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        whenRequestIsPerformed("http", 8080, new MethodSpec("GET"), "/session/v1/xsrfToken", null);

        thenResponseCodeIs(200);
    }

    @Test
    public void shouldNotReturnXSRFTokenIfSessionIsNotOpen() throws Exception {
        givenIdentity("foo", Optional.of("bar"), Collections.emptyList());
        givenNoBasicCredentials();

        whenRequestIsPerformed("http", 8080, new MethodSpec("GET"), "/session/v1/xsrfToken", null);

        thenResponseCodeIs(401);
    }

    @Test
    public void shouldAllowAccessingResourceThroughSessionAuth() throws Exception {
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"));
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenXsrfToken();

        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");

        thenResponseCodeIs(200);
    }

    @Test
    public void shouldNotAllowAccessingResourceThroughSessionAuthIfXsrfTokenIsMissing() throws Exception {
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"));
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");

        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");

        thenResponseCodeIs(401);
    }

    @Test
    public void shouldNotAllowAccessingResourceThroughSessionAuthIfXsrfTokenIsWrong() throws Exception {
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"));
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenXsrfTokenHeader("not-the-session-token");

        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");

        thenResponseCodeIs(401);
    }

    @Test
    public void shouldSupportLogout() throws Exception {
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"));
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenXsrfToken();
        givenSuccessfulRequest(new MethodSpec("GET"), "/requireAssets");
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/logout", null);

        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");

        thenResponseCodeIs(401);
    }

    @Test
    public void shouldRequireXsrfTokenForLogout() throws Exception {
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"));
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        whenRequestIsPerformed("http", 8080, new MethodSpec("POST"), "/session/v1/logout", null);

        thenResponseCodeIs(401);
    }

    @Test
    public void shouldDenyResourceAccessIfPasswordChangeIsNeeded() throws Exception {
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"), true);
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenXsrfToken();

        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");

        thenResponseCodeIs(401);
    }

    @Test
    public void shouldRejectPassordChangeWithSamePassword() throws Exception {
        givenConfiguration(PASSWORD_STRENGTH_VERIFICATION_SERVICE_PID, //
                "new.password.min.length", 1, //
                "new.password.require.digits", false, //
                "new.password.require.special.characters", false, //
                "new.password.require.both.cases", false //
        );
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"), true);
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenXsrfToken();

        whenRequestIsPerformed("http", 8080, new MethodSpec("POST"), "/session/v1/changePassword",
                "{\"currentPassword\":\"bar\",\"newPassword\":\"bar\"}");

        thenResponseCodeIs(400);
    }

    @Test
    public void shouldAllowResourceAccessAfterPasswordChange() throws Exception {
        givenConfiguration(PASSWORD_STRENGTH_VERIFICATION_SERVICE_PID, //
                "new.password.min.length", 1, //
                "new.password.require.digits", false, //
                "new.password.require.special.characters", false, //
                "new.password.require.both.cases", false //
        );
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"), true);
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenXsrfToken();
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/changePassword",
                "{\"currentPassword\":\"bar\",\"newPassword\":\"baz\"}");
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"baz\"}");
        givenXsrfToken();

        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");

        thenResponseCodeIs(200);
    }

    @Test
    public void shouldSupportSessionExpiration() throws Exception {
        givenRestServiceConfiguration(Collections.singletonMap("session.inactivity.interval", 1));
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"));
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenXsrfToken();
        givenSuccessfulRequest(new MethodSpec("GET"), "/requireAssets");
        givenDelay(2, TimeUnit.SECONDS);

        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");

        thenResponseCodeIs(401);
    }

    @Test
    public void shouldNotAllowGettingXsrfTokenIfSessionIsExpired() throws Exception {
        givenRestServiceConfiguration(Collections.singletonMap("session.inactivity.interval", 1));
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"));
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenXsrfToken();
        givenSuccessfulRequest(new MethodSpec("GET"), "/requireAssets");
        givenDelay(2, TimeUnit.SECONDS);

        whenRequestIsPerformed("http", 8080, new MethodSpec("GET"), "/session/v1/xsrfToken", null);

        thenResponseCodeIs(401);
    }

    @Test
    public void shouldExtendSessionLifetimeOnActivity() throws Exception {
        givenRestServiceConfiguration(Collections.singletonMap("session.inactivity.interval", 1));
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"));
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenXsrfToken();
        givenSuccessfulRequest(new MethodSpec("GET"), "/requireAssets");
        givenDelay(500, TimeUnit.MILLISECONDS);
        givenSuccessfulRequest(new MethodSpec("GET"), "/requireAssets");
        givenDelay(500, TimeUnit.MILLISECONDS);
        givenSuccessfulRequest(new MethodSpec("GET"), "/requireAssets");
        givenDelay(500, TimeUnit.MILLISECONDS);
        givenSuccessfulRequest(new MethodSpec("GET"), "/requireAssets");
        givenDelay(2, TimeUnit.SECONDS);

        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");

        thenResponseCodeIs(401);
    }

    @Test
    public void shouldIgnorePasswordChangeNeededWithCertificateAuth() throws Exception {
        givenRestServiceConfiguration(Collections.singletonMap("allowed.ports", new Integer[] { 8080, 9999 }));
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"), true);
        givenService(new RequiresAssetsRole());
        givenCA("clientCA");
        givenCA("serverCA");
        givenKeystoreService("clientKeystore");
        givenCACertificateInKeystore("clientKeystore", "serverCA");
        givenKeystoreService("serverKeystore");
        givenCACertificateInKeystore("serverKeystore", "clientCA");
        givenKeyPairInKeystore("clientKeystore", "clientCA", "foo");
        givenKeyPairInKeystore("serverKeystore", "serverCA", "serverCert");
        givenHttpServiceClientCertAuthEnabled("serverKeystore", 9999);
        givenClientKeystore("clientKeystore");

        givenSuccessfulRequest("https", 9999, new MethodSpec("POST"), "/session/v1/login/certificate", null);
        givenXsrfToken("https", 9999);

        whenRequestIsPerformed("https", 9999, new MethodSpec("GET"), "/testservice/requireAssets", null);

        thenResponseCodeIs(200);
    }

    @Test
    public void shouldSupportDisablingBuiltInBasicAuthentication() throws Exception {
        givenRestServiceConfiguration(Collections.singletonMap("auth.basic.enabled", false));
        givenService(new RequiresAssetsRole());
        givenIdentity("foo1", Optional.of("bar1"), Collections.singletonList("rest.assets"));
        givenBasicCredentials(Optional.of("foo1:bar1"));

        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");

        thenResponseCodeIs(401);
    }

    @Test
    public void shouldSupportDisablingCertificateAuthenticationOnResourcePath() throws Exception {
        givenRestServiceConfiguration(map("allowed.ports", new Integer[] { 8080, 9999 }, //
                "auth.certificate.stateless.enabled", false));
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.empty(), Arrays.asList("rest.assets"));
        givenService(new RequiresAssetsRole());
        givenCA("clientCA");
        givenCA("serverCA");
        givenKeystoreService("clientKeystore");
        givenCACertificateInKeystore("clientKeystore", "serverCA");
        givenKeystoreService("serverKeystore");
        givenCACertificateInKeystore("serverKeystore", "clientCA");
        givenKeyPairInKeystore("clientKeystore", "clientCA", "foo");
        givenKeyPairInKeystore("serverKeystore", "serverCA", "serverCert");
        givenHttpServiceClientCertAuthEnabled("serverKeystore", 9999);
        givenClientKeystore("clientKeystore");

        whenRequestIsPerformed("https", 9999, new MethodSpec("GET"), "/testservice/requireAssets", null);

        thenResponseCodeIs(401);
    }

    @Test
    public void shouldAllowAccessingResourceThroughSessionAuthEvenIfBasicAuthIsDisabled() throws Exception {
        givenRestServiceConfiguration(Collections.singletonMap("auth.basic.enabled", false));
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"));
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenXsrfToken();

        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");

        thenResponseCodeIs(200);
    }

    @Test
    public void shouldAllowAccessingResourceThroughSessionAuthEvenIfLegacyCertificateAuthIsDisabled() throws Exception {
        givenRestServiceConfiguration(map("allowed.ports", new Integer[] { 8080, 9999 }, //
                "auth.certificate.stateless.enabled", false));
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"), true);
        givenService(new RequiresAssetsRole());
        givenCA("clientCA");
        givenCA("serverCA");
        givenKeystoreService("clientKeystore");
        givenCACertificateInKeystore("clientKeystore", "serverCA");
        givenKeystoreService("serverKeystore");
        givenCACertificateInKeystore("serverKeystore", "clientCA");
        givenKeyPairInKeystore("clientKeystore", "clientCA", "foo");
        givenKeyPairInKeystore("serverKeystore", "serverCA", "serverCert");
        givenHttpServiceClientCertAuthEnabled("serverKeystore", 9999);
        givenClientKeystore("clientKeystore");

        givenSuccessfulRequest("https", 9999, new MethodSpec("POST"), "/session/v1/login/certificate", null);
        givenXsrfToken("https", 9999);

        whenRequestIsPerformed("https", 9999, new MethodSpec("GET"), "/testservice/requireAssets", null);

        thenResponseCodeIs(200);
    }

    @Test
    public void shouldTerminateSessionIfUserCredentialsChange() throws Exception {
        givenRestServiceConfiguration(Collections.singletonMap("auth.basic.enabled", false));
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"));
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenXsrfToken();
        givenSuccessfulRequest(new MethodSpec("GET"), "/requireAssets");

        whenIdentityIsUpdated("foo", Optional.of("baz"), Arrays.asList("rest.assets"));
        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");

        thenResponseCodeIs(401);
    }

    @Test
    public void shouldRejectPassordChangeWithTooShort() throws Exception {
        givenConfiguration(PASSWORD_STRENGTH_VERIFICATION_SERVICE_PID, //
                "new.password.min.length", 4, //
                "new.password.require.digits", false, //
                "new.password.require.special.characters", false, //
                "new.password.require.both.cases", false //
        );
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"), true);
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenXsrfToken();

        whenRequestIsPerformed("http", 8080, new MethodSpec("POST"), "/session/v1/changePassword",
                "{\"currentPassword\":\"bar\",\"newPassword\":\"baz\"}");

        thenResponseCodeIs(400);
    }

    @Test
    public void shouldRejectPassordChangeWithoutDigits() throws Exception {
        givenConfiguration(PASSWORD_STRENGTH_VERIFICATION_SERVICE_PID, //
                "new.password.min.length", 4, //
                "new.password.require.digits", true, //
                "new.password.require.special.characters", false, //
                "new.password.require.both.cases", false //
        );
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"), true);
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenXsrfToken();

        whenRequestIsPerformed("http", 8080, new MethodSpec("POST"), "/session/v1/changePassword",
                "{\"currentPassword\":\"bar\",\"newPassword\":\"nodigits\"}");

        thenResponseCodeIs(400);
    }

    @Test
    public void shouldRejectPassordChangeWithoutSpecialCharacters() throws Exception {
        givenConfiguration(PASSWORD_STRENGTH_VERIFICATION_SERVICE_PID, //
                "new.password.min.length", 4, //
                "new.password.require.digits", true, //
                "new.password.require.special.characters", true, //
                "new.password.require.both.cases", false //
        );
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"), true);
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenXsrfToken();

        whenRequestIsPerformed("http", 8080, new MethodSpec("POST"), "/session/v1/changePassword",
                "{\"currentPassword\":\"bar\",\"newPassword\":\"nospecialcharacters1\"}");

        thenResponseCodeIs(400);
    }

    @Test
    public void shouldRejectPassordChangeWithoutBothCases() throws Exception {
        givenConfiguration(PASSWORD_STRENGTH_VERIFICATION_SERVICE_PID, //
                "new.password.min.length", 4, //
                "new.password.require.digits", true, //
                "new.password.require.special.characters", true, //
                "new.password.require.both.cases", true //
        );
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"), true);
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenXsrfToken();

        whenRequestIsPerformed("http", 8080, new MethodSpec("POST"), "/session/v1/changePassword",
                "{\"currentPassword\":\"bar\",\"newPassword\":\"nobothcases1@\"}");

        thenResponseCodeIs(400);
    }

    @Test
    public void shouldAcceptPasswordThatFullfillsRequirements() throws Exception {
        givenConfiguration(PASSWORD_STRENGTH_VERIFICATION_SERVICE_PID, //
                "new.password.min.length", 4, //
                "new.password.require.digits", true, //
                "new.password.require.special.characters", true, //
                "new.password.require.both.cases", true //
        );
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"), true);
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenXsrfToken();

        whenRequestIsPerformed("http", 8080, new MethodSpec("POST"), "/session/v1/changePassword",
                "{\"currentPassword\":\"bar\",\"newPassword\":\"1validPW@\"}");

        thenRequestSucceeds();
    }

    @Test
    public void shouldReturnCurrentIdentityInfo() throws Exception {
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets", "rest.foo", "rest.bar"), false);
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenXsrfToken();

        whenRequestIsPerformed("http", 8080, new MethodSpec("GET"), "/session/v1/currentIdentity", null);

        thenRequestSucceeds();
        thenResponseBodyEqualsJson(
                "{\"name\":\"foo\",\"passwordChangeNeeded\":false,\"permissions\":[\"rest.bar\",\"rest.assets\",\"rest.foo\"]}");
    }

    @Test
    public void shouldReturnCurrentIdentityInfoWithNoPermissions() throws Exception {
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();
        givenIdentity("nopermissions", Optional.of("bar"), Collections.emptyList(), false);
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"nopermissions\",\"password\":\"bar\"}");
        givenXsrfToken();

        whenRequestIsPerformed("http", 8080, new MethodSpec("GET"), "/session/v1/currentIdentity", null);

        thenRequestSucceeds();
        thenResponseBodyEqualsJson("{\"name\":\"nopermissions\",\"passwordChangeNeeded\":false,\"permissions\":[]}");
    }

    @Test
    public void shouldReturnCurrentAuthenticationMethodInfo() throws Exception {
        givenHttpServiceClientCertAuthDisabled();
        givenService(new RequiresAssetsRole());
        givenNoBasicCredentials();

        whenRequestIsPerformed("http", 8080, new MethodSpec("GET"), "/session/v1/authenticationInfo", null);

        thenRequestSucceeds();
        thenResponseBodyEqualsJson(
                "{\"passwordAuthenticationEnabled\":true,\"certificateAuthenticationEnabled\":false}");
    }

    @Test
    public void shouldReturnMessageIfLoginBannnerIsEnabled() throws Exception {
        givenHttpServiceClientCertAuthDisabled();
        givenConfiguration(LOGIN_BANNER_SERVICE_PID, //
                "pre.login.banner.enabled", true, //
                "pre.login.banner.content", "foo");
        givenNoBasicCredentials();

        whenRequestIsPerformed("http", 8080, new MethodSpec("GET"), "/session/v1/authenticationInfo", null);

        thenResponseCodeIs(200);
        thenResponseBodyEqualsJson(
                "{\"passwordAuthenticationEnabled\":true,\"certificateAuthenticationEnabled\":false,\"message\":\"foo\"}");
    }

    @Test
    public void shouldReturnPostLoginMessageIfLoginBannnerIsEnabled() throws Exception {
        givenHttpServiceClientCertAuthDisabled();
        givenConfiguration(LOGIN_BANNER_SERVICE_PID, //
                "post.login.banner.enabled", true, //
                "post.login.banner.content", "foo");
        givenService(new RequiresAssetsRole());
        givenIdentity("foo", Optional.of("bar"), Collections.emptyList());
        givenNoBasicCredentials();
        whenRequestIsPerformed("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        thenRequestSucceeds();

        thenResponseBodyEqualsJson("{\"passwordChangeNeeded\":false,\"message\":\"foo\"}");
    }

    @Test
    public void shouldChangeSessionCookieRepeatingPasswordAuthentication() throws Exception {
        givenConfiguration(LOGIN_BANNER_SERVICE_PID, //
                "pre.login.banner.enabled", false, //
                "post.login.banner.enabled", false);
        givenService(new RequiresAssetsRole());
        givenIdentity("foo", Optional.of("bar"), Collections.emptyList());
        givenNoBasicCredentials();

        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenSnapshotOfCurrentCookies();
        givenCookieInSnapshot("JSESSIONID");

        whenRequestIsPerformed("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");

        thenResponseCodeIs(200);
        thenResponseBodyEqualsJson("{\"passwordChangeNeeded\":false}");
        thenCurrentCookieDiffersFromPreviousSnapshot("JSESSIONID");
    }

    @Test
    public void shouldChangeSessionCookieAfterPasswordChange() throws Exception {
        givenConfiguration(LOGIN_BANNER_SERVICE_PID, //
                "pre.login.banner.enabled", false);
        givenConfiguration(PASSWORD_STRENGTH_VERIFICATION_SERVICE_PID, //
                "new.password.min.length", 1, //
                "new.password.require.digits", false, //
                "new.password.require.special.characters", false, //
                "new.password.require.both.cases", false);
        givenService(new RequiresAssetsRole());
        givenIdentity("foo", Optional.of("bar"), Collections.emptyList(), true);
        givenNoBasicCredentials();

        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenSnapshotOfCurrentCookies();
        givenCookieInSnapshot("JSESSIONID");

        givenXsrfToken("http", 8080);

        whenRequestIsPerformed("http", 8080, new MethodSpec("POST"), "/session/v1/changePassword",
                "{\"currentPassword\":\"bar\",\"newPassword\":\"baz\"}");

        thenRequestSucceeds();
        thenCurrentCookieDiffersFromPreviousSnapshot("JSESSIONID");
    }

    @Test
    public void shouldChangeSessionCookieRepeatingCertificateAuthentication() throws Exception {
        givenRestServiceConfiguration(Collections.singletonMap("allowed.ports", new Integer[] { 8080, 9999 }));
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.empty(), Arrays.asList("rest.assets"));
        givenService(new RequiresAssetsRole());
        givenCA("clientCA");
        givenCA("serverCA");
        givenKeystoreService("clientKeystore");
        givenCACertificateInKeystore("clientKeystore", "serverCA");
        givenKeystoreService("serverKeystore");
        givenCACertificateInKeystore("serverKeystore", "clientCA");
        givenKeyPairInKeystore("clientKeystore", "clientCA", "foo");
        givenKeyPairInKeystore("serverKeystore", "serverCA", "serverCert");
        givenHttpServiceClientCertAuthEnabled("serverKeystore", 9999);
        givenClientKeystore("clientKeystore");

        givenSuccessfulRequest("https", 9999, new MethodSpec("POST"), "/session/v1/login/certificate", null);
        givenSnapshotOfCurrentCookies();
        givenCookieInSnapshot("JSESSIONID");

        whenRequestIsPerformed("https", 9999, new MethodSpec("POST"), "/session/v1/login/certificate", null);

        thenRequestSucceeds();
        thenCurrentCookieDiffersFromPreviousSnapshot("JSESSIONID");
    }

    @Test
    public void shouldChangeSessionCookieAuthenticatingWithPasswordAndThenWithCertificateOnDifferentPort() throws Exception {
        givenRestServiceConfiguration(Collections.singletonMap("allowed.ports", new Integer[] { 8080, 9999 }));
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"));
        givenService(new RequiresAssetsRole());
        givenCA("clientCA");
        givenCA("serverCA");
        givenKeystoreService("clientKeystore");
        givenCACertificateInKeystore("clientKeystore", "serverCA");
        givenKeystoreService("serverKeystore");
        givenCACertificateInKeystore("serverKeystore", "clientCA");
        givenKeyPairInKeystore("clientKeystore", "clientCA", "foo");
        givenKeyPairInKeystore("serverKeystore", "serverCA", "serverCert");
        givenHttpServiceClientCertAuthEnabled("serverKeystore", 9999);
        givenClientKeystore("clientKeystore");

        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenSnapshotOfCurrentCookies();
        givenCookieInSnapshot("JSESSIONID");

        whenRequestIsPerformed("https", 9999, new MethodSpec("POST"), "/session/v1/login/certificate", null);

        thenRequestSucceeds();
        thenCurrentCookieDiffersFromPreviousSnapshot("JSESSIONID");
    }

    @Test
    public void shouldChangeSessionCookieAuthenticatingWithCertificateAndThenWithPasswordOnDifferentPort() throws Exception {
        givenRestServiceConfiguration(Collections.singletonMap("allowed.ports", new Integer[] { 8080, 9999 }));
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"));
        givenService(new RequiresAssetsRole());
        givenCA("clientCA");
        givenCA("serverCA");
        givenKeystoreService("clientKeystore");
        givenCACertificateInKeystore("clientKeystore", "serverCA");
        givenKeystoreService("serverKeystore");
        givenCACertificateInKeystore("serverKeystore", "clientCA");
        givenKeyPairInKeystore("clientKeystore", "clientCA", "foo");
        givenKeyPairInKeystore("serverKeystore", "serverCA", "serverCert");
        givenHttpServiceClientCertAuthEnabled("serverKeystore", 9999);
        givenClientKeystore("clientKeystore");

        givenSuccessfulRequest("https", 9999, new MethodSpec("POST"), "/session/v1/login/certificate", null);
        givenSnapshotOfCurrentCookies();
        givenCookieInSnapshot("JSESSIONID");

        whenRequestIsPerformed("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        thenRequestSucceeds();
        thenCurrentCookieDiffersFromPreviousSnapshot("JSESSIONID");
    }

    @Test
    public void shouldChangeSessionCookieAuthenticatingWithPasswordAndThenWithCertificateOnSamePort() throws Exception {
        givenRestServiceConfiguration(Collections.singletonMap("allowed.ports", new Integer[] { 8080, 9999 }));
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"));
        givenService(new RequiresAssetsRole());
        givenCA("clientCA");
        givenCA("serverCA");
        givenKeystoreService("clientKeystore");
        givenCACertificateInKeystore("clientKeystore", "serverCA");
        givenKeystoreService("serverKeystore");
        givenCACertificateInKeystore("serverKeystore", "clientCA");
        givenKeyPairInKeystore("clientKeystore", "clientCA", "foo");
        givenKeyPairInKeystore("serverKeystore", "serverCA", "serverCert");
        givenHttpServiceClientCertAuthEnabled("serverKeystore", 9999);
        givenClientKeystore("clientKeystore");

        givenSuccessfulRequest("https", 9999, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenSnapshotOfCurrentCookies();
        givenCookieInSnapshot("JSESSIONID");

        whenRequestIsPerformed("https", 9999, new MethodSpec("POST"), "/session/v1/login/certificate", null);

        thenRequestSucceeds();
        thenCurrentCookieDiffersFromPreviousSnapshot("JSESSIONID");
    }

    @Test
    public void shouldChangeSessionCookieAuthenticatingWithCertificateAndThenWithPasswordOnSamePort() throws Exception {
        givenRestServiceConfiguration(Collections.singletonMap("allowed.ports", new Integer[] { 8080, 9999 }));
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"));
        givenService(new RequiresAssetsRole());
        givenCA("clientCA");
        givenCA("serverCA");
        givenKeystoreService("clientKeystore");
        givenCACertificateInKeystore("clientKeystore", "serverCA");
        givenKeystoreService("serverKeystore");
        givenCACertificateInKeystore("serverKeystore", "clientCA");
        givenKeyPairInKeystore("clientKeystore", "clientCA", "foo");
        givenKeyPairInKeystore("serverKeystore", "serverCA", "serverCert");
        givenHttpServiceClientCertAuthEnabled("serverKeystore", 9999);
        givenClientKeystore("clientKeystore");

        givenSuccessfulRequest("https", 9999, new MethodSpec("POST"), "/session/v1/login/certificate", null);
        givenSnapshotOfCurrentCookies();
        givenCookieInSnapshot("JSESSIONID");

        whenRequestIsPerformed("https", 9999, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        thenRequestSucceeds();
        thenCurrentCookieDiffersFromPreviousSnapshot("JSESSIONID");
    }

    @Test
    public void shouldNotLoginWithOldCookieAfterNewLogin() throws Exception {
        givenConfiguration(LOGIN_BANNER_SERVICE_PID, //
                "pre.login.banner.enabled", false);
        givenService(new RequiresAssetsRole());
        givenIdentity("foo", Optional.of("bar"), Collections.emptyList());
        givenNoBasicCredentials();

        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenSnapshotOfCurrentCookies();
        givenCookieInSnapshot("JSESSIONID");

        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");

        whenCookieIsRestoredFromSnapshot("JSESSIONID");
        whenRequestIsPerformed("http", 8080, new MethodSpec("GET"), "/session/v1/xsrfToken", null);

        thenResponseCodeIs(401);

    }

    @Test
    public void shouldInvalidateSessionAfterFailedPasswordLogin() throws Exception {
        givenConfiguration(LOGIN_BANNER_SERVICE_PID, //
                "pre.login.banner.enabled", false);
        givenService(new RequiresAssetsRole());
        givenIdentity("foo", Optional.of("bar"), Collections.emptyList());
        givenNoBasicCredentials();

        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenSnapshotOfCurrentCookies();
        givenCookieInSnapshot("JSESSIONID");

        givenXsrfToken();

        whenRequestIsPerformed("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"baz\"}");

        whenCookieIsRestoredFromSnapshot("JSESSIONID");
        whenRequestIsPerformed("http", 8080, new MethodSpec("GET"), "/session/v1/xsrfToken", null);

        thenResponseCodeIs(401);
    }

    @Test
    public void shouldInvalidateSessionAfterFailedCertificateLogin() throws Exception {
        givenRestServiceConfiguration(Collections.singletonMap("allowed.ports", new Integer[] { 8080, 9999 }));
        givenNoBasicCredentials();
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"));
        givenService(new RequiresAssetsRole());
        givenCA("clientCA");
        givenCA("serverCA");
        givenKeystoreService("clientKeystore");
        givenCACertificateInKeystore("clientKeystore", "serverCA");
        givenKeystoreService("serverKeystore");
        givenCACertificateInKeystore("serverKeystore", "clientCA");
        givenKeyPairInKeystore("clientKeystore", "clientCA", "bar");
        givenKeyPairInKeystore("serverKeystore", "serverCA", "serverCert");
        givenHttpServiceClientCertAuthEnabled("serverKeystore", 9999);
        givenClientKeystore("clientKeystore");

        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
        givenSnapshotOfCurrentCookies();
        givenCookieInSnapshot("JSESSIONID");

        givenXsrfToken();

        whenRequestIsPerformed("https", 9999, new MethodSpec("POST"), "/session/v1/login/certificate", null);

        whenCookieIsRestoredFromSnapshot("JSESSIONID");
        whenRequestIsPerformed("http", 8080, new MethodSpec("GET"), "/session/v1/xsrfToken", null);

        thenResponseCodeIs(401);
    }

    @Test
    public void auditContextIpIsNotInfluencedByXffHeader() throws Exception {
        givenService(new AuditContextCapturingService());
        givenXForwardedForHeader("6.6.6.6");

        whenRequestIsPerformed(new MethodSpec("GET"), "/auditIp");

        thenResponseCodeIs(200);
        thenAuditContextIpIsNotXffSpoofedValue("6.6.6.6");
        thenAuditContextIpIsLoopback();
    }

    @Test
    public void auditContextIpIsRemoteAddrWhenXffHeaderIsAbsent() throws Exception {
        givenService(new AuditContextCapturingService());

        whenRequestIsPerformed(new MethodSpec("GET"), "/auditIp");

        thenResponseCodeIs(200);
        thenAuditContextIpIsLoopback();
    }

    @Test
    public void shouldReturnBadRequestOnMalformedJSON() throws Exception {
        givenIdentity("foo", Optional.of("bar"), Collections.emptyList());
        givenNoBasicCredentials();

        whenRequestIsPerformed("http", 8080, new MethodSpec("POST"), "/session/v1/login/password", "}");

        thenResponseCodeIs(400);
        thenResponseBodyEqualsJson("{\"message\":\"Error parsing request body\"}");
    }

    @Test
    public void shouldReturnInternalServerErrorWithMessage() throws Exception {
        givenService(new NoAuthBroken());
        givenNoBasicCredentials();

        whenRequestIsPerformed(new MethodSpec("GET"), "/noAuth");

        thenResponseCodeIs(500);
        thenResponseBodyEqualsJson("{\"message\":\"Something went wrong\"}");
    }


    private final RestTlsFixture tls = new RestTlsFixture();
    private final Map<String, String> headers = new HashMap<>();
    private final Map<String, Object> restOptions = new HashMap<>();
    private final Map<String, Object> bannerOptions = new HashMap<>();
    private final Map<String, Object> passwordOptions = new HashMap<>(Map.of("new.password.min.length", 1));
    private final CompletableFuture<Void> providerEnabled = new CompletableFuture<>();
    private final CompletableFuture<Void> providerDisabled = new CompletableFuture<>();
    private final CompletableFuture<Void> providerAuthenticated = new CompletableFuture<>();
    private AuthenticationProvider customProvider;
    private HttpResponse<String> response;
    private Map<String, String> cookieSnapshot;
    private String httpsBaseUrl;

    @BeforeEach
    void setUpAuthentication() throws Exception {
        this.baseUrl = this.baseUrl.replace("127.0.0.1", "localhost");
        identities().passwordStrength.updated(this.passwordOptions);
        identities().create("admin", "Admin-Password-1!", List.of("kura.admin"));
    }

    private record MethodSpec(String method) { }

    private void givenNoBasicCredentials() { givenBasicCredentials(Optional.empty()); }
    private void givenBasicCredentials(Optional<String> credentials) {
        this.headers.remove("Authorization");
        credentials.ifPresent(value -> this.headers.put("Authorization", "Basic "
                + Base64.getEncoder().encodeToString(value.getBytes(StandardCharsets.UTF_8))));
    }
    private void givenRestServiceConfiguration(Map<String, Object> properties) {
        this.restOptions.putAll(properties);
        updateRestOptions();
    }
    private void updateRestOptions() {
        Map<String, Object> effective = new HashMap<>(this.restOptions);
        // Preserve the upstream two-port scenario while using private ephemeral ports.
        if (effective.containsKey("allowed.ports")) {
            List<Integer> ports = new ArrayList<>();
            ports.add(URI.create(this.baseUrl).getPort());
            if (this.httpsBaseUrl != null) { ports.add(URI.create(this.httpsBaseUrl).getPort()); }
            effective.put("allowed.ports", ports.toArray(Integer[]::new));
        }
        givenTheRestServiceProperties(effective);
    }
    private void givenConfiguration(String pid, Object... pairs) {
        Map<String, Object> properties = map(pairs);
        if (LOGIN_BANNER_SERVICE_PID.equals(pid)) {
            this.bannerOptions.putAll(properties);
            this.banner.updated(new HashMap<>(this.bannerOptions));
        } else if (PASSWORD_STRENGTH_VERIFICATION_SERVICE_PID.equals(pid)) {
            this.passwordOptions.putAll(properties);
            identities().passwordStrength.updated(new HashMap<>(this.passwordOptions));
        } else {
            fail("Unexpected configuration PID: " + pid);
        }
    }
    private void givenIdentity(String username, Optional<String> password, List<String> roles) throws Exception {
        givenIdentity(username, password, roles, false);
    }
    private void givenIdentity(String username, Optional<String> password, List<String> roles,
            boolean needsChange) throws Exception {
        // Model existing credentials created before the currently enforced password policy.
        // Restore that policy before any HTTP password-change request exercises it.
        identities().passwordStrength.updated(Map.of("new.password.min.length", 1));
        try {
            identities().create(username, password.orElse("Unused-Password-1!"), roles);
        } finally {
            identities().passwordStrength.updated(new HashMap<>(this.passwordOptions));
        }
        if (password.isEmpty()) {
            ((org.osgi.service.useradmin.User) identities().userAdmin.getRole("kura.user." + username))
                    .getCredentials().remove("kura.password");
        }
        if (needsChange) { identities().requirePasswordChange(username); }
    }
    private void whenIdentityIsUpdated(String username, Optional<String> password, List<String> roles) throws Exception {
        identities().service.updateIdentityConfiguration(new IdentityConfiguration(username, List.of(
                new PasswordConfiguration(false, true, password.map(String::toCharArray), Optional.empty()))));
    }
    private void givenService(TestService service) { addResource(service); }
    private void givenAuthenticationProvider(AuthenticationProvider provider) {
        this.customProvider = provider;
        this.rest.bindAuthenticationProvider(provider);
        thenProviderIsEnabled();
    }
    private void whenAuthenticationProviderIsRegistered(AuthenticationProvider provider) {
        givenAuthenticationProvider(provider);
    }
    private void whenLastRegisteredServiceIsUnregistered() {
        this.rest.unbindAuthenticationProvider(this.customProvider);
    }
    private void thenProviderIsEnabled() { assertTrue(this.providerEnabled.isDone()); }
    private void thenProviderIsDisabled() { assertTrue(this.providerDisabled.isDone()); }
    private void thenProviderAuthenticatedRequest() { assertTrue(this.providerAuthenticated.isDone()); }
    private void thenProviderDidNotAuthenticateRequest() { assertFalse(this.providerAuthenticated.isDone()); }
    private void whenRequestIsPerformed(MethodSpec method, String resource) throws Exception {
        whenRequestIsPerformed("http", 8080, method, "/testservice" + resource, null);
    }
    private void whenRequestIsPerformed(String protocol, int port, MethodSpec method, String resource, String body)
            throws Exception {
        assertTrue(("http".equals(protocol) && port == 8080) || ("https".equals(protocol) && port == 9999));
        String base = "https".equals(protocol) ? this.httpsBaseUrl : this.baseUrl;
        assertNotNull(base);
        HttpRequest.Builder request = HttpRequest.newBuilder(URI.create(base + resource.substring(1)))
                .timeout(java.time.Duration.ofSeconds(5));
        this.headers.forEach(request::header);
        if (body != null) { request.header("Content-Type", "application/json"); }
        request.method(method.method(), body == null ? HttpRequest.BodyPublishers.noBody()
                : HttpRequest.BodyPublishers.ofString(body));
        this.response = this.client.send(request.build(), HttpResponse.BodyHandlers.ofString());
    }
    private void givenSuccessfulRequest(MethodSpec method, String resource) throws Exception {
        whenRequestIsPerformed(method, resource); thenRequestSucceeds();
    }
    private void givenSuccessfulRequest(String protocol, int port, MethodSpec method, String resource, String body)
            throws Exception {
        whenRequestIsPerformed(protocol, port, method, resource, body); thenRequestSucceeds();
    }
    @Override
    protected void thenResponseCodeIs(int status) { assertEquals(status, this.response.statusCode(), this.response.body()); }
    private void thenRequestSucceeds() {
        assertTrue(this.response.statusCode() >= 200 && this.response.statusCode() < 300,
                () -> this.response.statusCode() + ": " + this.response.body());
    }
    private void thenResponseBodyEqualsJson(String expected) {
        var expectedJson = JsonParser.parseString(expected);
        var actualJson = JsonParser.parseString(this.response.body());
        // Permission lists are sets in the identity API, independent of role-store iteration order.
        if (expectedJson.isJsonObject() && expectedJson.getAsJsonObject().has("permissions")) {
            var expectedPermissions = new HashSet<>(expectedJson.getAsJsonObject().remove("permissions").getAsJsonArray().asList());
            var actualPermissions = new HashSet<>(actualJson.getAsJsonObject().remove("permissions").getAsJsonArray().asList());
            assertEquals(expectedPermissions, actualPermissions);
        }
        assertEquals(expectedJson, actualJson);
    }
    private void givenXsrfToken() throws Exception { givenXsrfToken("http", 8080); }
    private void givenXsrfToken(String protocol, int port) throws Exception {
        whenRequestIsPerformed(protocol, port, new MethodSpec("GET"), "/session/v1/xsrfToken", null);
        thenResponseCodeIs(200);
        givenXsrfTokenHeader(Json.parse(this.response.body()).asObject().get("xsrfToken").asString());
    }
    private void givenXsrfTokenHeader(String token) { this.headers.put("X-XSRF-Token", token); }
    private void givenDelay(long amount, TimeUnit unit) throws InterruptedException { unit.sleep(amount); }
    private void givenSnapshotOfCurrentCookies() {
        this.cookieSnapshot = new HashMap<>();
        this.cookies.getCookieStore().getCookies().forEach(cookie -> this.cookieSnapshot.put(cookie.getName(), cookie.getValue()));
    }
    private void givenCookieInSnapshot(String name) { assertNotNull(this.cookieSnapshot.get(name)); }
    private String currentCookie(String name) {
        return this.cookies.getCookieStore().getCookies().stream().filter(cookie -> cookie.getName().equals(name))
                .map(HttpCookie::getValue).findFirst().orElse(null);
    }
    private void thenResponseHasCookie(String name) {
        assertTrue(this.response.headers().allValues("set-cookie").stream().anyMatch(value -> value.startsWith(name + "=")));
        assertNotNull(currentCookie(name));
    }
    private void thenResponseDoesNotHaveCookie(String name) {
        assertFalse(this.response.headers().allValues("set-cookie").stream().anyMatch(value -> value.startsWith(name + "=")));
    }
    private void thenCurrentCookieDiffersFromPreviousSnapshot(String name) {
        assertNotNull(currentCookie(name));
        assertNotEquals(this.cookieSnapshot.get(name), currentCookie(name));
    }
    private void whenCookieIsRestoredFromSnapshot(String name) {
        this.cookies.getCookieStore().removeAll();
        // An explicit captured cookie avoids inferring success from an empty cookie jar.
        this.headers.put("Cookie", name + "=" + this.cookieSnapshot.get(name));
    }
    private void givenXForwardedForHeader(String ip) { this.headers.put("X-Forwarded-For", ip); }
    private void thenAuditContextIpIsNotXffSpoofedValue(String value) { assertFalse(this.response.body().contains(value)); }
    private void thenAuditContextIpIsLoopback() { assertEquals("127.0.0.1", this.response.body()); }
    private void givenCA(String name) throws Exception { this.tls.createCA(name); }
    private void givenKeystoreService(String name) throws Exception { this.tls.createKeyStore(name); }
    private void givenCACertificateInKeystore(String store, String ca) throws Exception { this.tls.trust(store, ca); }
    private void givenKeyPairInKeystore(String store, String ca, String cn) throws Exception {
        this.tls.createKey(store, ca, cn);
    }
    private void givenHttpServiceClientCertAuthEnabled(String store, int port) throws Exception {
        assertEquals(9999, port);
        this.httpsBaseUrl = this.tls.addMutualTlsConnector(this.server, store);
        updateRestOptions();
    }
    private void givenHttpServiceClientCertAuthDisabled() { assertNull(this.httpsBaseUrl); }
    private void givenClientKeystore(String store) throws Exception {
        this.client.close();
        this.client = HttpClient.newBuilder().sslContext(this.tls.clientContext(store))
                .connectTimeout(java.time.Duration.ofSeconds(5)).cookieHandler(this.cookies).build();
    }
    private static Map<String, Object> map(Object... pairs) {
        Map<String, Object> result = new HashMap<>();
        for (int i = 0; i < pairs.length; i += 2) { result.put((String) pairs[i], pairs[i + 1]); }
        return result;
    }
    public static abstract class TestService {

        @GET
        @Path("/ping")
        public String ping() {
            return "ok";
        }

    }

    @Path("testservice")
    public static class NoAuth extends TestService {

        @GET
        @Path("/noAuth")
        public String noAuth() {
            return "Hello";
        }
    }

    @Path("testservice")
    public static class NoAuthBroken extends TestService {

        @GET
        @Path("/noAuth")
        public String noAuth() throws Exception {
            throw new Exception("Some error");
        }
    }

    @Path("testservice")
    public static class RequiresAssetsRole extends TestService {

        @GET
        @Path("requireAssets")
        @RolesAllowed("assets")
        public String requireAssets() {
            return "Hello";
        }
    }

    public class DummyAuthenticationProvider implements AuthenticationProvider {

        final String expectedCredentials;
        final String targetIdentity;

        public DummyAuthenticationProvider(final String expectedUsername, final String expectedPassword,
                final String targetIdentity) {
            this.expectedCredentials = expectedUsername + ":" + expectedPassword;
            this.targetIdentity = targetIdentity;
        }

        @Override
        public void onEnabled() {
            providerEnabled.complete(null);
        }

        @Override
        public void onDisabled() {
            providerDisabled.complete(null);
        }

        @Override
        public Optional<Principal> authenticate(HttpServletRequest request, ContainerRequestContext requestContext) {

            String authHeader = requestContext.getHeaderString("Authorization");
            if (authHeader == null) {
                return Optional.empty();
            }

            StringTokenizer tokens = new StringTokenizer(authHeader);
            String authScheme = tokens.nextToken();
            if (!"Basic".equals(authScheme)) {
                return Optional.empty();
            }

            final String credentials = new String(Base64.getDecoder().decode(tokens.nextToken()),
                    StandardCharsets.UTF_8);

            if (expectedCredentials.equals(credentials)) {
                providerAuthenticated.complete(null);
                return Optional.of(() -> targetIdentity);
            } else {
                return Optional.empty();
            }
        }
    }

    @Priority(1000)
    private class LowPriorityAuthenticationProvider extends DummyAuthenticationProvider {

        public LowPriorityAuthenticationProvider(String expectedUsername, String expectedPassword,
                String targetIdentity) {
            super(expectedUsername, expectedPassword, targetIdentity);
        }
    }

    @Priority(1)
    private class HighPriorityAuthenticationProvider extends DummyAuthenticationProvider {

        public HighPriorityAuthenticationProvider(String expectedUsername, String expectedPassword,
                String targetIdentity) {
            super(expectedUsername, expectedPassword, targetIdentity);
        }
    }

    @Path("testservice")
    public static class AuditContextCapturingService extends TestService {

        @GET
        @Path("/auditIp")
        public String getAuditContextIp(@Context ContainerRequestContext requestContext) {
            final Object rawContext = requestContext.getProperty("org.eclipse.kura.rest.audit.context");
            if (rawContext instanceof AuditContext) {
                return ((AuditContext) rawContext).getProperties().getOrDefault("ip", "no-ip");
            }
            return "no-audit-context";
        }
    }

}
