yofc-iot-api-comp=file\:/opt/eclipse/kura/packages/yofc-iot-api-comp-${yofc.dp.version}.dp
yofc-iot-apps-comp=file\:/opt/eclipse/kura/packages/yofc-iot-apps-comp-${yofc.dp.version}.dp
yofc-iot-repack-vertx-db=file\:/opt/eclipse/kura/packages/yofc-iot-repack-vertx-db-${yofc.dp.version}.dp
yofc-iot-apps-opcuaserver=file\:/opt/eclipse/kura/packages/yofc-iot-apps-opcuaserver-${yofc.dp.version}.dp
