<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2011, 2025 Eurotech and/or its affiliates and others
  
    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/
 
	SPDX-License-Identifier: EPL-2.0
	
	Contributors:
	 Eurotech

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.eclipse.kura</groupId>
		<artifactId>kura</artifactId>
		<version>6.0.0-SNAPSHOT</version>
	</parent>

	<properties>
		<kura.basedir>${project.basedir}/..</kura.basedir>
		<sonar.coverage.jacoco.xmlReportPaths>${project.basedir}/../test/*/target/site/jacoco-aggregate/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
	</properties>

	<artifactId>org.eclipse.kura.core</artifactId>
	<version>2.0.0-SNAPSHOT</version>
	<packaging>eclipse-plugin</packaging>
	
	<build>
		<plugins>
			<plugin>
				<groupId>biz.aQute.bnd</groupId>
				<artifactId>bnd-maven-plugin</artifactId>
				<configuration>
				    <bnd><![CDATA[
				      	Bundle-Name: org.eclipse.kura.core
						Bundle-SymbolicName: org.eclipse.kura.core;singleton:=true
						Bundle-Version: 2.0.0.qualifier
						Bundle-Vendor: Eclipse Kura
						-exportcontents: org.eclipse.kura.core.linux.executor;version="1.0.0",\
						 org.eclipse.kura.core.linux.util;version="1.2.0",\
						 org.eclipse.kura.core.ssl;version="1.0.0",\
						 org.eclipse.kura.core.util;version="2.0.0";x-internal:=true
						Bundle-ActivationPolicy: lazy
				    ]]></bnd>
  				</configuration>
			</plugin>
		</plugins>
	</build>
	
</project>
