/*******************************************************************************
 * Copyright (c) 2021, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.testutil.requesthandler;

import java.io.InputStream;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.TimeUnit;
import javax.net.ssl.HttpsURLConnection;
import javax.net.ssl.SSLContext;

/** HTTP transport for a server explicitly owned by the calling fixture. */
public class RestTransport implements Transport {
    private final String baseURL;
    private int timeoutMs = 5000;
    private Optional<String> basicCredentials = Optional.empty();
    private SSLContext sslContext;
    private boolean hostnameVerificationEnabled = true;
    private CookieManager cookies = new CookieManager();
    private final Map<String, String> headers = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);

    public RestTransport(String urlPrefix, String servicePath) {
        this.baseURL = urlPrefix + servicePath;
        URI uri = URI.create(this.baseURL);
        if (!Set.of("http", "https").contains(uri.getScheme()) || uri.getHost() == null) {
            throw new IllegalArgumentException("Expected an absolute HTTP(S) endpoint");
        }
    }

    @Override
    public TransportType getType() { return TransportType.REST; }

    /** The caller starts/registers services; this never rewrites live Kura configuration. */
    @Override
    public void init() { }

    public void setTimeoutMillis(int timeoutMs) {
        if (timeoutMs <= 0) { throw new IllegalArgumentException("Timeout must be positive"); }
        this.timeoutMs = timeoutMs;
    }
    public void setBasicCredentials(Optional<String> value) { this.basicCredentials = value; }
    public void setSslContext(SSLContext value) { this.sslContext = value; }
    public void setHostnameVerificationEnabled(boolean enabled) { this.hostnameVerificationEnabled = enabled; }
    public void setHeader(String name, String value) { this.headers.put(name, value); }
    public void removeHeader(String name) { this.headers.remove(name); }
    public void setCookieManager(CookieManager value) { this.cookies = Objects.requireNonNull(value); }
    public CookieManager getCookieManager() { return this.cookies; }

    @Override
    public Response runRequest(String resource, MethodSpec method) { return runRequest(resource, method, null); }

    @Override
    public Response runRequest(String resource, MethodSpec method, String body) {
        return runRequest(this.baseURL, resource, method, body);
    }

    public Response runRequest(String prefix, String resource, MethodSpec method, String body) {
        HttpURLConnection connection = null;
        try {
            URI uri = URI.create(prefix + resource);
            connection = (HttpURLConnection) uri.toURL().openConnection();
            connection.setConnectTimeout(this.timeoutMs);
            connection.setReadTimeout(this.timeoutMs);
            connection.setInstanceFollowRedirects(false);
            connection.setRequestMethod(method.getRestMethod());
            connection.setRequestProperty("Accept", "application/json");
            connection.setRequestProperty("Connection", "close");
            if (this.basicCredentials.isPresent()) {
                connection.setRequestProperty("Authorization", "Basic " + Base64.getEncoder().encodeToString(
                        this.basicCredentials.get().getBytes(StandardCharsets.UTF_8)));
            }
            if (connection instanceof HttpsURLConnection https) {
                if (this.sslContext != null) { https.setSSLSocketFactory(this.sslContext.getSocketFactory()); }
                if (!this.hostnameVerificationEnabled) { https.setHostnameVerifier((host, session) -> true); }
            }
            for (var entry : this.headers.entrySet()) { connection.setRequestProperty(entry.getKey(), entry.getValue()); }
            for (var entry : this.cookies.get(uri, connection.getRequestProperties()).entrySet()) {
                if (!entry.getValue().isEmpty()) {
                    connection.setRequestProperty(entry.getKey(), String.join("; ", entry.getValue()));
                }
            }
            if (body != null) {
                byte[] bytes = body.getBytes(StandardCharsets.UTF_8);
                connection.setDoOutput(true);
                connection.setFixedLengthStreamingMode(bytes.length);
                connection.setRequestProperty("Content-Type", this.headers.getOrDefault("Content-Type", "application/json"));
                try (var out = connection.getOutputStream()) { out.write(bytes); }
            }
            int status = connection.getResponseCode();
            this.cookies.put(uri, connection.getHeaderFields());
            Map<String, List<String>> responseHeaders = new HashMap<>();
            connection.getHeaderFields().forEach((name, values) -> {
                if (name != null) { responseHeaders.put(name, List.copyOf(values)); }
            });
            Optional<String> responseBody;
            try (InputStream in = status >= 400 ? connection.getErrorStream() : connection.getInputStream()) {
                responseBody = in == null ? Optional.empty()
                        : Optional.of(new String(in.readAllBytes(), StandardCharsets.UTF_8)).filter(value -> !value.isEmpty());
            }
            return new Response(status, responseBody, Map.copyOf(responseHeaders));
        } catch (Exception e) {
            throw new IllegalStateException("HTTP request failed", e);
        } finally {
            if (connection != null) { connection.disconnect(); }
        }
    }

    public static void waitPortOpen(String host, int port, long timeout, TimeUnit unit) throws InterruptedException {
        waitPort(host, port, true, timeout, unit);
    }
    public static void waitPortClosed(String host, int port, long timeout, TimeUnit unit) throws InterruptedException {
        waitPort(host, port, false, timeout, unit);
    }
    private static void waitPort(String host, int port, boolean expectedOpen, long timeout, TimeUnit unit)
            throws InterruptedException {
        long deadline = System.nanoTime() + unit.toNanos(timeout);
        while (System.nanoTime() < deadline) {
            boolean open;
            try (Socket socket = new Socket()) {
                int remainingMs = (int) Math.max(1, Math.min(500,
                        TimeUnit.NANOSECONDS.toMillis(deadline - System.nanoTime())));
                socket.connect(new InetSocketAddress(host, port), remainingMs);
                open = true;
            } catch (java.io.IOException e) { open = false; }
            if (open == expectedOpen) { return; }
            TimeUnit.MILLISECONDS.sleep(50);
        }
        throw new IllegalStateException("Port " + port + " did not become " + (expectedOpen ? "open" : "closed"));
    }

    @Override
    public void close() { this.cookies.getCookieStore().removeAll(); }
}
