<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>

     <parent>
        <groupId>org.eclipse.kura</groupId>
        <artifactId>target-platform</artifactId>
        <version>6.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>p2-repo-extra</artifactId>
    <packaging>pom</packaging>
	<build>
		<plugins>
			<plugin>
				<groupId>org.reficio</groupId>
				<artifactId>p2-maven-plugin</artifactId>
				<version>${p2-maven-plugin.version}</version>
				<executions>
					<execution>
						<id>generate-p2-site</id>
						<phase>initialize</phase>
						<goals>
							<goal>site</goal>
						</goals>
						<configuration>
							<artifacts>
								<artifact>
									<id>jakarta.activation:jakarta.activation-api:jar:${jakarta.activation-api.javax.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>jakarta.xml.bind:jakarta.xml.bind-api:jar:${jakarta.xml.bind-api.javax.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>com.sun.xml.bind:jaxb-osgi:${jaxb-osgi.javax.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								
							</artifacts>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<repositories>
		<repository>
			<id>mvnrepository</id>
			<url>https://repo.maven.apache.org/maven2</url>
		</repository>
	</repositories>
</project>