<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>

     <parent>
        <groupId>org.eclipse.kura</groupId>
        <artifactId>target-platform</artifactId>
        <version>6.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>p2-repo-extra</artifactId>
    <packaging>pom</packaging>
	<build>
		<plugins>
			<plugin>
				<groupId>org.reficio</groupId>
				<artifactId>p2-maven-plugin</artifactId>
				<version>${p2-maven-plugin.version}</version>
				<executions>
					<execution>
						<id>generate-p2-site</id>
						<phase>initialize</phase>
						<goals>
							<goal>site</goal>
						</goals>
						<configuration>
							<artifacts>
								
							</artifacts>
						</configuration>
					</execution>
				</executions>
			</plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <id>install-p2-bundles-to-local-m2</id>
                        <phase>install</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <exec executable="${project.basedir}/../install-to-m2.sh"
                                      dir="${project.basedir}"
                                      failonerror="true">
                                    <arg value="${project.build.directory}/repository/plugins" />
                                    <arg value="p2.osgi.bundle" />
                                </exec>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
		</plugins>
	</build>
	<repositories>
		<repository>
			<id>mvnrepository</id>
			<url>https://repo.maven.apache.org/maven2</url>
		</repository>
	</repositories>
</project>