<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>

     <parent>
        <groupId>org.eclipse.kura</groupId>
        <artifactId>target-platform</artifactId>
        <version>6.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>p2-repo-extra</artifactId>
    <packaging>pom</packaging>

	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>properties-maven-plugin</artifactId>
				<version>1.2.1</version>
				<executions>
					<execution>
						<phase>initialize</phase>
						<goals>
							<goal>read-project-properties</goal>
						</goals>
						<configuration>
							<files>
								<file>${basedir}/../config/kura.target-platform.build.properties</file>
							</files>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.reficio</groupId>
				<artifactId>p2-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>generate-p2-site</id>
						<phase>initialize</phase>
						<goals>
							<goal>site</goal>
						</goals>
						<configuration>
							<artifacts>
								<!-- vertx  -->
								<artifact>
									<id>io.vertx:vertx-core:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.vertx:vertx-io_uring-incubator:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.vertx:vertx-web-common:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.vertx:vertx-web:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.vertx:vertx-bridge-common:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.vertx:vertx-web-client:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.vertx:vertx-uri-template:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.vertx:vertx-tcp-eventbus-bridge:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.vertx:vertx-mqtt:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.vertx:vertx-auth-common:${vertx.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>

								<artifact>
									<id>io.vavr:vavr:${io.vavr.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>>
								<artifact>
									<id>org.codehaus.groovy:groovy:${org.codehaus.groovy.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.codehaus.groovy:groovy-xml:${org.codehaus.groovy.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.codehaus.groovy:groovy-templates:${org.codehaus.groovy.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.codehaus.groovy:groovy-sql:${org.codehaus.groovy.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.codehaus.groovy:groovy-json:${org.codehaus.groovy.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.codehaus.groovy:groovy-datetime:${org.codehaus.groovy.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.codehaus.groovy:groovy-dateutil:${org.codehaus.groovy.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.apache.httpcomponents:httpcore-osgi:${org.apache.httpcomponents.httpcore-osgi.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>commons-codec:commons-codec:${org.apache.commons.codec.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>jakarta.jms:jakarta.jms-api:${jakarta.jms-api.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>>
								<artifact>
									<id>com.google.code.gson:gson:${com.google.gson.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.apache.commons:commons-configuration2:${commons-configuration2.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.apache.commons:commons-text:${commons-text.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.netty:netty-codec-http2:${io.netty.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.netty:netty-codec-dns:${io.netty.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.netty:netty-resolver-dns-native-macos:${io.netty.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.netty:netty-handler-proxy:${io.netty.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.netty:netty-resolver-dns:${io.netty.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>io.netty:netty-codec-socks:${io.netty.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>com.fasterxml.jackson.core:jackson-core:${com.fasterxml.jackson.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>com.fasterxml.jackson.core:jackson-databind:${com.fasterxml.jackson.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>com.fasterxml.jackson.core:jackson-annotations:${com.fasterxml.jackson.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>com.fasterxml.jackson.module:jackson-module-jaxb-annotations:${com.fasterxml.jackson.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:${com.fasterxml.jackson.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.yaml:snakeyaml:${org.yaml.snakeyaml.mvn.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.apache.commons:commons-pool2:jar:${org.apache.commons-pool2.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.gwtproject:gwt-servlet-jakarta:${gwt-user.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.gwtbootstrap3:gwtbootstrap3:${org.gwtbootstrap3.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.apache.felix:org.apache.felix.fileinstall:${org.apache.felix.fileinstall.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.eclipse.paho:org.eclipse.paho.mqttv5.client:${org.eclipse.paho.client.mqttv3.version}</id>
									<source>true</source>
									<transitive>false</transitive>
									<override>true</override>
									<instructions>
										<Import-Package>*;resolution:=optional</Import-Package>
										<Export-Package>org.eclipse.paho.mqttv5.client;version="1.2.5",
														org.eclipse.paho.mqttv5.client.persist;version="1.2.5",
														org.eclipse.paho.mqttv5.common;version="1.2.5",
														org.eclipse.paho.mqttv5.common.packet;version="1.2.5"
										</Export-Package>
									</instructions>
								</artifact>
								<artifact>
									<id>org.eclipse.milo:sdk-client:jar:${org.eclipse.milo.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.eclipse.milo:sdk-core:jar:${org.eclipse.milo.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.eclipse.milo:stack-client:jar:${org.eclipse.milo.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.eclipse.milo:stack-core:jar:${org.eclipse.milo.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.eclipse.milo:dictionary-manager:jar:${org.eclipse.milo.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.eclipse.milo:bsd-core:jar:${org.eclipse.milo.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.eclipse.milo:bsd-generator:jar:${org.eclipse.milo.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.eclipse.milo:sdk-server:jar:${org.eclipse.milo.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>org.eclipse.milo:stack-server:jar:${org.eclipse.milo.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								
								<artifact>
									<id>com.digitalpetri.fsm:strict-machine:jar:${strict-machine-mvn.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>com.digitalpetri.netty:netty-channel-fsm:jar:${netty-channel-fsm-mvn.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>com.alibaba.fastjson2:fastjson2:jar:${fastjson2.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>com.fazecast:jSerialComm:jar:${jSerialComm.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>tel.schich:javacan-core:jar:${javacan.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
								<artifact>
									<id>net.java.dev.jna:jna:jar:${net.java.dev.jna.version}</id>
									<source>true</source>
									<transitive>false</transitive>
								</artifact>
							</artifacts>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-antrun-plugin</artifactId>
				<version>${maven-antrun-plugin.version}</version>
				<executions>
					<execution>
						<id>install-equinox</id>
						<phase>install</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<target>
								<delete dir="../../kura/target-definition/extra/" />
								<mkdir dir="../../kura/target-definition/extra/repository" />
								<copy todir="../../kura/target-definition/extra/repository">
									<fileset dir="${project.build.directory}/repository" />
								</copy>
							</target>
						</configuration>
					</execution>
				</executions>
			</plugin>
			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
				<version>3.1.1</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<repositories>
		<repository>
			<id>mvnrepository</id>
			<url>https://repo.maven.apache.org/maven2</url>
		</repository>
	</repositories>
</project>