<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2011, 2025 Eurotech and/or its affiliates and others
  
    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/
 
    SPDX-License-Identifier: EPL-2.0
 
    Contributors:
     Eurotech
     Red Hat Inc
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>org.eclipse.kura</groupId>
    <artifactId>target-platform</artifactId>
    <version>6.0.0-SNAPSHOT</version>

    <packaging>pom</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <check.plugins.exist.remote>false</check.plugins.exist.remote>
        <skip.libsocket-can>true</skip.libsocket-can>

        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>

        <!-- Plugins versions -->
        <exists-maven-plugin.version>0.12.0</exists-maven-plugin.version>
        <lifecycle-mapping.version>1.0.0</lifecycle-mapping.version>
        <maven-antrun-plugin.version>3.1.0</maven-antrun-plugin.version>
        <maven-bundle-plugin.version>5.1.9</maven-bundle-plugin.version>
        <maven-clean-plugin.version>3.3.2</maven-clean-plugin.version>
        <maven-compiler-plugin.version>3.11.0</maven-compiler-plugin.version>
        <maven-checkstyle-plugin.version>3.1.0</maven-checkstyle-plugin.version>
        <maven-dependency-plugin.version>3.6.1</maven-dependency-plugin.version>
        <maven-deploy-plugin.version>3.1.1</maven-deploy-plugin.version>
        <maven-site-plugin.version>3.12.1</maven-site-plugin.version>
        <maven-surefire-plugin.version>3.2.3</maven-surefire-plugin.version>
        <p2-maven-plugin.version>2.1.0</p2-maven-plugin.version>
        
        <!-- START common dependencies -->
        <apache-qpid-jms-client.version>2.7.0</apache-qpid-jms-client.version>
        <apache-qpid-proton-j.version>0.34.1</apache-qpid-proton-j.version>
        <bluez-dbus-osgi.version>0.3.1</bluez-dbus-osgi.version>
        <com.eclipsesource.minimal-json.version>0.9.5</com.eclipsesource.minimal-json.version>
        <com.eurotech.gpsd4java.version>1.0.0</com.eurotech.gpsd4java.version>
        <com.google.gson.version>2.11.0</com.google.gson.version>
        <com.google.protobuf.version>4.30.2</com.google.protobuf.version>
        <com.h2database.h2.version>2.3.232</com.h2database.h2.version>
        <commons-beanutils.version>1.9.4</commons-beanutils.version>
        <commons-collections.version>3.2.2</commons-collections.version>
        <commons-csv.version>1.14.0</commons-csv.version>
        <commons-exec.version>1.4.0</commons-exec.version>
        <commons-fileupload.version>2.0.0-M2</commons-fileupload.version>
        <failureaccess.version>1.0.2</failureaccess.version>
        <guava.version>33.4.0-jre</guava.version>
        <hikaricp.version>5.1.0</hikaricp.version>
        <hk2.version>3.1.1</hk2.version>
        <io.netty.version>4.2.12.Final</io.netty.version>
        <javassist.version>3.30.2-GA</javassist.version>
        <jersey.version>3.1.9</jersey.version>
        <log4j.version>2.25.4</log4j.version>
        <mimepull.version>1.10.0</mimepull.version>
        <org.apache.aries.spifly.dynamic.bundle.version>1.3.7</org.apache.aries.spifly.dynamic.bundle.version>
        <!--<org.apache.camel.version>2.25.3</org.apache.camel.version>-->
        <org.apache.commons.commons-io.version>2.21.0</org.apache.commons.commons-io.version>
        <org.apache.commons.commons-net.version>3.12.0</org.apache.commons.commons-net.version>
        <org.apache.commons.lang3.version>3.20.0</org.apache.commons.lang3.version>
        <org.apache.felix.dependencymanager.version>4.6.1</org.apache.felix.dependencymanager.version>
        <org.apache.felix.deploymentadmin.version>0.9.10</org.apache.felix.deploymentadmin.version>
        <org.apache.felix.http.bridge.version>5.1.8</org.apache.felix.http.bridge.version>
        <org.apache.felix.http.jetty12.version>1.0.2</org.apache.felix.http.jetty12.version>
        <org.apache.felix.http.proxy.version>4.0.0</org.apache.felix.http.proxy.version>
        <org.apache.felix.http.servlet-api.version>3.0.0</org.apache.felix.http.servlet-api.version>
        <org.apache.felix.http.wrappers.version>1.1.2</org.apache.felix.http.wrappers.version>
        <org.apache.felix.useradmin.version>1.0.4</org.apache.felix.useradmin.version>
        <org.apache.geronimo.specs.jms.version>1.0-alpha-2</org.apache.geronimo.specs.jms.version>
        <org.apache.geronimo.specs.json.version>1.0-alpha-1</org.apache.geronimo.specs.json.version>
        <org.apache.geronimo.specs.jta.version>1.1.1</org.apache.geronimo.specs.jta.version>
        <org.apache.servicemix.bundles.c3p0.version>0.9.5.5_1</org.apache.servicemix.bundles.c3p0.version>
        <org.bouncycastle.version>1.84</org.bouncycastle.version>
        <org.eclipse.jetty.version>12.1.8</org.eclipse.jetty.version>
        <org.eclipse.osgi-technology.rest.version>1.2.3</org.eclipse.osgi-technology.rest.version>
        <org.eclipse.paho.client.mqttv3.version>1.2.5</org.eclipse.paho.client.mqttv3.version>
        <org.hamcrest.core.version>2.2</org.hamcrest.core.version>
        <!--<org.jboss.logging.version>3.3.2.Final</org.jboss.logging.version>-->
        <org.knowhowlab.osgi.monitoradmin.version>1.0.3</org.knowhowlab.osgi.monitoradmin.version>
        <org.osgi.service.component.annotations.version>1.5.1</org.osgi.service.component.annotations.version>
        <org.osgi.service.http.whiteboard.version>1.1.1</org.osgi.service.http.whiteboard.version>
        <org.osgi.service.metatype.annotations.version>1.4.1</org.osgi.service.metatype.annotations.version>
        <org.osgi.service.servlet.version>2.0.0</org.osgi.service.servlet.version>
        <org.ow2.asm.version>9.7.1</org.ow2.asm.version>
        <org.xerial.sqlite-jdbc.version>3.47.1.0</org.xerial.sqlite-jdbc.version>
        <osgi-resource-locator.version>1.0.3</osgi-resource-locator.version>
        <osgi.annotation.version>8.1.0</osgi.annotation.version>
        <quartz.version>2.5.0</quartz.version>
        <slf4j.version>2.0.17</slf4j.version>
        <spring.version>6.0.10_1</spring.version>
        <!-- END common dependencies -->
        <!-- START Jakarta dependencies -->
        <jakarta.activation-api.version>2.1.2</jakarta.activation-api.version>
        <jakarta.annotation-api.version>2.1.1</jakarta.annotation-api.version>
        <jakarta.inject-api.version>2.0.1</jakarta.inject-api.version>
        <jakarta.validation-api.version>3.0.2</jakarta.validation-api.version>
        <jakarta.xml.bind-api.version>4.0.2</jakarta.xml.bind-api.version>
        <jakarta.xml.ws-api.version>4.0.2</jakarta.xml.ws-api.version>
        <jakarta.xml.soap-api.version>3.0.2</jakarta.xml.soap-api.version>
        <jakarta.ws.rs-api.version>3.1.0</jakarta.ws.rs-api.version>
        <org.osgi.service.jakartars.version>2.0.0</org.osgi.service.jakartars.version>
        <jaxb-osgi.version>4.0.2</jaxb-osgi.version>
        <!-- END Jakarta dependencies -->
        <!-- START Equinox dependencies -->
        <org.apache.felix.gogo.command.version>1.1.2</org.apache.felix.gogo.command.version>
        <org.apache.felix.gogo.runtime.version>1.1.6</org.apache.felix.gogo.runtime.version>
        <org.apache.felix.gogo.shell.version>1.1.4</org.apache.felix.gogo.shell.version>
        <org.apache.felix.scr.version>2.2.14</org.apache.felix.scr.version>
        <org.eclipse.core.contenttype.version>3.9.800</org.eclipse.core.contenttype.version>
        <org.eclipse.core.jobs.version>3.15.700</org.eclipse.core.jobs.version>
        <org.eclipse.core.runtime.version>3.34.200</org.eclipse.core.runtime.version>
        <org.eclipse.equinox.app.version>1.7.600</org.eclipse.equinox.app.version>
        <org.eclipse.equinox.cm.version>1.6.400</org.eclipse.equinox.cm.version>
        <org.eclipse.equinox.common.version>3.20.300</org.eclipse.equinox.common.version>
        <org.eclipse.equinox.console.version>1.4.1100</org.eclipse.equinox.console.version>
        <org.eclipse.equinox.event.version>1.7.300</org.eclipse.equinox.event.version>
        <org.eclipse.equinox.launcher.version>1.7.100</org.eclipse.equinox.launcher.version>
        <org.eclipse.equinox.metatype.version>1.6.900</org.eclipse.equinox.metatype.version>
        <org.eclipse.equinox.preferences.version>3.12.100</org.eclipse.equinox.preferences.version>
        <org.eclipse.equinox.registry.version>3.12.600</org.eclipse.equinox.registry.version>
        <org.eclipse.equinox.util.version>1.1.300</org.eclipse.equinox.util.version>
        <org.eclipse.equinox.wireadmin.version>1.0.800</org.eclipse.equinox.wireadmin.version>
        <org.eclipse.osgi.util.version>3.7.400</org.eclipse.osgi.util.version>
        <org.eclipse.osgi.version>3.24.100</org.eclipse.osgi.version>
        <org.osgi.service.cm.version>1.6.1</org.osgi.service.cm.version>
        <org.osgi.service.component.version>1.5.1</org.osgi.service.component.version>
        <org.osgi.service.coordinator.version>1.0.2</org.osgi.service.coordinator.version>
        <org.osgi.service.device.version>1.1.1</org.osgi.service.device.version>
        <org.osgi.service.event.version>1.4.1</org.osgi.service.event.version>
        <org.osgi.service.log.stream.version>1.0.0</org.osgi.service.log.stream.version>
        <org.osgi.service.metatype.version>1.4.1</org.osgi.service.metatype.version>
        <org.osgi.service.prefs.version>1.1.2</org.osgi.service.prefs.version>
        <org.osgi.service.provisioning.version>1.2.0</org.osgi.service.provisioning.version>
        <org.osgi.service.upnp.version>1.2.1</org.osgi.service.upnp.version>
        <org.osgi.service.useradmin.version>1.1.1</org.osgi.service.useradmin.version>
        <org.osgi.service.wireadmin.version>1.0.2</org.osgi.service.wireadmin.version>
        <org.osgi.util.function.version>1.2.0</org.osgi.util.function.version>
        <org.osgi.util.measurement.version>1.0.2</org.osgi.util.measurement.version>
        <org.osgi.util.position.version>1.0.1</org.osgi.util.position.version>
        <org.osgi.util.promise.version>1.3.0</org.osgi.util.promise.version>
        <org.osgi.util.pushstream.version>1.1.0</org.osgi.util.pushstream.version>
        <org.osgi.util.xml.version>1.0.2</org.osgi.util.xml.version>
        <!-- END Equinox dependencies -->
        
        <!-- START test dependencies -->
        <byte-buddy.version>1.18.8</byte-buddy.version>
        <io.dropwizard.metrics.version>3.2.2</io.dropwizard.metrics.version>
        <mockito-core.version>5.7.0</mockito-core.version>
        <moquette-broker.version>0.17</moquette-broker.version>
        <!--<objenesis.version>3.3</objenesis.version>-->
        <org.junit.version>4.13.2</org.junit.version>
        <org.jvnet.mimepull.version>1.10.0</org.jvnet.mimepull.version>
        <org.hamcrest.integration.version>2.2</org.hamcrest.integration.version>
        <org.hamcrest.version>2.2</org.hamcrest.version>
        <!-- END test dependencies -->
        <!-- START target platform dependencies -->
        <!--<org.apache.activemq.artemis.upstream.version>2.6.4</org.apache.activemq.artemis.upstream.version>-->
        <usb4java.version>1.2.0</usb4java.version>
        <!-- END target platform dependencies -->
        <!--<com.gwt.user.version>2.0.0-SNAPSHOT</com.gwt.user.version>-->
        <log4j2-api-config.version>2.0.0-SNAPSHOT</log4j2-api-config.version>
        <!--<org.apache.activemq.artemis.version>3.0.0-SNAPSHOT</org.apache.activemq.artemis.version>-->
        <!-- <org.eclipse.kura.camel.sun.misc.version>2.0.0-SNAPSHOT</org.eclipse.kura.camel.sun.misc.version> -->
        <org.eclipse.kura.sun.misc.version>2.0.0-SNAPSHOT</org.eclipse.kura.sun.misc.version>
        <org.eclipse.soda.dk.comm.version>2.0.0-SNAPSHOT</org.eclipse.soda.dk.comm.version>
        <!--<org.moka7.version>2.0.0-SNAPSHOT</org.moka7.version>-->
        <org.usb4java.version>2.0.0-SNAPSHOT</org.usb4java.version>
        <usb4java-javax.version>2.0.0-SNAPSHOT</usb4java-javax.version>
        
        <vertx.version>5.0.10</vertx.version>
        <org.codehaus.groovy.version>3.0.25</org.codehaus.groovy.version>
        <org.eclipse.milo.version>0.6.16</org.eclipse.milo.version>
        <commons-text.version>1.13.1</commons-text.version>
        <com.fasterxml.jackson.version>2.19.4</com.fasterxml.jackson.version>
        <commons-configuration2.version>2.12.0</commons-configuration2.version>
        <org.yaml.snakeyaml.mvn.version>2.4</org.yaml.snakeyaml.mvn.version>
        <org.apache.commons-pool2.version>2.12.1</org.apache.commons-pool2.version>
        <gwt-user.version>2.12.2</gwt-user.version>
        <org.gwtbootstrap3.version>1.0.1</org.gwtbootstrap3.version>
        <org.apache.felix.fileinstall.version>3.7.4</org.apache.felix.fileinstall.version>
        <strict-machine.version>0.7</strict-machine.version>
        <netty-channel-fsm.version>0.9</netty-channel-fsm.version>
        <fastjson2.version>2.0.61</fastjson2.version>
        <jSerialComm.version>2.11.4</jSerialComm.version>
        <javacan.version>3.5.0</javacan.version>
        <net.java.dev.jna.version>5.17.0</net.java.dev.jna.version>
        <io.vavr.version>1.0.0</io.vavr.version>
        <org.jspecify.version>1.0.0</org.jspecify.version>
        <org.apache.httpcomponents.httpcore-osgi.version>4.4.16</org.apache.httpcomponents.httpcore-osgi.version>
        <org.apache.commons.codec.version>1.21.0</org.apache.commons.codec.version>
        <jakarta.jms-api.version>3.1.0</jakarta.jms-api.version>
        <jakarta.activation-api.javax.version>1.2.2</jakarta.activation-api.javax.version>
        <jakarta.xml.bind-api.javax.version>2.3.3</jakarta.xml.bind-api.javax.version>
        <jaxb-osgi.javax.version>2.3.9</jaxb-osgi.javax.version>
    </properties>

    <modules>
        <module>target-platform-bom</module>
        <module>p2-repo-equinox</module>
        <module>p2-repo-common</module>
        <module>p2-repo-test-deps</module>
        <!--<module>org.apache.activemq.artemis</module>-->
        <!--<module>org.eclipse.kura.camel.sun.misc</module>-->
        <module>org.eclipse.kura.sun.misc</module>
        <module>org.usb4java</module>
        <module>usb4java-javax</module>
        <module>log4j2-api-config</module>
        <module>p2-repo-extra</module>
        <module>target-platform-pde-deps</module>
    </modules>

    <repositories>
        <repository>
            <id>Kura Releases</id>
            <name>Kura Repository - Releases</name>
            <url>https://repo.eclipse.org/content/repositories/kura-releases/</url>
        </repository>
        <repository>
            <id>Kura Snapshots</id>
            <name>Kura Repository - Snapshots</name>
            <url>https://repo.eclipse.org/content/repositories/kura-snapshots/</url>
        </repository>
        <repository>
            <id>kura_addons</id>
            <name>Local Kura Addons Cache</name>
            <url>file://${user.home}/.m2/repository</url>
        </repository>
        <repository>
            <id>Eclipse Paho Repo</id>
            <url>https://repo.eclipse.org/content/repositories/paho-releases/</url>
        </repository>
        <repository>
            <!-- moquette-broker -->
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
    <pluginRepositories>
		<pluginRepository>
			<id>reficio</id>
			<url>http://repo.reficio.org/maven/</url>
		</pluginRepository>
	</pluginRepositories>

    <distributionManagement>
        <repository>
            <id>repo.eclipse.org</id>
            <name>Kura Repository - Releases</name>
            <url>https://repo.eclipse.org/content/repositories/kura-releases/</url>
        </repository>
        <snapshotRepository>
            <id>repo.eclipse.org</id>
            <name>Kura Repository - Snapshots</name>
            <url>https://repo.eclipse.org/content/repositories/kura-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

    <profiles>
        <profile>
            <id>can</id>
            <activation>
                <property>
                    <name>skip.libsocket-can</name>
                    <value>false</value>
                </property>
            </activation>
            <modules>
                <module>org.eclipse.kura.libsocket-can-osgi</module>
            </modules>
        </profile>
        <profile>
            <id>check-exists-plugin</id>
            <properties>
                <check.plugins.exist.remote>true</check.plugins.exist.remote>
            </properties>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <version>${maven-site-plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>${maven-deploy-plugin.version}</version>
                <configuration>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>${maven-checkstyle-plugin.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>org.slf4j</groupId>
                        <artifactId>jcl-over-slf4j</artifactId>
                        <version>2.0.11</version>
                    </dependency>
                    <dependency>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-jdk14</artifactId>
                        <version>2.0.11</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>checkstyle-validation</id>
                        <phase>process-sources</phase>
                        <configuration>
                            <encoding>UTF-8</encoding>
                            <consoleOutput>true</consoleOutput>
                            <failsOnError>true</failsOnError>
                            <linkXRef>false</linkXRef>
                            <configLocation>../checkstyle_checks.xml</configLocation>
                        </configuration>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.honton.chas</groupId>
                <artifactId>exists-maven-plugin</artifactId>
                <version>${exists-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>remote</goal>
                        </goals>
                        <configuration>
                            <skipIfSnapshot>true</skipIfSnapshot>
                            <failIfExists>${check.plugins.exist.remote}</failIfExists>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.felix</groupId>
                    <artifactId>maven-bundle-plugin</artifactId>
                    <version>${maven-bundle-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.eclipse.m2e</groupId>
                    <artifactId>lifecycle-mapping</artifactId>
                    <version>${lifecycle-mapping.version}</version>
                    <configuration>
                        <lifecycleMappingMetadata>
                            <pluginExecutions>
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>
                                            org.jacoco
                                        </groupId>
                                        <artifactId>
                                            jacoco-maven-plugin
                                        </artifactId>
                                        <versionRange>
                                            [0.6.4.201312101107,)
                                        </versionRange>
                                        <goals>
                                            <goal>
                                                prepare-agent
                                            </goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <ignore></ignore>
                                    </action>
                                </pluginExecution>
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>
                                            org.apache.maven.plugins
                                        </groupId>
                                        <artifactId>
                                            maven-dependency-plugin
                                        </artifactId>
                                        <versionRange>
                                            [2.1,)
                                        </versionRange>
                                        <goals>
                                            <goal>
                                                copy-dependencies
                                            </goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <ignore></ignore>
                                    </action>
                                </pluginExecution>
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>
                                            org.apache.maven.plugins
                                        </groupId>
                                        <artifactId>
                                            maven-antrun-plugin
                                        </artifactId>
                                        <versionRange>
                                            [1.7,)
                                        </versionRange>
                                        <goals>
                                            <goal>run</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <ignore></ignore>
                                    </action>
                                </pluginExecution>
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>
                                            org.codehaus.mojo
                                        </groupId>
                                        <artifactId>
                                            build-helper-maven-plugin
                                        </artifactId>
                                        <versionRange>
                                            [1.9,)
                                        </versionRange>
                                        <goals>
                                            <goal>regex-property</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <ignore></ignore>
                                    </action>
                                </pluginExecution>
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>
                                            org.apache.maven.plugins
                                        </groupId>
                                        <artifactId>
                                            maven-checkstyle-plugin
                                        </artifactId>
                                        <versionRange>
                                            [2.14,)
                                        </versionRange>
                                        <goals>
                                            <goal>check</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <ignore></ignore>
                                    </action>
                                </pluginExecution>
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>
                                            org.codehaus.mojo
                                        </groupId>
                                        <artifactId>
                                            exec-maven-plugin
                                        </artifactId>
                                        <versionRange>
                                            [1.2,)
                                        </versionRange>
                                        <goals>
                                            <goal>exec</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <ignore></ignore>
                                    </action>
                                </pluginExecution>
                            </pluginExecutions>
                        </lifecycleMappingMetadata>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
