<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2025 Eurotech and/or its affiliates and others

    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0

    Contributors:
     Eurotech

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>distrib</artifactId>
        <groupId>org.eclipse.kura</groupId>
        <version>6.0.0-SNAPSHOT</version>
        <relativePath>..</relativePath>
    </parent>

    <artifactId>docker-base</artifactId>
    <name>docker-base</name>

    <packaging>pom</packaging>

    <properties>
        <kura.basedir>../</kura.basedir>
        <dist.assembly.name>kura_${project.version}_docker-nn</dist.assembly.name>
        <dist.linux.bundles.skip>false</dist.linux.bundles.skip>
        <target.device>docker-nn</target.device>
        <kura.os.version>linux</kura.os.version>
    </properties>

   <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>buildnumber-maven-plugin</artifactId>
                <version>1.0</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>create-timestamp</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>1.7</version>
                <executions>
                    <execution>
                        <id>docker-nn-jars</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <property name="buildNumber" value="buildNumber" />
                                <property name="project.version" value="${project.version}" />
                                <property name="project.build.profile" value="${project.build.profile}" />
                                <property name="project.build.directory" value="${project.build.directory}" />
                                <property name="build.name" value="docker-nn" />
                                <property name="target.device" value="docker-nn" />
                                <property name="native.tag" value="${native.tag}" />
                                <property name="kura.os.version" value="linux" />
                                <property name="kura.arch" value="${kura.arch}" />
                                <property name="kura.mem.size" value="1024m" />
                                <property name="kura.install.dir" value="/opt/eclipse" />
                                <property name="kura.basedir" value="${kura.basedir}" />

                                <ant antfile="${basedir}/../src/main/ant/build_equinox_distrib.xml" target="dist-linux" />
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>1.7</version>
                <executions>
                    <execution>
                        <id>docker-nn-build-container</id>
                        <phase>package</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <copy todir="${project.build.directory}" file="${project.basedir}/../src/main/resources/docker-nn/Dockerfile" />
                                <exec executable="docker" dir="${project.build.directory}" failonerror="true">
                                    <arg value="build"/>
                                    <arg value="-t"/>
                                    <arg value="base-kura-docker:latest"/>
                                    <arg value="."/>
                                </exec>
                              </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-yofc-dp-into-context</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}</outputDirectory>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>com.yofc.iot</groupId>
                                    <artifactId>yofc-iot-api-comp</artifactId>
                                    <version>${yofc.dp.version}</version>
                                    <type>dp</type>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>com.yofc.iot</groupId>
                                    <artifactId>yofc-iot-apps-comp</artifactId>
                                    <version>${yofc.dp.version}</version>
                                    <type>dp</type>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>com.yofc.iot</groupId>
                                    <artifactId>yofc-iot-repack-vertx-db</artifactId>
                                    <version>${yofc.dp.version}</version>
                                    <type>dp</type>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>com.yofc.iot</groupId>
                                    <artifactId>yofc-iot-apps-opcuaserver</artifactId>
                                    <version>${yofc.dp.version}</version>
                                    <type>dp</type>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>com.yofc.iot</groupId>
                                    <artifactId>yofc-iot-apps-influxdb</artifactId>
                                    <version>${yofc.dp.version}</version>
                                    <type>dp</type>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>com.yofc.iot</groupId>
                                    <artifactId>yofc-iot-apps-influxdbv1</artifactId>
                                    <version>${yofc.dp.version}</version>
                                    <type>dp</type>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>filter-deb-control</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/filtered-control</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.basedir}/../src/main/resources/docker-nn/deb/control</directory>
                                    <filtering>true</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.vafer</groupId>
                <artifactId>jdeb</artifactId>
                <version>${jdeb-version}</version>
                <executions>
                    <execution>
                        <id>docker-nn-deb</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jdeb</goal>
                        </goals>
                        <configuration>
                            <verbose>true</verbose>
                            <deb>${basedir}/target/kura_${package.version}-${package.revision}_docker-nn_installer_${deb.arch}.deb</deb>
                            <snapshotExpand>true</snapshotExpand>
                            <snapshotTemplate>${package.snapshot}</snapshotTemplate>
                            <controlDir>${project.build.directory}/filtered-control</controlDir>
                            <skipPOMs>false</skipPOMs>
                            <dataSet>
                                <data>
                                    <src>${basedir}/target/kura_${project.version}_docker-nn.zip</src>
                                    <type>file</type>
                                    <mapper>
                                        <type>perm</type>
                                        <prefix>/tmp</prefix>
                                    </mapper>
                                </data>
                            </dataSet>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
