<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2025 Eurotech and/or its affiliates and others

    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0

    Contributors:
     Eurotech

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>distrib</artifactId>
        <groupId>org.eclipse.kura</groupId>
        <version>6.0.0-SNAPSHOT</version>
        <relativePath>..</relativePath>
    </parent>

    <artifactId>docker-base</artifactId>
    <name>docker-base</name>

    <packaging>pom</packaging>

    <properties>
        <kura.basedir>../</kura.basedir>
    </properties>

   <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>buildnumber-maven-plugin</artifactId>
                <version>1.0</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>create-timestamp</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>1.7</version>
                <executions>
                    <execution>
                        <id>docker-aarch64-nn-jars</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <property name="buildNumber" value="buildNumber" />
                                <property name="project.version" value="${project.version}" />
                                <property name="project.build.profile" value="${project.build.profile}" />
                                <property name="project.build.directory" value="${project.build.directory}" />
                                <property name="build.name" value="docker-aarch64-nn" />
                                <property name="target.device" value="docker-aarch64-nn" />
                                <property name="native.tag" value="aarch64" />
                                <property name="kura.os.version" value="linux" />
                                <property name="kura.arch" value="aarch64" />
                                <property name="kura.mem.size" value="1024m" />
                                <property name="kura.install.dir" value="/opt/eclipse" />
                                <property name="kura.basedir" value="${kura.basedir}" />

                                <ant antfile="${basedir}/../src/main/ant/build_equinox_distrib.xml" target="dist-linux" />
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>1.7</version>
                <executions>
                    <execution>
                        <id>docker-aarch64-nn-build-container</id>
                        <phase>package</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <copy todir="${project.build.directory}" file="${project.basedir}/../src/main/resources/docker-aarch64-nn/Dockerfile" />
                                <copy todir="${project.build.directory}" file="${HOME}/IdeaProjects/yofc-iot/com.yofc.iot.repack/com.yofc.iot.repack.vertx.db/target/yofc-iot-repack-vertx-db_0.0.1-SNAPSHOT.dp" />
                                <copy todir="${project.build.directory}" file="${HOME}/IdeaProjects/yofc-iot/com.yofc.iot.api/com.yofc.iot.api.comp/target/yofc-iot-api-comp_0.0.1-SNAPSHOT.dp" />
                                <copy todir="${project.build.directory}" file="${HOME}/IdeaProjects/yofc-iot/com.yofc.iot.apps/com.yofc.iot.apps.comp/target/yofc-iot-apps-comp_0.0.1-SNAPSHOT.dp" />
                                <copy todir="${project.build.directory}" file="${HOME}/IdeaProjects/yofc-iot/com.yofc.iot.apps/com.yofc.iot.apps.opcuaserver/target/yofc-iot-apps-opcuaserver_0.0.1-SNAPSHOT.dp" />
                                <copy todir="${project.build.directory}" file="${HOME}/IdeaProjects/yofc-iot/com.yofc.iot.apps/com.yofc.iot.apps.influxdb/target/yofc-iot-apps-influxdb_0.0.1-SNAPSHOT.dp" />
                                <copy todir="${project.build.directory}" file="${HOME}/IdeaProjects/yofc-iot/com.yofc.iot.apps/com.yofc.iot.apps.influxdbv1/target/yofc-iot-apps-influxdbv1_0.0.1-SNAPSHOT.dp" />
                                <exec executable="docker" dir="${project.build.directory}" failonerror="true">
                                    <arg value="build"/>
                                    <arg value="-t"/>
                                    <arg value="base-kura-docker:latest"/>
                                    <arg value="."/>
                                </exec>
                              </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.vafer</groupId>
                <artifactId>jdeb</artifactId>
                <version>${jdeb-version}</version>
                <executions>
                    <execution>
                        <id>docker-aarch64-nn-deb</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jdeb</goal>
                        </goals>
                        <configuration>
                            <verbose>true</verbose>
                            <deb>${basedir}/target/kura_${package.version}-${package.revision}_docker-aarch64-nn_installer.deb</deb>
                            <snapshotExpand>true</snapshotExpand>
                            <snapshotTemplate>${package.snapshot}</snapshotTemplate>
                            <controlDir>${basedir}/../src/main/resources/docker-aarch64-nn/deb/control</controlDir>
                            <skipPOMs>false</skipPOMs>
                            <dataSet>
                                <data>
                                    <src>${basedir}/target/kura_${project.version}_docker-aarch64-nn.zip</src>
                                    <type>file</type>
                                    <mapper>
                                        <type>perm</type>
                                        <prefix>/tmp</prefix>
                                    </mapper>
                                </data>
                            </dataSet>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>