#!/bin/bash
#
# Copyright (c) 2023, 2026 Eurotech and/or its affiliates and others
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#  Eurotech
#

INSTALL_DIR=/opt/eclipse

case "$1" in
    purge|remove)
        # Remove kura installation tree (plugins/ + siblings/)
        if [ -d "${INSTALL_DIR}/kura" ] ; then
            ${INSTALL_DIR}/kura/.data/manage_kura_users.sh -u 2>/dev/null || true
            PARENT=$(readlink -f "${INSTALL_DIR}/kura" 2>/dev/null || echo "")
            rm -rf "${INSTALL_DIR}/kura"
            if [ -n "${PARENT}" ] && [ -d "${PARENT}" ]; then
                rm -rf "${PARENT}"
            fi
        fi

        # Restore /etc/network/interfaces.old
        if [ -f /etc/network/interfaces.old ]; then
            mv /etc/network/interfaces.old /etc/network/interfaces
        fi

        # Restore /etc/default/dnsmasq.old
        if [ -f /etc/default/dnsmasq.old ]; then
            mv /etc/default/dnsmasq.old /etc/default/dnsmasq
        fi

        rm -rf /tmp/.kura /tmp/kura
        rm -f /var/run/kura.pid
        ;;
    upgrade|failed-upgrade)
        ;;
esac
exit 0
