/*******************************************************************************
 * Copyright (c) 2023, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 * Content with portions generated by generative AI platform
 *******************************************************************************/
package org.eclipse.kura.internal.db.sqlite.provider;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.File;
import java.nio.file.Path;
import java.util.Optional;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.Mockito;
import org.osgi.framework.BundleContext;

public class SqliteProviderActivatorTest {

    @Test
    public void shouldSetSqliteTempDirIfUnset() {
        givenNoSystemPropertyValue("org.sqlite.tmpdir");
        givenBundleStorageAreaPath("/tmp/foo");

        whenActivatorIsStarted();

        thenNoExceptionIsThrown();
        thenSystemPropertyValueIs("org.sqlite.tmpdir", absolutePathOf("/tmp/foo"));
    }

    @Test
    public void shouldNotSetSqliteTempDirIfBundleStorageAreaIsNotAvailable() {
        givenNoSystemPropertyValue("org.sqlite.tmpdir");
        givenNoBundleStorageArea();

        whenActivatorIsStarted();

        thenNoExceptionIsThrown();
        thenSystemPropertyValueIs("org.sqlite.tmpdir", null);
    }

    @Test
    public void shouldChangeSqliteTempDirIfSetButNonExisting() {
        givenSystemProperty("org.sqlite.tmpdir", "bar");
        givenBundleStorageAreaPath("/tmp/foo");

        whenActivatorIsStarted();

        thenNoExceptionIsThrown();
        thenSystemPropertyValueIs("org.sqlite.tmpdir", absolutePathOf("/tmp/foo"));
    }

    @Test
    public void shouldNotChangeSqliteTempDirIfSetAndExisting() {
        givenSystemProperty("org.sqlite.tmpdir", temporaryDirectoryPath());
        givenBundleStorageAreaPath("/tmp/foo");

        whenActivatorIsStarted();

        thenNoExceptionIsThrown();
        thenSystemPropertyValueIs("org.sqlite.tmpdir", temporaryDirectoryPath());
    }

    @Test
    public void shouldClearSqliteTempDirOnStopIfChanged() {
        givenNoSystemPropertyValue("org.sqlite.tmpdir");
        givenBundleStorageAreaPath("/tmp/foo");
        givenStartedActivator();

        whenActivatorIsStopped();

        thenNoExceptionIsThrown();
        thenSystemPropertyValueIs("org.sqlite.tmpdir", null);
    }

    @Test
    public void shouldNotClearSqliteTempDirOnStopIfNotChanged() {
        givenSystemProperty("org.sqlite.tmpdir", temporaryDirectoryPath());
        givenBundleStorageAreaPath("/tmp/foo");
        givenStartedActivator();

        whenActivatorIsStopped();

        thenNoExceptionIsThrown();
        thenSystemPropertyValueIs("org.sqlite.tmpdir", temporaryDirectoryPath());
    }

    private final BundleContext bundleContext = Mockito.mock(BundleContext.class);
    private Optional<Exception> exception = Optional.empty();
    @TempDir
    Path temporaryDirectory;
    private String originalTemporaryDirectory;

    @BeforeEach
    void rememberSqliteDirectory() {
        this.originalTemporaryDirectory = System.getProperty("org.sqlite.tmpdir");
    }

    @AfterEach
    void restoreSqliteDirectory() {
        if (this.originalTemporaryDirectory == null) {
            System.clearProperty("org.sqlite.tmpdir");
        } else {
            System.setProperty("org.sqlite.tmpdir", this.originalTemporaryDirectory);
        }
    }
    private SqliteProviderActivator activator = new SqliteProviderActivator();

    private void givenBundleStorageAreaPath(String path) {
        Mockito.when(bundleContext.getDataFile("")).thenReturn(new File(path));
    }

    private void givenNoBundleStorageArea() {
        Mockito.when(bundleContext.getDataFile("")).thenReturn(null);
    }

    private void givenSystemProperty(final String key, final String value) {
        System.setProperty(key, value);
    }

    private void givenNoSystemPropertyValue(final String key) {
        System.clearProperty(key);
    }

    private void givenStartedActivator() {
        whenActivatorIsStarted();
        thenNoExceptionIsThrown();
    }

    private void whenActivatorIsStarted() {
        try {
            this.exception = Optional.empty();
            activator.start(bundleContext);
        } catch (Exception e) {
            this.exception = Optional.of(e);
        }
    }

    private void whenActivatorIsStopped() {
        try {
            this.exception = Optional.empty();
            activator.stop(bundleContext);
        } catch (Exception e) {
            this.exception = Optional.of(e);
        }
    }

    private void thenSystemPropertyValueIs(final String key, final String value) {
        assertEquals(value, System.getProperty(key));
    }

    private void thenNoExceptionIsThrown() {
        assertEquals(Optional.empty(), this.exception);
    }

    private String absolutePathOf(final String path) {
        return new File(path).getAbsolutePath();
    }

    private String temporaryDirectoryPath() {
        return this.temporaryDirectory.toAbsolutePath().toString();
    }
}
