<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2026 Eurotech and/or its affiliates and others

    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.eclipse.kura</groupId>
        <artifactId>target-platform</artifactId>
        <version>6.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>target-platform-pde-deps</artifactId>
    <packaging>pom</packaging>
    <name>Kura target platform PDE dependencies</name>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>target-platform-bom</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>org.apache.qpid.jms.client</artifactId>
        </dependency>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>com.alibaba.fastjson2</artifactId>
        </dependency>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>io.vertx.auth-common</artifactId>
        </dependency>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>io.vertx.bridge-common</artifactId>
        </dependency>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>io.vertx.core</artifactId>
        </dependency>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>io.vertx.core-logging</artifactId>
        </dependency>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>io.vertx.http-proxy</artifactId>
        </dependency>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>io.vertx.mqtt</artifactId>
        </dependency>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>io.vertx.tcp-eventbus-bridge</artifactId>
        </dependency>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>io.vertx.uri-template</artifactId>
        </dependency>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>io.vertx.web</artifactId>
        </dependency>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>io.vertx.web-client</artifactId>
        </dependency>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>io.vertx.web-common</artifactId>
        </dependency>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>tel.schich.javacan-core</artifactId>
        </dependency>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>com.sun.xml.bind.jaxb-osgi</artifactId>
        </dependency>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>org.gwtbootstrap3</artifactId>
        </dependency>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>org.gwtproject.gwt-servlet-jakarta</artifactId>
        </dependency>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>com.digitalpetri.fsm.strict-machine</artifactId>
        </dependency>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>com.digitalpetri.netty.channel-fsm</artifactId>
        </dependency>
        <dependency>
            <groupId>p2.osgi.bundle</groupId>
            <artifactId>org.eclipse.paho.mqttv5.client</artifactId>
        </dependency>
    </dependencies>
</project>
