<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (c) 2025, 2026 Eurotech and contributors.
     SPDX-License-Identifier: EPL-2.0 -->
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>${groupId}</groupId><artifactId>${artifactId}</artifactId>
    <version>${version}</version><relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>${artifactId}.tests</artifactId><packaging>pom</packaging>
  <modules><module>${artifactId}.bundle.test</module></modules>
</project>
