<?xml version="1.0"?>
<!--
    Copyright (c) 2011, 2025 Eurotech and/or its affiliates and others
  
    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/
 
    SPDX-License-Identifier: EPL-2.0
 
    Contributors:
     Eurotech
-->
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
    xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.eclipse.kura</groupId>
        <artifactId>target-platform</artifactId>
        <version>6.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>p2-repo-equinox</artifactId>
    <packaging>pom</packaging>

    <build>
        <plugins>
			<plugin>
				<groupId>org.reficio</groupId>
				<artifactId>p2-maven-plugin</artifactId>
				<version>${p2-maven-plugin.version}</version>
				<executions>
					<execution>
						<id>generate-p2-site</id>
						<phase>initialize</phase>
						<goals>
							<goal>site</goal>
						</goals>
						<configuration>
                            <artifacts>
                                <artifact>
                                    <id>org.osgi:org.osgi.service.cm:${org.osgi.service.cm.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.osgi:org.osgi.service.component:${org.osgi.service.component.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.osgi:org.osgi.service.coordinator:${org.osgi.service.coordinator.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.osgi:org.osgi.service.device:${org.osgi.service.device.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.osgi:org.osgi.service.event:${org.osgi.service.event.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.osgi:org.osgi.service.log.stream:${org.osgi.service.log.stream.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.osgi:org.osgi.service.metatype:${org.osgi.service.metatype.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.osgi:org.osgi.service.prefs:${org.osgi.service.prefs.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.osgi:org.osgi.service.provisioning:${org.osgi.service.provisioning.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.osgi:org.osgi.service.upnp:${org.osgi.service.upnp.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.osgi:org.osgi.service.useradmin:${org.osgi.service.useradmin.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.osgi:org.osgi.service.wireadmin:${org.osgi.service.wireadmin.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.osgi:org.osgi.util.function:${org.osgi.util.function.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.osgi:org.osgi.util.measurement:${org.osgi.util.measurement.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.osgi:org.osgi.util.position:${org.osgi.util.position.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.osgi:org.osgi.util.promise:${org.osgi.util.promise.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.osgi:org.osgi.util.pushstream:${org.osgi.util.pushstream.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.osgi:org.osgi.util.xml:${org.osgi.util.xml.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.eclipse.platform:org.eclipse.equinox.cm:${org.eclipse.equinox.cm.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.eclipse.platform:org.eclipse.equinox.common:${org.eclipse.equinox.common.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.eclipse.platform:org.eclipse.equinox.console:${org.eclipse.equinox.console.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.eclipse.platform:org.eclipse.equinox.registry:${org.eclipse.equinox.registry.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.eclipse.platform:org.eclipse.equinox.event:${org.eclipse.equinox.event.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.eclipse.platform:org.eclipse.equinox.io:${org.eclipse.equinox.io.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.eclipse.platform:org.eclipse.equinox.metatype:${org.eclipse.equinox.metatype.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.eclipse.platform:org.eclipse.equinox.launcher:${org.eclipse.equinox.launcher.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.eclipse.platform:org.eclipse.equinox.util:${org.eclipse.equinox.util.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.eclipse.platform:org.eclipse.equinox.wireadmin:${org.eclipse.equinox.wireadmin.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.apache.felix:org.apache.felix.scr:${org.apache.felix.scr.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.eclipse.platform:org.eclipse.core.jobs:${org.eclipse.core.jobs.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.eclipse.platform:org.eclipse.equinox.preferences:${org.eclipse.equinox.preferences.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.eclipse.platform:org.eclipse.core.contenttype:${org.eclipse.core.contenttype.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.eclipse.platform:org.eclipse.equinox.app:${org.eclipse.equinox.app.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.eclipse.platform:org.eclipse.osgi:${org.eclipse.osgi.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.eclipse.platform:org.eclipse.osgi.util:${org.eclipse.osgi.util.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.apache.felix:org.apache.felix.gogo.command:${org.apache.felix.gogo.command.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.apache.felix:org.apache.felix.gogo.runtime:${org.apache.felix.gogo.runtime.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.apache.felix:org.apache.felix.gogo.shell:${org.apache.felix.gogo.shell.version}</id>
                                    <source>true</source>
                                    <transitive>false</transitive>
                                </artifact>
                                
                            </artifacts>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
